# Getting Started with ScraperNHL

Welcome to ScraperNHL! This notebook will teach you the basics of using the new unified API.

## What is ScraperNHL?

ScraperNHL is a Python package for scraping hockey data from multiple leagues:
- NHL (National Hockey League)
- QMJHL (Quebec Major Junior Hockey League)
- OHL (Ontario Hockey League)
- WHL (Western Hockey League)
- AHL (American Hockey League)

## New in Version 3.0

The package has been completely redesigned with:
- **Unified API**: One consistent interface for all leagues
- **Simpler Design**: Easy functional API or flexible OOP API
- **Better Performance**: Built-in caching and rate limiting
- **Clean Data**: Automatic normalization and transformations

In [1]:
# %load_ext autoreload
# %autoreload 2

## Installation

Make sure you have scrapernhl installed:

```bash
pip install scrapernhl
```

Or from source:

```bash
pip install -e .
```

## Method 1: Functional API (Recommended for Beginners)

The simplest way to use ScraperNHL is with the `scrape()` function:

In [2]:
from scrapernhl import scrape
import pandas as pd

pd.set_option('display.max_columns', None)

# Get player stats from the QMJHL
stats = scrape('qmjhl', 'stats', season=90, position='skaters', limit=10)

print(f"Got {len(stats)} players")
print("\nTop 10 players:")
display(stats[['name', 'teamCode', 'G', 'A', 'PTS']].head(10))

Got 10 players

Top 10 players:

                   name teamCode   G   A  PTS
0    Radulov, Alexander      Que  61  91  152
1     Lascek, Stanislav      Chi  47  88  135
2     Boisclair, Maxime      Chi  70  60  130
3  Latendresse, Olivier      VdO  41  84  125
4     Desharnais, David      Chi  33  85  118
5          Aubin, Brent      Que  57  60  117
6      Brassard, Derick      Dru  44  72  116
7         Bourret, Alex      Sha  44  70  114
8      Dupuis, Philippe      Mon  32  76  108
9          Roy, Mathieu      Bat  50  54  104

In [3]:
stats.head()

,player_id,name,position,rookie,jerseyNumber,teamCode,GP,GWG,G,S,Sh%,A,PTS,PTS/GP,+/-,PIM,PIM/GP,PPG,PPA,SHG,SHA,SG,rank,lastName,firstName,playerName,teamId,teamLogo,season,league,seasonName,seasonStartYear,seasonEndYear,scraped_at
0,9261,"Radulov, Alexander",RW,0,22,Que,62,9,61,332,18.4,91,152,2.45,53,101,1.63,22,44,10,6,4,1,Radulov,Alexander,"Radulov, Alexander",9,https://assets.leaguestat.com/lhjmq/logos/9_90...,90,qmjhl,2005-06 | Regular Season,2005,2006,2026-03-07T02:20:51.232434+00:00
1,9734,"Lascek, Stanislav",RW,0,17,Chi,64,9,47,344,13.7,88,135,2.11,42,96,1.50,20,55,3,2,3,2,Lascek,Stanislav,"Lascek, Stanislav",10,https://assets.leaguestat.com/lhjmq/logos/10.png,90,qmjhl,2005-06 | Regular Season,2005,2006,2026-03-07T02:20:51.232434+00:00
2,10615,"Boisclair, Maxime",LW,0,97,Chi,70,12,70,321,21.8,60,130,1.86,39,97,1.39,43,24,3,1,0,3,Boisclair,Maxime,"Boisclair, Maxime",10,https://assets.leaguestat.com/lhjmq/logos/10.png,90,qmjhl,2005-06 | Regular Season,2005,2006,2026-03-07T02:20:51.232434+00:00
3,9732,"Latendresse, Olivier",C,0,44,VdO,70,6,41,359,11.4,84,125,1.79,5,83,1.19,16,47,4,2,2,4,Latendresse,Olivier,"Latendresse, Olivier",15,https://assets.leaguestat.com/lhjmq/logos/15.png,90,qmjhl,2005-06 | Regular Season,2005,2006,2026-03-07T02:20:51.232434+00:00
4,10288,"Desharnais, David",C,0,15,Chi,63,6,33,161,20.5,85,118,1.87,45,44,0.70,20,52,2,3,2,5,Desharnais,David,"Desharnais, David",10,https://assets.leaguestat.com/lhjmq/logos/10.png,90,qmjhl,2005-06 | Regular Season,2005,2006,2026-03-07T02:20:51.232434+00:00

### Available Data Types

You can request different types of data:

1. **'pbp'** - Play-by-play data for a specific game
2. **'stats'** - Player statistics for skaters or goalies
3. **'schedule'** - Schedule for a team or entire league
4. **'roster'** - Team roster with player details
5. **'standings'** - Current league standings

In [4]:
# Get schedule for a team
schedule = scrape('ohl', 'schedule', season=83, team_id=16)

print(f"Games in schedule: {len(schedule)}")
display(schedule[['date', 'homeTeam', 'awayTeam']].head())

Games in schedule: 683

        date             homeTeam             awayTeam
0 2025-09-18  North Bay Battalion      Oshawa Generals
1 2025-09-18   Peterborough Petes  Brampton Steelheads
2 2025-09-19  Brampton Steelheads      Niagara IceDogs
3 2025-09-19    Kitchener Rangers   Brantford Bulldogs
4 2025-09-19       London Knights    Owen Sound Attack

In [5]:
schedule.head()

,homeId,awayId,gameId,dateString,homeScore,awayScore,gameStatus,homeCity,awayCity,venue,homeTeam,homeCode,homeDivision,homeLogo,awayTeam,awayCode,awayDivision,awayLogo,season,league,seasonName,seasonStartDate,seasonStartYear,seasonEndYear,dayOfWeek,monthText,monthNum,day,year,date,scraped_at
0,19,4,28150,"Thu, Sep 18",4,2,Final,North Bay,Oshawa,Boart Longyear Memorial Gardens,North Bay Battalion,NB,2,https://assets.leaguestat.com/ohl/logos/19.png,Oshawa Generals,OSH,1,https://assets.leaguestat.com/ohl/logos/4.png,83,ohl,2025-26 Regular Season,2025-09-16,2025,2026,Thu,Sep,09,18,2025,2025-09-18,2026-03-07T02:20:52.091052+00:00
1,6,18,28151,"Thu, Sep 18",6,3,Final,Peterborough,Brampton,Peterborough Memorial Centre,Peterborough Petes,PBO,1,https://assets.leaguestat.com/ohl/logos/6.png,Brampton Steelheads,BRAM,2,https://assets.leaguestat.com/ohl/logos/50x50/...,83,ohl,2025-26 Regular Season,2025-09-16,2025,2026,Thu,Sep,09,18,2025,2025-09-18,2026-03-07T02:20:52.091052+00:00
2,18,20,28152,"Fri, Sep 19",4,1,Final,Brampton,Niagara,CAA Centre,Brampton Steelheads,BRAM,2,https://assets.leaguestat.com/ohl/logos/50x50/...,Niagara IceDogs,NIAG,2,https://assets.leaguestat.com/ohl/logos/20.png,83,ohl,2025-26 Regular Season,2025-09-16,2025,2026,Fri,Sep,09,19,2025,2025-09-19,2026-03-07T02:20:52.091052+00:00
3,10,1,28155,"Fri, Sep 19",4,3,Final OT,Kitchener,Brantford,Kitchener Memorial Auditorium,Kitchener Rangers,KIT,4,https://assets.leaguestat.com/ohl/logos/10.png,Brantford Bulldogs,BFD,1,https://assets.leaguestat.com/ohl/logos/1.png,83,ohl,2025-26 Regular Season,2025-09-16,2025,2026,Fri,Sep,09,19,2025,2025-09-19,2026-03-07T02:20:52.091052+00:00
4,14,11,28156,"Fri, Sep 19",2,3,Final OT,London,Owen Sound,Canada Life Place,London Knights,LDN,4,https://assets.leaguestat.com/ohl/logos/14.png,Owen Sound Attack,OS,4,https://assets.leaguestat.com/ohl/logos/11.png,83,ohl,2025-26 Regular Season,2025-09-16,2025,2026,Fri,Sep,09,19,2025,2025-09-19,2026-03-07T02:20:52.091052+00:00

In [6]:
# Get league standings
standings = scrape('whl', 'standings', season=289)

print("WHL Standings:")
display(standings[['team_code', 'wins', 'losses', 'points']].head())

WHL Standings:

  team_code wins losses points
0        PA   45      9     96
1       BDN   35     24     71
2       SAS   31     25     68
3       REG   23     29     53
4        MJ   21     33     49

In [7]:
standings.head()

,team_code,wins,losses,ties,ot_losses,ot_wins,shootout_wins,shootout_losses,regulation_wins,row,points,penalty_minutes,streak,goals_for,goals_against,goals_diff,percentage,games_played,rank,past_10,name,prefixTeam,season,league,seasonName,seasonStartYear,seasonEndYear,teamId,teamName,teamLogo,scraped_at
0,PA,45,9,0,5,3,2,1,40,43,96,686,0-1-0-0,273,153,120,0.800,60,1,7-2-0-1,xy - Prince Albert Raiders,xy,289,whl,2025 - 26 Regular Season,2025,2026,209,Prince Albert Raiders,https://assets.leaguestat.com/whl/logos/209.png,2026-03-07T02:20:52.517355+00:00
1,BDN,35,24,0,1,4,2,0,29,33,71,778,0-1-0-0,241,215,26,0.592,60,2,7-3-0-0,x - Brandon Wheat Kings,x,289,whl,2025 - 26 Regular Season,2025,2026,201,Brandon Wheat Kings,https://assets.leaguestat.com/whl/logos/50x50/...,2026-03-07T02:20:52.517355+00:00
2,SAS,31,25,0,4,4,2,2,25,29,68,660,1-0-0-0,204,207,-3,0.548,62,3,5-3-1-1,x - Saskatoon Blades,x,289,whl,2025 - 26 Regular Season,2025,2026,213,Saskatoon Blades,https://assets.leaguestat.com/whl/logos/50x50/...,2026-03-07T02:20:52.517355+00:00
3,REG,23,29,0,6,4,1,1,18,22,53,682,0-1-0-0,212,249,-37,0.449,59,4,7-3-0-0,Regina Pats,None,289,whl,2025 - 26 Regular Season,2025,2026,212,Regina Pats,https://assets.leaguestat.com/whl/logos/212.png,2026-03-07T02:20:52.517355+00:00
4,MJ,21,33,0,5,4,1,2,16,20,49,623,1-0-0-0,212,269,-57,0.402,61,5,2-7-1-0,Moose Jaw Warriors,None,289,whl,2025 - 26 Regular Season,2025,2026,207,Moose Jaw Warriors,https://assets.leaguestat.com/whl/logos/207.png,2026-03-07T02:20:52.517355+00:00

In [8]:
scrape('whl', 'standings', season=285).head()

,team_code,wins,losses,ties,ot_losses,ot_wins,shootout_wins,shootout_losses,regulation_wins,row,points,penalty_minutes,streak,goals_for,goals_against,goals_diff,percentage,games_played,rank,past_10,name,prefixTeam,season,league,seasonName,seasonStartYear,seasonEndYear,teamId,teamName,teamLogo,scraped_at
0,PA,39,23,0,5,5,3,1,31,36,84,776,5-0-0-0,253,228,25,0.618,68,1,6-3-1-0,xy - Prince Albert Raiders,xy,285,whl,2024 - 25 Regular Season,2024,2025,209,Prince Albert Raiders,https://assets.leaguestat.com/whl/logos/209.png,2026-03-07T02:20:53.045714+00:00
1,BDN,38,23,0,4,3,1,3,34,37,83,750,2-0-0-0,255,213,42,0.610,68,2,6-4-0-0,x - Brandon Wheat Kings,x,285,whl,2024 - 25 Regular Season,2024,2025,201,Brandon Wheat Kings,https://assets.leaguestat.com/whl/logos/50x50/...,2026-03-07T02:20:53.045714+00:00
2,SAS,37,23,0,4,8,1,4,28,36,82,550,0-1-1-0,235,218,17,0.603,68,3,6-3-1-0,x - Saskatoon Blades,x,285,whl,2024 - 25 Regular Season,2024,2025,213,Saskatoon Blades,https://assets.leaguestat.com/whl/logos/50x50/...,2026-03-07T02:20:53.045714+00:00
3,SC,35,30,0,1,6,4,2,25,31,73,756,0-1-0-0,240,256,-16,0.537,68,4,4-5-0-1,x - Swift Current Broncos,x,285,whl,2024 - 25 Regular Season,2024,2025,216,Swift Current Broncos,https://assets.leaguestat.com/whl/logos/216.png,2026-03-07T02:20:53.045714+00:00
4,REG,16,44,0,5,5,2,3,9,14,40,765,0-2-0-0,170,285,-115,0.294,68,5,1-8-0-1,Regina Pats,None,285,whl,2024 - 25 Regular Season,2024,2025,212,Regina Pats,https://assets.leaguestat.com/whl/logos/212.png,2026-03-07T02:20:53.045714+00:00

In [9]:
scrape('qmjhl', 'standings', season=211).head()

,team_code,wins,losses,ot_losses,ot_wins,shootout_wins,shootout_losses,row,points,penalty_minutes,streak,goals_for,goals_against,goals_diff,percentage,overall_rank,games_played,rank,past_10,name,prefixTeam,season,league,seasonName,seasonStartYear,seasonEndYear,teamId,teamName,teamLogo,scraped_at
0,Mon,44,10,2,3,5,2,39,92,712,3-0-0-0,277,152,125,0.793,1,58,1,7-2-0-1,"x - Moncton, Wildcats",x,211,qmjhl,2025-26 | Regular Season,2025,2026,1,"Moncton, Wildcats",https://assets.leaguestat.com/lhjmq/logos/1.png,2026-03-07T02:20:53.269949+00:00
1,Chi,43,9,3,1,1,2,42,91,530,3-0-0-0,276,137,139,0.798,2,57,2,9-1-0-0,"x - Chicoutimi, Saguenéens",x,211,qmjhl,2025-26 | Regular Season,2025,2026,10,"Chicoutimi, Saguenéens",https://assets.leaguestat.com/lhjmq/logos/10.png,2026-03-07T02:20:53.269949+00:00
2,NFL,35,20,2,5,2,1,33,73,734,0-1-0-0,222,191,31,0.629,6,58,3,8-1-1-0,"x - Newfoundland, Regiment",x,211,qmjhl,2025-26 | Regular Season,2025,2026,2,"Newfoundland, Regiment",https://assets.leaguestat.com/lhjmq/logos/2_21...,2026-03-07T02:20:53.269949+00:00
3,Cha,29,20,2,5,3,6,26,66,639,7-0-0-0,203,214,-11,0.579,8,57,4,7-3-0-0,"x - Charlottetown, Islanders",x,211,qmjhl,2025-26 | Regular Season,2025,2026,7,"Charlottetown, Islanders",https://assets.leaguestat.com/lhjmq/logos/7.png,2026-03-07T02:20:53.269949+00:00
4,Cap,27,21,2,1,3,9,24,65,585,0-2-0-1,160,184,-24,0.551,9,59,5,3-5-0-2,"x - Cape Breton, Eagles",x,211,qmjhl,2025-26 | Regular Season,2025,2026,3,"Cape Breton, Eagles",https://assets.leaguestat.com/lhjmq/logos/3.png,2026-03-07T02:20:53.269949+00:00

In [10]:
scrape('qmjhl', 'roster', team=1,season=211).head()

,shoots,birthplace,player_id,birthdate,tp_jersey_number,rookie,position,h,w,name,catches,lastName,firstName,teamId,teamName,teamCode,teamLogo,season,league,seasonName,seasonStartYear,seasonEndYear,n_birthplace,birthCity,birthCountry,birthState,height_cm,shootsCatches,scraped_at
0,L,"St.Andrews, NB, Canada",19539,2006-08-03,9,0,C,"6'04""",225,"Smith, Gabe",NaN,Smith,Gabe,1,"Moncton, Wildcats",Mon,https://assets.leaguestat.com/lhjmq/logos/1.png,211,qmjhl,2025-26 | Regular Season,2025,2026,3,St.Andrews,Canada,NB,193.04,L,2026-03-07T02:20:53.350396+00:00
1,R,"Ste-Foy, QC, Canada",19090,2005-09-22,10,0,RW,"5'10""",183,"Mercier, Alex",NaN,Mercier,Alex,1,"Moncton, Wildcats",Mon,https://assets.leaguestat.com/lhjmq/logos/1.png,211,qmjhl,2025-26 | Regular Season,2025,2026,3,Ste-Foy,Canada,QC,177.80,R,2026-03-07T02:20:53.350396+00:00
2,L,"Fairbanks, AK, United States",22466,2006-02-14,12,0,LW,"6'00""",191,"Binkley, Simon",NaN,Binkley,Simon,1,"Moncton, Wildcats",Mon,https://assets.leaguestat.com/lhjmq/logos/1.png,211,qmjhl,2025-26 | Regular Season,2025,2026,3,Fairbanks,United States,AK,182.88,L,2026-03-07T02:20:53.350396+00:00
3,R,"Norwell, MA, United States",20414,2007-02-16,14,1,C,"6'01""",209,"Mutryn, Teddy",NaN,Mutryn,Teddy,1,"Moncton, Wildcats",Mon,https://assets.leaguestat.com/lhjmq/logos/1.png,211,qmjhl,2025-26 | Regular Season,2025,2026,3,Norwell,United States,MA,185.42,R,2026-03-07T02:20:53.350396+00:00
4,R,"Danbury, CT, United States",24195,2006-01-07,17,0,RW,"6'00""",215,"Wingfield, Jacob",NaN,Wingfield,Jacob,1,"Moncton, Wildcats",Mon,https://assets.leaguestat.com/lhjmq/logos/1.png,211,qmjhl,2025-26 | Regular Season,2025,2026,3,Danbury,United States,CT,182.88,R,2026-03-07T02:20:53.350396+00:00

## Method 2: Object-Oriented API (Advanced Usage)

For more control, you can create a `HockeyScraper` object:

### ✨ NEW: Automatic Bootstrap Fetching

When you create a scraper for non-NHL leagues, bootstrap data (teams, seasons, divisions) is **automatically fetched**!

In [11]:
from scrapernhl import HockeyScraper


for league in ['ohl', 'whl', 'qmjhl', 'ahl', 'pwhl']:
    # Create a scraper for the league
    scraper = HockeyScraper(league)
    season = scraper.config.default_season

    # Bootstrap data is automatically fetched!
    print(f"Bootstrap auto-fetched on initialization:")
    print(f"  League ID: {scraper.current_league_id}")
    print(f"  Season ID: {scraper.current_season_id}")
    print(f"  Teams: {len(scraper.teams)}")

    # Access team data easily
    print(f"\nFirst 5 teams:")
    for team in scraper.teams[:5]:
        print(f"  - {team['name']} (ID: {team['id']})")

    # Use methods to get data
    stats = scraper.player_stats(season=season, position='skaters', limit=15)
    schedule = scraper.schedule(season=season, team='all')  # 'all' or team_id
    standings = scraper.standings(season=season)

    print(f"\nData retrieved:")
    print(f"  Stats: {len(stats)} rows")
    print(f"  Schedule: {len(schedule)} games")
    print(f"  Standings: {len(standings)} teams")

    bootstrap_keys = scraper.bootstrap_data.keys()
    print(f"\nBootstrap data keys: {bootstrap_keys}")

Bootstrap auto-fetched on initialization:
  League ID: 1
  Season ID: 83
  Teams: 20

First 5 teams:
  - Barrie Colts (ID: 7)
  - Brampton Steelheads (ID: 18)
  - Brantford Bulldogs (ID: 1)
  - Erie Otters (ID: 8)
  - Flint Firebirds (ID: 13)

Data retrieved:
  Stats: 15 rows
  Schedule: 683 games
  Standings: 20 teams

Bootstrap data keys: dict_keys(['firebaseUrl', 'firebaseToken', 'firebaseApiKey', 'current_league_id', 'current_season_id', 'leagues', 'seasons', 'conferences', 'conferencesAll', 'divisions', 'divisionsAll', 'first_season_year', 'regularSeasons', 'playoffSeasons', 'teams', 'teamsNoAll', 'months', 'monthsAll', 'positions', 'goalies', 'rosterstatus', 'standingsFooter', 'rosterFooter', 'playerStatsFooter', 'showExpandedGoaliesOption', 'showRosterStatus', 'quickViews', 'dailySchedRefreshToggle', 'playerNoPicLogoOverride', 'svfConfig', 'svfLanguages', 'svfLang', 'player_shot_heat_map'])
Bootstrap auto-fetched on initialization:
  League ID: 26
  Season ID: 289
  Teams: 23

First 5 teams:
  - Brandon Wheat Kings (ID: 201)
  - Calgary Hitmen (ID: 202)
  - Edmonton Oil Kings (ID: 228)
  - Everett Silvertips (ID: 226)
  - Kamloops Blazers (ID: 203)

Data retrieved:
  Stats: 15 rows
  Schedule: 782 games
  Standings: 23 teams

Bootstrap data keys: dict_keys(['firebaseUrl', 'firebaseToken', 'firebaseApiKey', 'current_league_id', 'current_season_id', 'leagues', 'seasons', 'conferences', 'conferencesAll', 'divisions', 'divisionsAll', 'first_season_year', 'regularSeasons', 'playoffSeasons', 'teams', 'teamsNoAll', 'months', 'monthsAll', 'positions', 'goalies', 'rosterstatus', 'standingsFooter', 'rosterFooter', 'playerStatsFooter', 'showExpandedGoaliesOption', 'showRosterStatus', 'quickViews', 'dailySchedRefreshToggle', 'dailySchedChangeoverHour', 'playerNoPicLogoOverride', 'svfConfig', 'svfLanguages', 'svfLang', 'player_shot_heat_map'])
Bootstrap auto-fetched on initialization:
  League ID: 1
  Season ID: 211
  Teams: 18

First 5 teams:
  - Baie-Comeau, Drakkar (ID: 16)
  - Blainville-Boisbriand, Armada (ID: 19)
  - Cape Breton, Eagles (ID: 3)
  - Charlottetown, Islanders (ID: 7)
  - Chicoutimi, Saguenéens (ID: 10)

Data retrieved:
  Stats: 15 rows
  Schedule: 578 games
  Standings: 18 teams

Bootstrap data keys: dict_keys(['firebaseUrl', 'firebaseToken', 'firebaseApiKey', 'current_league_id', 'current_season_id', 'leagues', 'seasons', 'conferences', 'conferencesAll', 'divisions', 'divisionsAll', 'first_season_year', 'regularSeasons', 'playoffSeasons', 'teams', 'teamsNoAll', 'months', 'monthsAll', 'positions', 'goalies', 'rosterstatus', 'standingsFooter', 'rosterFooter', 'playerStatsFooter', 'showExpandedGoaliesOption', 'showRosterStatus', 'quickViews', 'dailySchedRefreshToggle', 'playerNoPicLogoOverride', 'svfConfig', 'svfLanguages', 'svfLang', 'player_shot_heat_map'])
Bootstrap auto-fetched on initialization:
  League ID: 4
  Season ID: 90
  Teams: 32

First 5 teams:
  - Abbotsford Canucks (ID: 440)
  - Bakersfield Condors (ID: 402)
  - Belleville Senators (ID: 413)
  - Bridgeport Islanders (ID: 317)
  - Calgary Wranglers (ID: 444)

Data retrieved:
  Stats: 15 rows
  Schedule: 1152 games
  Standings: 32 teams

Bootstrap data keys: dict_keys(['firebaseUrl', 'firebaseToken', 'firebaseApiKey', 'current_league_id', 'current_season_id', 'leagues', 'seasons', 'conferences', 'conferencesAll', 'divisions', 'divisionsAll', 'first_season_year', 'regularSeasons', 'playoffSeasons', 'teams', 'teamsNoAll', 'months', 'monthsAll', 'positions', 'goalies', 'rosterstatus', 'standingsFooter', 'rosterFooter', 'playerStatsFooter', 'showExpandedGoaliesOption', 'showRosterStatus', 'quickViews', 'dailySchedRefreshToggle', 'dailySchedChangeoverHour', 'playerNoPicLogoOverride', 'svfConfig', 'svfLanguages', 'svfLang', 'player_shot_heat_map'])
Bootstrap auto-fetched on initialization:
  League ID: 1
  Season ID: 8
  Teams: 8

First 5 teams:
  - Boston Fleet (ID: 1)
  - Minnesota Frost (ID: 2)
  - Montréal Victoire (ID: 3)
  - New York Sirens (ID: 4)
  - Ottawa Charge (ID: 5)

Data retrieved:
  Stats: 15 rows
  Schedule: 120 games
  Standings: 8 teams

Bootstrap data keys: dict_keys(['firebaseUrl', 'firebaseToken', 'firebaseApiKey', 'current_league_id', 'current_season_id', 'leagues', 'seasons', 'conferences', 'conferencesAll', 'divisions', 'divisionsAll', 'first_season_year', 'regularSeasons', 'playoffSeasons', 'teams', 'teamsNoAll', 'months', 'monthsAll', 'positions', 'goalies', 'rosterstatus', 'standingsFooter', 'rosterFooter', 'playerStatsFooter', 'showExpandedGoaliesOption', 'showRosterStatus', 'quickViews', 'dailySchedRefreshToggle', 'dailySchedChangeoverHour', 'playerNoPicLogoOverride', 'svfConfig', 'svfLanguages', 'svfLang', 'player_shot_heat_map'])

In [12]:
bs_data = {}
for league in ['ohl', 'whl', 'qmjhl', 'ahl', 'pwhl']:
    scraper = HockeyScraper(league)
    bs_data[league] = scraper.bootstrap_data
    
bs_data

{'ohl': {'firebaseUrl': 'leaguestat-b9523.firebaseio.com',
  'firebaseToken': 'uwM69pPkdUhb0UuVAxM8IcA6pBAzATAxOc8979oJ',
  'firebaseApiKey': 'AIzaSyBVn0Gr6zIFtba-hQy3StkifD8bb7Hi68A',
  'current_league_id': '1',
  'current_season_id': '83',
  'leagues': [{'id': '2',
    'name': 'Canadian Hockey League',
    'short_name': 'CHL',
    'code': 'chl',
    'logo_image': ''},
   {'id': '3',
    'name': 'OHL All Star Game',
    'short_name': 'All Star',
    'code': 'allstar',
    'logo_image': ''},
   {'id': '1',
    'name': 'Ontario Hockey League',
    'short_name': 'OHL',
    'code': 'ohl',
    'logo_image': 'https://lscluster.hockeytech.com/download.php?client_code=ohl&file_path=img/logos/league-logo-1.jpg'},
   {'id': '4',
    'name': 'Tournaments',
    'short_name': 'tourney',
    'code': 'tourney',
    'logo_image': ''}],
  'seasons': [{'id': '84',
    'name': '2025-26 OHL Top Prospects',
    'default_sort': '',
    'start_date': '2026-01-10',
    'hide_in_standings': False},
   {'id': '83',
    'name': '2025-26 Regular Season',
    'default_sort': '',
    'start_date': '2025-09-16',
    'hide_in_standings': False},
   {'id': '82',
    'name': '2025 Pre-Season',
    'default_sort': '',
    'start_date': '2025-08-13',
    'hide_in_standings': False},
   {'id': '81',
    'name': '2025 Playoffs',
    'default_sort': '',
    'start_date': '2025-03-26',
    'hide_in_standings': False},
   {'id': '79',
    'name': '2024-25 Regular Season',
    'default_sort': '',
    'start_date': '2024-09-23',
    'hide_in_standings': False},
   {'id': '78',
    'name': '2024 Pre-season',
    'default_sort': '',
    'start_date': '2024-08-15',
    'hide_in_standings': False},
   {'id': '77',
    'name': '2024 Playoffs',
    'default_sort': '',
    'start_date': '2024-03-26',
    'hide_in_standings': False},
   {'id': '76',
    'name': '2023-24 Regular Season',
    'default_sort': '',
    'start_date': '2023-09-26',
    'hide_in_standings': False},
   {'id': '75',
    'name': '2023 Pre-season',
    'default_sort': '',
    'start_date': '2023-08-15',
    'hide_in_standings': False},
   {'id': '74',
    'name': '2023 Playoffs',
    'default_sort': '',
    'start_date': '2023-03-29',
    'hide_in_standings': False},
   {'id': '73',
    'name': '2022-23 Regular Season',
    'default_sort': '',
    'start_date': '2022-09-27',
    'hide_in_standings': True},
   {'id': '72',
    'name': '2022 Pre-season',
    'default_sort': '',
    'start_date': '2022-08-15',
    'hide_in_standings': False},
   {'id': '71',
    'name': '2022 Playoffs',
    'default_sort': '',
    'start_date': '2022-04-19',
    'hide_in_standings': False},
   {'id': '70',
    'name': '2021-22 Regular Season',
    'default_sort': '',
    'start_date': '2021-10-04',
    'hide_in_standings': False},
   {'id': '69',
    'name': '2021 Pre-season',
    'default_sort': '',
    'start_date': '2021-08-18',
    'hide_in_standings': False},
   {'id': '68',
    'name': '2019-20 Regular Season',
    'default_sort': '',
    'start_date': '2019-09-17',
    'hide_in_standings': False},
   {'id': '67',
    'name': '2019 Pre-season',
    'default_sort': '',
    'start_date': '2019-08-01',
    'hide_in_standings': False},
   {'id': '66',
    'name': '2019 Playoffs',
    'default_sort': '',
    'start_date': '2019-03-19',
    'hide_in_standings': False},
   {'id': '63',
    'name': '2018-19 Regular Season',
    'default_sort': '',
    'start_date': '2018-09-17',
    'hide_in_standings': False},
   {'id': '62',
    'name': '2018 Pre-season',
    'default_sort': '',
    'start_date': '2018-08-01',
    'hide_in_standings': False},
   {'id': '61',
    'name': '2018 Playoffs',
    'default_sort': '',
    'start_date': '2018-03-21',
    'hide_in_standings': False},
   {'id': '60',
    'name': '2017-18 Regular Season',
    'default_sort': '',
    'start_date': '2017-09-18',
    'hide_in_standings': False},
   {'id': '59',
    'name': '2017 Pre-season',
    'default_sort': '',
    'start_date': '2017-08-16',
    'hide_in_standings': False},
   {'id': '58',
    'name': '2017 Playoffs',
    'default_sort': '',
    'start_date': '2017-03-21',
    'hide_in_standings': False},
   {'id': '56',
    'name': '2016-17 Regular Season',
    'default_sort': '',
    'start_date': '2016-09-19',
    'hide_in_standings': False},
   {'id': '57',
    'name': '2016 Pre-season',
    'default_sort': '',
    'start_date': '2016-08-15',
    'hide_in_standings': False},
   {'id': '55',
    'name': '2016 Playoffs',
    'default_sort': '',
    'start_date': '2016-03-21',
    'hide_in_standings': False},
   {'id': '54',
    'name': '2015-16 Regular Season',
    'default_sort': '',
    'start_date': '2015-09-21',
    'hide_in_standings': False},
   {'id': '53',
    'name': '2015 Pre-season',
    'default_sort': '',
    'start_date': '2015-07-15',
    'hide_in_standings': False},
   {'id': '52',
    'name': '2015 Playoffs',
    'default_sort': '',
    'start_date': '2015-03-23',
    'hide_in_standings': False},
   {'id': '51',
    'name': '2014-15 Regular Season',
    'default_sort': '',
    'start_date': '2014-08-17',
    'hide_in_standings': False},
   {'id': '50',
    'name': '2014 Playoffs',
    'default_sort': '',
    'start_date': '2014-03-19',
    'hide_in_standings': False},
   {'id': '49',
    'name': '2013-14 Regular Season',
    'default_sort': '',
    'start_date': '2013-08-15',
    'hide_in_standings': False},
   {'id': '48',
    'name': '2013 Playoffs',
    'default_sort': '',
    'start_date': '2013-03-19',
    'hide_in_standings': False},
   {'id': '46',
    'name': '2012-13 Regular Season',
    'default_sort': '',
    'start_date': '2012-09-19',
    'hide_in_standings': False},
   {'id': '45',
    'name': '2012 Playoffs',
    'default_sort': '',
    'start_date': '2012-03-20',
    'hide_in_standings': False},
   {'id': '44',
    'name': '2011-12 Regular Season',
    'default_sort': '',
    'start_date': '2011-08-01',
    'hide_in_standings': False},
   {'id': '43',
    'name': '2011 Playoffs',
    'default_sort': '',
    'start_date': '2011-03-21',
    'hide_in_standings': False},
   {'id': '42',
    'name': '2010-11 Regular Season',
    'default_sort': '',
    'start_date': '2010-09-01',
    'hide_in_standings': False},
   {'id': '41',
    'name': '2010 Playoffs',
    'default_sort': '',
    'start_date': '2010-03-16',
    'hide_in_standings': False},
   {'id': '40',
    'name': '2009-10 All-Star Classic',
    'default_sort': '',
    'start_date': '2010-01-29',
    'hide_in_standings': False},
   {'id': '38',
    'name': '2009-10 Regular Season',
    'default_sort': '',
    'start_date': '2009-09-06',
    'hide_in_standings': False},
   {'id': '37',
    'name': '2009 Playoffs',
    'default_sort': '',
    'start_date': '2009-03-17',
    'hide_in_standings': False},
   {'id': '36',
    'name': '2008-09 All-Star Classic',
    'default_sort': '',
    'start_date': '2009-02-03',
    'hide_in_standings': False},
   {'id': '35',
    'name': '2008-09 Regular Season',
    'default_sort': '',
    'start_date': '2008-09-17',
    'hide_in_standings': False},
   {'id': '34',
    'name': '2008 Playoffs',
    'default_sort': '',
    'start_date': '2008-03-19',
    'hide_in_standings': False},
   {'id': '33',
    'name': '2007-08 All-Star Classic',
    'default_sort': '',
    'start_date': '2008-02-04',
    'hide_in_standings': False},
   {'id': '32',
    'name': '2007-08 Regular Season',
    'default_sort': '',
    'start_date': '2007-09-07',
    'hide_in_standings': False},
   {'id': '31',
    'name': '2007 Playoffs',
    'default_sort': '',
    'start_date': '2007-03-22',
    'hide_in_standings': False},
   {'id': '30',
    'name': '2006-07 All-Star Classic',
    'default_sort': '',
    'start_date': '2007-01-28',
    'hide_in_standings': False},
   {'id': '29',
    'name': '2006-07 Regular Season',
    'default_sort': '',
    'start_date': '2006-09-20',
    'hide_in_standings': False},
   {'id': '28',
    'name': '2006 Playoffs',
    'default_sort': '',
    'start_date': '2006-03-23',
    'hide_in_standings': False},
   {'id': '27',
    'name': '2005-06 All Star Classic',
    'default_sort': '',
    'start_date': '2006-02-01',
    'hide_in_standings': False},
   {'id': '26',
    'name': '2005-06 Regular Season',
    'default_sort': '',
    'start_date': '2005-09-05',
    'hide_in_standings': False},
   {'id': '25',
    'name': '2005 Playoffs',
    'default_sort': '',
    'start_date': '2005-03-24',
    'hide_in_standings': False},
   {'id': '24',
    'name': '2004-05 Regular Season',
    'default_sort': '',
    'start_date': '2004-09-06',
    'hide_in_standings': False},
   {'id': '23',
    'name': '2004 Playoffs',
    'default_sort': '',
    'start_date': '2004-03-17',
    'hide_in_standings': False},
   {'id': '21',
    'name': '2003-04 Regular Season',
    'default_sort': '',
    'start_date': '2003-09-17',
    'hide_in_standings': False},
   {'id': '20',
    'name': '2003 Playoffs',
    'default_sort': '',
    'start_date': '2003-03-20',
    'hide_in_standings': False},
   {'id': '17',
    'name': '2002-03 Regular Season',
    'default_sort': '',
    'start_date': '2002-09-18',
    'hide_in_standings': False},
   {'id': '15',
    'name': '2002 Playoffs',
    'default_sort': '',
    'start_date': '2002-03-19',
    'hide_in_standings': False},
   {'id': '14',
    'name': '2001-02 Regular Season',
    'default_sort': '',
    'start_date': '2001-09-13',
    'hide_in_standings': False},
   {'id': '12',
    'name': '2001 Playoffs',
    'default_sort': '',
    'start_date': '2001-03-24',
    'hide_in_standings': False},
   {'id': '11',
    'name': '2000-01 Regular Season',
    'default_sort': '',
    'start_date': '2000-09-21',
    'hide_in_standings': False},
   {'id': '10',
    'name': '2000 Playoffs',
    'default_sort': '',
    'start_date': '2000-03-25',
    'hide_in_standings': False},
   {'id': '9',
    'name': '1999-2000 Regular Season',
    'default_sort': '',
    'start_date': '1999-09-22',
    'hide_in_standings': False},
   {'id': '7',
    'name': '1999 Playoffs',
    'default_sort': '',
    'start_date': '1999-03-20',
    'hide_in_standings': False},
   {'id': '6',
    'name': '1998-99 Regular Season',
    'default_sort': '',
    'start_date': '1998-09-24',
    'hide_in_standings': False},
   {'id': '5',
    'name': '1998 Playoffs',
    'default_sort': '',
    'start_date': '1998-03-14',
    'hide_in_standings': False},
   {'id': '4',
    'name': '1997-98 Regular Season',
    'default_sort': '',
    'start_date': '1997-09-17',
    'hide_in_standings': False}],
  'conferences': [{'conference_id': '1',
    'conference_name': 'Eastern Conference'},
   {'conference_id': '2', 'conference_name': 'Western Conference'}],
  'conferencesAll': [{'conference_id': -1,
    'conference_name': 'All Conferences'},
   {'conference_id': '1', 'conference_name': 'Eastern Conference'},
   {'conference_id': '2', 'conference_name': 'Western Conference'}],
  'divisions': [{'id': '1', 'name': 'East Division', 'conference_id': '1'},
   {'id': '2', 'name': 'Central Division', 'conference_id': '1'},
   {'id': '4', 'name': 'Midwest Division', 'conference_id': '2'},
   {'id': '3', 'name': 'West Division', 'conference_id': '2'}],
  'divisionsAll': [{'id': -1, 'name': 'All Divisions', 'conference_id': None},
   {'id': '1', 'name': 'East Division', 'conference_id': '1'},
   {'id': '2', 'name': 'Central Division', 'conference_id': '1'},
   {'id': '4', 'name': 'Midwest Division', 'conference_id': '2'},
   {'id': '3', 'name': 'West Division', 'conference_id': '2'}],
  'first_season_year': '1997',
  'regularSeasons': [{'id': '83', 'name': '2025-26 Regular Season'},
   {'id': '79', 'name': '2024-25 Regular Season'},
   {'id': '76', 'name': '2023-24 Regular Season'},
   {'id': '73', 'name': '2022-23 Regular Season'},
   {'id': '70', 'name': '2021-22 Regular Season'},
   {'id': '68', 'name': '2019-20 Regular Season'},
   {'id': '63', 'name': '2018-19 Regular Season'},
   {'id': '60', 'name': '2017-18 Regular Season'},
   {'id': '56', 'name': '2016-17 Regular Season'},
   {'id': '54', 'name': '2015-16 Regular Season'},
   {'id': '51', 'name': '2014-15 Regular Season'},
   {'id': '49', 'name': '2013-14 Regular Season'},
   {'id': '46', 'name': '2012-13 Regular Season'},
   {'id': '44', 'name': '2011-12 Regular Season'},
   {'id': '42', 'name': '2010-11 Regular Season'},
   {'id': '38', 'name': '2009-10 Regular Season'},
   {'id': '35', 'name': '2008-09 Regular Season'},
   {'id': '32', 'name': '2007-08 Regular Season'},
   {'id': '29', 'name': '2006-07 Regular Season'},
   {'id': '26', 'name': '2005-06 Regular Season'},
   {'id': '24', 'name': '2004-05 Regular Season'},
   {'id': '21', 'name': '2003-04 Regular Season'},
   {'id': '17', 'name': '2002-03 Regular Season'},
   {'id': '14', 'name': '2001-02 Regular Season'},
   {'id': '11', 'name': '2000-01 Regular Season'},
   {'id': '9', 'name': '1999-2000 Regular Season'},
   {'id': '6', 'name': '1998-99 Regular Season'},
   {'id': '4', 'name': '1997-98 Regular Season'}],
  'playoffSeasons': [{'id': '81', 'name': '2025 Playoffs'},
   {'id': '77', 'name': '2024 Playoffs'},
   {'id': '74', 'name': '2023 Playoffs'},
   {'id': '71', 'name': '2022 Playoffs'},
   {'id': '66', 'name': '2019 Playoffs'},
   {'id': '61', 'name': '2018 Playoffs'},
   {'id': '58', 'name': '2017 Playoffs'},
   {'id': '55', 'name': '2016 Playoffs'},
   {'id': '52', 'name': '2015 Playoffs'},
   {'id': '50', 'name': '2014 Playoffs'},
   {'id': '48', 'name': '2013 Playoffs'},
   {'id': '45', 'name': '2012 Playoffs'},
   {'id': '43', 'name': '2011 Playoffs'},
   {'id': '41', 'name': '2010 Playoffs'},
   {'id': '37', 'name': '2009 Playoffs'},
   {'id': '34', 'name': '2008 Playoffs'},
   {'id': '31', 'name': '2007 Playoffs'},
   {'id': '28', 'name': '2006 Playoffs'},
   {'id': '25', 'name': '2005 Playoffs'},
   {'id': '23', 'name': '2004 Playoffs'},
   {'id': '20', 'name': '2003 Playoffs'},
   {'id': '15', 'name': '2002 Playoffs'},
   {'id': '12', 'name': '2001 Playoffs'},
   {'id': '10', 'name': '2000 Playoffs'},
   {'id': '7', 'name': '1999 Playoffs'},
   {'id': '5', 'name': '1998 Playoffs'}],
  'teams': [{'id': -1, 'name': 'All Teams'},
   {'id': '7',
    'name': 'Barrie Colts',
    'nickname': 'Colts',
    'team_code': 'BAR',
    'division_id': '2',
    'logo': 'https://assets.leaguestat.com/ohl/logos/50x50/7.png'},
   {'id': '18',
    'name': 'Brampton Steelheads',
    'nickname': 'Steelheads',
    'team_code': 'BRAM',
    'division_id': '2',
    'logo': 'https://assets.leaguestat.com/ohl/logos/50x50/18.png'},
   {'id': '1',
    'name': 'Brantford Bulldogs',
    'nickname': 'Bulldogs',
    'team_code': 'BFD',
    'division_id': '1',
    'logo': 'https://assets.leaguestat.com/ohl/logos/1.png'},
   {'id': '8',
    'name': 'Erie Otters',
    'nickname': 'Otters',
    'team_code': 'ER',
    'division_id': '4',
    'logo': 'https://assets.leaguestat.com/ohl/logos/8.png'},
   {'id': '13',
    'name': 'Flint Firebirds',
    'nickname': 'Firebirds',
    'team_code': 'FLNT',
    'division_id': '3',
    'logo': 'https://assets.leaguestat.com/ohl/logos/13.png'},
   {'id': '9',
    'name': 'Guelph Storm',
    'nickname': 'Storm',
    'team_code': 'GUE',
    'division_id': '4',
    'logo': 'https://assets.leaguestat.com/ohl/logos/9.png'},
   {'id': '2',
    'name': 'Kingston Frontenacs',
    'nickname': 'Frontenacs',
    'team_code': 'KGN',
    'division_id': '1',
    'logo': 'https://assets.leaguestat.com/ohl/logos/50x50/2.png'},
   {'id': '10',
    'name': 'Kitchener Rangers',
    'nickname': 'Rangers',
    'team_code': 'KIT',
    'division_id': '4',
    'logo': 'https://assets.leaguestat.com/ohl/logos/10.png'},
   {'id': '14',
    'name': 'London Knights',
    'nickname': 'Knights',
    'team_code': 'LDN',
    'division_id': '4',
    'logo': 'https://assets.leaguestat.com/ohl/logos/14.png'},
   {'id': '20',
    'name': 'Niagara IceDogs',
    'nickname': 'IceDogs',
    'team_code': 'NIAG',
    'division_id': '2',
    'logo': 'https://assets.leaguestat.com/ohl/logos/20.png'},
   {'id': '19',
    'name': 'North Bay Battalion',
    'nickname': 'Battalion',
    'team_code': 'NB',
    'division_id': '2',
    'logo': 'https://assets.leaguestat.com/ohl/logos/19.png'},
   {'id': '4',
    'name': 'Oshawa Generals',
    'nickname': 'Generals',
    'team_code': 'OSH',
    'division_id': '1',
    'logo': 'https://assets.leaguestat.com/ohl/logos/4.png'},
   {'id': '5',
    'name': "Ottawa 67's",
    'nickname': "67's",
    'team_code': 'OTT',
    'division_id': '1',
    'logo': 'https://assets.leaguestat.com/ohl/logos/5.png'},
   {'id': '11',
    'name': 'Owen Sound Attack',
    'nickname': 'Attack',
    'team_code': 'OS',
    'division_id': '4',
    'logo': 'https://assets.leaguestat.com/ohl/logos/11.png'},
   {'id': '6',
    'name': 'Peterborough Petes',
    'nickname': 'Petes',
    'team_code': 'PBO',
    'division_id': '1',
    'logo': 'https://assets.leaguestat.com/ohl/logos/6.png'},
   {'id': '34',
    'name': 'Saginaw Spirit',
    'nickname': 'Spirit',
    'team_code': 'SAG',
    'division_id': '3',
    'logo': 'https://assets.leaguestat.com/ohl/logos/34.png'},
   {'id': '15',
    'name': 'Sarnia Sting',
    'nickname': 'Sting',
    'team_code': 'SAR',
    'division_id': '3',
    'logo': 'https://assets.leaguestat.com/ohl/logos/15.png'},
   {'id': '16',
    'name': 'Soo Greyhounds',
    'nickname': 'Greyhounds',
    'team_code': 'SOO',
    'division_id': '3',
    'logo': 'https://assets.leaguestat.com/ohl/logos/16.png'},
   {'id': '12',
    'name': 'Sudbury Wolves',
    'nickname': 'Wolves',
    'team_code': 'SBY',
    'division_id': '2',
    'logo': 'https://assets.leaguestat.com/ohl/logos/50x50/12.png'},
   {'id': '17',
    'name': 'Windsor Spitfires',
    'nickname': 'Spitfires',
    'team_code': 'WSR',
    'division_id': '3',
    'logo': 'https://assets.leaguestat.com/ohl/logos/17.png'}],
  'teamsNoAll': [{'id': '7',
    'name': 'Barrie Colts',
    'nickname': 'Colts',
    'team_code': 'BAR',
    'division_id': '2',
    'logo': 'https://assets.leaguestat.com/ohl/logos/50x50/7.png'},
   {'id': '18',
    'name': 'Brampton Steelheads',
    'nickname': 'Steelheads',
    'team_code': 'BRAM',
    'division_id': '2',
    'logo': 'https://assets.leaguestat.com/ohl/logos/50x50/18.png'},
   {'id': '1',
    'name': 'Brantford Bulldogs',
    'nickname': 'Bulldogs',
    'team_code': 'BFD',
    'division_id': '1',
    'logo': 'https://assets.leaguestat.com/ohl/logos/1.png'},
   {'id': '8',
    'name': 'Erie Otters',
    'nickname': 'Otters',
    'team_code': 'ER',
    'division_id': '4',
    'logo': 'https://assets.leaguestat.com/ohl/logos/8.png'},
   {'id': '13',
    'name': 'Flint Firebirds',
    'nickname': 'Firebirds',
    'team_code': 'FLNT',
    'division_id': '3',
    'logo': 'https://assets.leaguestat.com/ohl/logos/13.png'},
   {'id': '9',
    'name': 'Guelph Storm',
    'nickname': 'Storm',
    'team_code': 'GUE',
    'division_id': '4',
    'logo': 'https://assets.leaguestat.com/ohl/logos/9.png'},
   {'id': '2',
    'name': 'Kingston Frontenacs',
    'nickname': 'Frontenacs',
    'team_code': 'KGN',
    'division_id': '1',
    'logo': 'https://assets.leaguestat.com/ohl/logos/50x50/2.png'},
   {'id': '10',
    'name': 'Kitchener Rangers',
    'nickname': 'Rangers',
    'team_code': 'KIT',
    'division_id': '4',
    'logo': 'https://assets.leaguestat.com/ohl/logos/10.png'},
   {'id': '14',
    'name': 'London Knights',
    'nickname': 'Knights',
    'team_code': 'LDN',
    'division_id': '4',
    'logo': 'https://assets.leaguestat.com/ohl/logos/14.png'},
   {'id': '20',
    'name': 'Niagara IceDogs',
    'nickname': 'IceDogs',
    'team_code': 'NIAG',
    'division_id': '2',
    'logo': 'https://assets.leaguestat.com/ohl/logos/20.png'},
   {'id': '19',
    'name': 'North Bay Battalion',
    'nickname': 'Battalion',
    'team_code': 'NB',
    'division_id': '2',
    'logo': 'https://assets.leaguestat.com/ohl/logos/19.png'},
   {'id': '4',

In [13]:
import json

# save to a file
bs_data_json = json.dumps(bs_data, indent=4)
with open('bootstrap_data.json', 'w') as f:
    f.write(bs_data_json)

In [14]:
pd.json_normalize(scraper.bootstrap_data["seasons"])

  id                    name default_sort  start_date  hide_in_standings
0  8  2025-26 Regular Season               2025-11-21              False
1  7       2025-26 Preseason               2025-06-01               True
2  6           2025 Playoffs               2025-05-06              False
3  5  2024-25 Regular Season               2024-11-25              False
4  4       2024-25 Preseason               2024-11-01              False
5  3           2024 Playoffs               2024-05-06               True
6  1     2024 Regular Season               2024-01-01              False
7  2          2024 Preseason               2023-11-01              False

In [15]:
# Manually fetch bootstrap with specific parameters
ahl = HockeyScraper('ahl')

# Get bootstrap for a specific season
bootstrap = ahl.bootstrap(season='90', page_name='scorebar')

print(f"Manual bootstrap fetch:")
print(f"  Season ID: {bootstrap['current_season_id']}")
print(f"  Teams: {len(bootstrap['teams'])}")

# Note: NHL doesn't support bootstrap
try:
    nhl = HockeyScraper('nhl')
    nhl_bootstrap = nhl.bootstrap()
except NotImplementedError as e:
    print(f"\nNHL doesn't support bootstrap: {e}")

Manual bootstrap fetch:
  Season ID: 90
  Teams: 33

NHL doesn't support bootstrap: Bootstrap endpoint not available for NHL.

### Manual Bootstrap Method

You can also manually fetch bootstrap with custom parameters:

In [16]:
# Bootstrap properties provide quick access to common data
pwhl = HockeyScraper('pwhl')

print("Convenience properties:")
print(f"  League ID: {pwhl.current_league_id}")
print(f"  Season ID: {pwhl.current_season_id}")
print(f"  Number of teams: {len(pwhl.teams)}")

# Full bootstrap data is also available
print(f"\nFull bootstrap has {len(pwhl.bootstrap_data)} keys:")
print(f"  Available keys: {list(pwhl.bootstrap_data.keys())[:10]}...")

# Access specific data from bootstrap
divisions = pwhl.bootstrap_data.get('divisions', [])
seasons = pwhl.bootstrap_data.get('regularSeasons', [])
print(f"\n  Divisions: {len(divisions)}")
print(f"  Regular seasons: {len(seasons)}")

Convenience properties:
  League ID: 1
  Season ID: 8
  Number of teams: 8

Full bootstrap has 34 keys:
  Available keys: ['firebaseUrl', 'firebaseToken', 'firebaseApiKey', 'current_league_id', 'current_season_id', 'leagues', 'seasons', 'conferences', 'conferencesAll', 'divisions']...

  Divisions: 1
  Regular seasons: 3

### Bootstrap Properties

The scraper provides convenient properties for accessing bootstrap data:

## Understanding the Output

All methods return **pandas DataFrames** - this makes it easy to:
- Filter and sort data
- Export to CSV, Excel, or JSON
- Perform analysis
- Create visualizations

In [17]:
# Example: Filter and sort
stats = scrape('qmjhl', 'stats', season=90, position='skaters', limit=50)

# Get players with more than 20 goals
goal_scorers = stats[stats['G'] > 20].sort_values('G', ascending=False)

print(f"Found {len(goal_scorers)} players with 20+ goals")
display(goal_scorers[['playerName', 'teamCode', 'GP','G', 'A', 'PTS']].head(10))

Found 46 players with 20+ goals

                  playerName teamCode  GP   G   A  PTS
2          Boisclair, Maxime      Chi  70  70  60  130
0         Radulov, Alexander      Que  62  61  91  152
13  Picard-Hooper, Alexandre      BaC  70  57  43  100
5               Aubin, Brent      Que  72  57  60  117
20          Goulet, Stéphane      Mon  67  51  42   93
9               Roy, Mathieu      Bat  65  50  54  104
14          Labelle, Olivier      Bat  67  50  50  100
1          Lascek, Stanislav      Chi  64  47  88  135
10            Aubin, Mathieu      Lew  70  47  56  103
22        Beauregard, Thomas      Bat  69  46  42   88

In [18]:
stats.head()

,player_id,name,position,rookie,jerseyNumber,teamCode,GP,GWG,G,S,Sh%,A,PTS,PTS/GP,+/-,PIM,PIM/GP,PPG,PPA,SHG,SHA,SG,rank,lastName,firstName,playerName,teamId,teamLogo,season,league,seasonName,seasonStartYear,seasonEndYear,scraped_at
0,9261,"Radulov, Alexander",RW,0,22,Que,62,9,61,332,18.4,91,152,2.45,53,101,1.63,22,44,10,6,4,1,Radulov,Alexander,"Radulov, Alexander",9,https://assets.leaguestat.com/lhjmq/logos/9_90...,90,qmjhl,2005-06 | Regular Season,2005,2006,2026-03-07T02:20:56.412142+00:00
1,9734,"Lascek, Stanislav",RW,0,17,Chi,64,9,47,344,13.7,88,135,2.11,42,96,1.50,20,55,3,2,3,2,Lascek,Stanislav,"Lascek, Stanislav",10,https://assets.leaguestat.com/lhjmq/logos/10.png,90,qmjhl,2005-06 | Regular Season,2005,2006,2026-03-07T02:20:56.412142+00:00
2,10615,"Boisclair, Maxime",LW,0,97,Chi,70,12,70,321,21.8,60,130,1.86,39,97,1.39,43,24,3,1,0,3,Boisclair,Maxime,"Boisclair, Maxime",10,https://assets.leaguestat.com/lhjmq/logos/10.png,90,qmjhl,2005-06 | Regular Season,2005,2006,2026-03-07T02:20:56.412142+00:00
3,9732,"Latendresse, Olivier",C,0,44,VdO,70,6,41,359,11.4,84,125,1.79,5,83,1.19,16,47,4,2,2,4,Latendresse,Olivier,"Latendresse, Olivier",15,https://assets.leaguestat.com/lhjmq/logos/15.png,90,qmjhl,2005-06 | Regular Season,2005,2006,2026-03-07T02:20:56.412142+00:00
4,10288,"Desharnais, David",C,0,15,Chi,63,6,33,161,20.5,85,118,1.87,45,44,0.70,20,52,2,3,2,5,Desharnais,David,"Desharnais, David",10,https://assets.leaguestat.com/lhjmq/logos/10.png,90,qmjhl,2005-06 | Regular Season,2005,2006,2026-03-07T02:20:56.412142+00:00

## Next Steps

Now that you understand the basics, check out:

1. **02_nhl_data.ipynb** - Working with NHL data
2. **03_other_leagues.ipynb** - QMJHL, OHL, WHL, AHL examples
3. **04_advanced_features.ipynb** - Caching, rate limiting, transformations

## Summary

- Use `scrape(league, data_type, **kwargs)` for simple queries
- Use `HockeyScraper(league)` for object-oriented approach
- **NEW:** Bootstrap data (teams, seasons, divisions) auto-fetched for non-NHL leagues
- Access bootstrap via `scraper.teams`, `scraper.current_season_id`, etc.
- All methods return pandas DataFrames
- Supported leagues: NHL, PWHL, QMJHL, OHL, WHL, AHL
- Data types: pbp, stats, schedule, roster, standings

## League-Specific Parameters

Each league and data type accepts specific parameters. Here are the most common ones:

### Player Stats
- `season`: Season ID (e.g., 90 for QMJHL 2024-25)
- `position`: 'skaters' or 'goalies'
- `team`: Team ID or 'all'
- `limit`: Number of results to return

### Schedule
- `season`: Season ID
- `team_id`: Team ID (-1 for all teams)
- `month`: Month filter (-1 for all months)

### Play-by-Play
- `game_id`: The game ID to scrape
- `nhlify`: Apply NHL-style transformations (default: True)

### Roster
- `team_id`: Team ID
- `season`: Season ID

### Standings
- `season`: Season ID

## Error Handling

ScraperNHL provides helpful error messages:

In [19]:
try:
    # This will fail - invalid data type
    data = scrape('qmjhl', 'invalid_type', season=90)
except ValueError as e:
    print(f"Error: {e}")

Error: Invalid data_type: invalid_type

## Next Steps

Now that you understand the basics, check out:

1. **02_nhl_data.ipynb** - Working with NHL data
2. **03_other_leagues.ipynb** - QMJHL, OHL, WHL, AHL examples
3. **04_advanced_features.ipynb** - Caching, rate limiting, transformations

## Summary

- Use `scrape(league, data_type, **kwargs)` for simple queries
- Use `HockeyScraper(league)` for object-oriented approach
- All methods return pandas DataFrames
- Supported leagues: NHL, QMJHL, OHL, WHL, AHL
- Data types: pbp, stats, schedule, roster, standings