# Getting Started with ScraperNHL

Welcome to ScraperNHL! This notebook will teach you the basics of using the new unified API.

## What is ScraperNHL?

ScraperNHL is a Python package for scraping hockey data from multiple leagues:
- NHL (National Hockey League)
- QMJHL (Quebec Major Junior Hockey League)
- OHL (Ontario Hockey League)
- WHL (Western Hockey League)
- AHL (American Hockey League)

## New in Version 3.0

The package has been completely redesigned with:
- **Unified API**: One consistent interface for all leagues
- **Simpler Design**: Easy functional API or flexible OOP API
- **Better Performance**: Built-in caching and rate limiting
- **Clean Data**: Automatic normalization and transformations

In [20]:
%load_ext autoreload
%autoreload 2

The autoreload extension is already loaded. To reload it, use:
  %reload_ext autoreload

## Installation

Make sure you have scrapernhl installed:

```bash
pip install scrapernhl
```

Or from source:

```bash
pip install -e .
```

## Method 1: Functional API (Recommended for Beginners)

The simplest way to use ScraperNHL is with the `scrape()` function:

In [183]:
from scrapernhl import scrape
import pandas as pd

pd.set_option('display.max_columns', None)

# Get player stats from the QMJHL
stats = scrape('qmjhl', 'stats', season=90, position='skaters', limit=10)

print(f"Got {len(stats)} players")
print("\nTop 10 players:")
display(stats[['name', 'team_code', 'goals', 'assists', 'points']].head(10))

Got 10 players

Top 10 players:

KeyError: "['team_code', 'goals', 'assists', 'points'] not in index"

In [184]:
stats

,player_id,name,position,rookie,jerseyNumber,teamCode,GP,GWG,G,S,Sh%,A,PTS,PTS/GP,+/-,PIM,PIM/GP,PPG,PPA,SHG,SHA,SG,rank,lastName,firstName,playerName,teamId,teamLogo,season,league,seasonName,seasonStartYear,seasonEndYear
0,9261,"Radulov, Alexander",RW,0,22,Que,62,9,61,332,18.4,91,152,2.45,53,101,1.63,22,44,10,6,4,1,Radulov,Alexander,"Radulov, Alexander",9,https://assets.leaguestat.com/lhjmq/logos/9_90...,90,qmjhl,2005-06 | Regular Season,2005,2006
1,9734,"Lascek, Stanislav",RW,0,17,Chi,64,9,47,344,13.7,88,135,2.11,42,96,1.50,20,55,3,2,3,2,Lascek,Stanislav,"Lascek, Stanislav",10,https://assets.leaguestat.com/lhjmq/logos/10.png,90,qmjhl,2005-06 | Regular Season,2005,2006
2,10615,"Boisclair, Maxime",LW,0,97,Chi,70,12,70,321,21.8,60,130,1.86,39,97,1.39,43,24,3,1,0,3,Boisclair,Maxime,"Boisclair, Maxime",10,https://assets.leaguestat.com/lhjmq/logos/10.png,90,qmjhl,2005-06 | Regular Season,2005,2006
3,9732,"Latendresse, Olivier",C,0,44,VdO,70,6,41,359,11.4,84,125,1.79,5,83,1.19,16,47,4,2,2,4,Latendresse,Olivier,"Latendresse, Olivier",15,https://assets.leaguestat.com/lhjmq/logos/15.png,90,qmjhl,2005-06 | Regular Season,2005,2006
4,10288,"Desharnais, David",C,0,15,Chi,63,6,33,161,20.5,85,118,1.87,45,44,0.70,20,52,2,3,2,5,Desharnais,David,"Desharnais, David",10,https://assets.leaguestat.com/lhjmq/logos/10.png,90,qmjhl,2005-06 | Regular Season,2005,2006
5,10779,"Aubin, Brent",C,0,18,Que,72,10,57,323,17.6,60,117,1.63,17,92,1.28,26,41,1,0,1,6,Aubin,Brent,"Aubin, Brent",9,https://assets.leaguestat.com/lhjmq/logos/9_90...,90,qmjhl,2005-06 | Regular Season,2005,2006
6,10550,"Brassard, Derick",C,0,61,Dru,58,6,44,283,15.5,72,116,2.00,19,92,1.59,23,39,2,4,0,7,Brassard,Derick,"Brassard, Derick",14,https://assets.leaguestat.com/lhjmq/logos/50x5...,90,qmjhl,2005-06 | Regular Season,2005,2006
7,10562,"Bourret, Alex",LW,0,23,Sha,67,10,44,289,15.2,70,114,1.70,11,133,1.99,23,40,5,4,1,8,Bourret,Alex,"Bourret, Alex",13,https://assets.leaguestat.com/lhjmq/logos/13.png,90,qmjhl,2005-06 | Regular Season,2005,2006
8,10199,"Dupuis, Philippe",C,0,9,Mon,56,5,32,277,11.6,76,108,1.93,42,52,0.93,13,53,2,1,1,9,Dupuis,Philippe,"Dupuis, Philippe",1,https://assets.leaguestat.com/lhjmq/logos/1.png,90,qmjhl,2005-06 | Regular Season,2005,2006
9,9180,"Roy, Mathieu",LW,0,15,Bat,65,4,50,348,14.4,54,104,1.60,22,101,1.55,28,35,3,0,2,10,Roy,Mathieu,"Roy, Mathieu",2,https://assets.leaguestat.com/lhjmq/logos/2.png,90,qmjhl,2005-06 | Regular Season,2005,2006

### Available Data Types

You can request different types of data:

1. **'pbp'** - Play-by-play data for a specific game
2. **'stats'** - Player statistics for skaters or goalies
3. **'schedule'** - Schedule for a team or entire league
4. **'roster'** - Team roster with player details
5. **'standings'** - Current league standings

In [87]:
# Get schedule for a team
schedule = scrape('ohl', 'schedule', season=83, team_id=16)

print(f"Games in schedule: {len(schedule)}")
display(schedule[['date', 'homeTeam', 'awayTeam']].head())

Games in schedule: 683

        date             homeTeam             awayTeam
0 2025-09-18  North Bay Battalion      Oshawa Generals
1 2025-09-18   Peterborough Petes  Brampton Steelheads
2 2025-09-19  Brampton Steelheads      Niagara IceDogs
3 2025-09-19    Kitchener Rangers   Brantford Bulldogs
4 2025-09-19       London Knights    Owen Sound Attack

In [86]:
schedule

,homeId,awayId,gameId_,gameId,date_,homeScore,awayScore,gameStatus,homeCity,awayCity,venue,homeTeam,awayTeam,homeCode,awayCode,homeDivision,awayDivision,homeLogo,awayLogo,season,league,seasonName,seasonStartDate,seasonStartYear,seasonEndYear,dayOfWeek,monthText,monthNum,day,year,date
0,19,4,28150,28150,"Thu, Sep 18",4,2,Final,North Bay,Oshawa,Boart Longyear Memorial Gardens,North Bay Battalion,Oshawa Generals,NB,OSH,2,1,https://assets.leaguestat.com/ohl/logos/19.png,https://assets.leaguestat.com/ohl/logos/4.png,83,ohl,2025-26 Regular Season,2025-09-16,2025,2026,Thu,Sep,09,18,2025,2025-09-18
1,6,18,28151,28151,"Thu, Sep 18",6,3,Final,Peterborough,Brampton,Peterborough Memorial Centre,Peterborough Petes,Brampton Steelheads,PBO,BRAM,1,2,https://assets.leaguestat.com/ohl/logos/6.png,https://assets.leaguestat.com/ohl/logos/50x50/...,83,ohl,2025-26 Regular Season,2025-09-16,2025,2026,Thu,Sep,09,18,2025,2025-09-18
2,18,20,28152,28152,"Fri, Sep 19",4,1,Final,Brampton,Niagara,CAA Centre,Brampton Steelheads,Niagara IceDogs,BRAM,NIAG,2,2,https://assets.leaguestat.com/ohl/logos/50x50/...,https://assets.leaguestat.com/ohl/logos/20.png,83,ohl,2025-26 Regular Season,2025-09-16,2025,2026,Fri,Sep,09,19,2025,2025-09-19
3,10,1,28155,28155,"Fri, Sep 19",4,3,Final OT,Kitchener,Brantford,Kitchener Memorial Auditorium,Kitchener Rangers,Brantford Bulldogs,KIT,BFD,4,1,https://assets.leaguestat.com/ohl/logos/10.png,https://assets.leaguestat.com/ohl/logos/1.png,83,ohl,2025-26 Regular Season,2025-09-16,2025,2026,Fri,Sep,09,19,2025,2025-09-19
4,14,11,28156,28156,"Fri, Sep 19",2,3,Final OT,London,Owen Sound,Canada Life Place,London Knights,Owen Sound Attack,LDN,OS,4,4,https://assets.leaguestat.com/ohl/logos/14.png,https://assets.leaguestat.com/ohl/logos/11.png,83,ohl,2025-26 Regular Season,2025-09-16,2025,2026,Fri,Sep,09,19,2025,2025-09-19
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
678,18,1,NaN,28827,"Sun, Mar 22",-,-,2:00 pm,Brampton,Brantford,CAA Centre,Brampton Steelheads,Brantford Bulldogs,BRAM,BFD,2,1,https://assets.leaguestat.com/ohl/logos/50x50/...,https://assets.leaguestat.com/ohl/logos/1.png,83,ohl,2025-26 Regular Season,2025-09-16,2025,2026,Sun,Mar,03,22,2026,2026-03-22
679,19,12,NaN,28829,"Sun, Mar 22",-,-,2:00 pm,North Bay,Sudbury,Boart Longyear Memorial Gardens,North Bay Battalion,Sudbury Wolves,NB,SBY,2,2,https://assets.leaguestat.com/ohl/logos/19.png,https://assets.leaguestat.com/ohl/logos/50x50/...,83,ohl,2025-26 Regular Season,2025-09-16,2025,2026,Sun,Mar,03,22,2026,2026-03-22
680,20,8,NaN,28828,"Sun, Mar 22",-,-,2:00 pm,Niagara,Erie,Meridian Centre,Niagara IceDogs,Erie Otters,NIAG,ER,2,4,https://assets.leaguestat.com/ohl/logos/20.png,https://assets.leaguestat.com/ohl/logos/8.png,83,ohl,2025-26 Regular Season,2025-09-16,2025,2026,Sun,Mar,03,22,2026,2026-03-22
681,16,17,NaN,28831,"Sun, Mar 22",-,-,2:07 pm,Sault Ste. Marie,Windsor,GFL Memorial Gardens,Soo Greyhounds,Windsor Spitfires,SOO,WSR,3,3,https://assets.leaguestat.com/ohl/logos/16.png,https://assets.leaguestat.com/ohl/logos/17.png,83,ohl,2025-26 Regular Season,2025-09-16,2025,2026,Sun,Mar,03,22,2026,2026-03-22
682,4,6,NaN,28830,"Sun, Mar 22",-,-,6:05 pm,Oshawa,Peterborough,Tribute Communities Centre,Oshawa Generals,Peterborough Petes,OSH,PBO,1,1,https://assets.leaguestat.com/ohl/logos/4.png,https://assets.leaguestat.com/ohl/logos/6.png,83,ohl,2025-26 Regular Season,2025-09-16,2025,2026,Sun,Mar,03,22,2026,2026-03-22

In [122]:
# Get league standings
standings = scrape('whl', 'standings', season=289)

print("WHL Standings:")
display(standings[['team_code', 'wins', 'losses', 'points']].head())

289
{'BDN': {'id': '201', 'name': 'Brandon Wheat Kings', 'nickname': 'Wheat Kings', 'division_id': '1', 'logo': 'https://assets.leaguestat.com/whl/logos/50x50/201.png'}, 'CGY': {'id': '202', 'name': 'Calgary Hitmen', 'nickname': 'Hitmen', 'division_id': '3', 'logo': 'https://assets.leaguestat.com/whl/logos/202.png'}, 'EDM': {'id': '228', 'name': 'Edmonton Oil Kings', 'nickname': 'Oil Kings', 'division_id': '3', 'logo': 'https://assets.leaguestat.com/whl/logos/228.png'}, 'EVT': {'id': '226', 'name': 'Everett Silvertips', 'nickname': 'Silvertips', 'division_id': '6', 'logo': 'https://assets.leaguestat.com/whl/logos/226.png'}, 'KAM': {'id': '203', 'name': 'Kamloops Blazers', 'nickname': 'Blazers', 'division_id': '2', 'logo': 'https://assets.leaguestat.com/whl/logos/203.png'}, 'KEL': {'id': '204', 'name': 'Kelowna Rockets', 'nickname': 'Rockets', 'division_id': '2', 'logo': 'https://assets.leaguestat.com/whl/logos/50x50/204.png'}, 'LET': {'id': '205', 'name': 'Lethbridge Hurricanes', 'nickname': 'Hurricanes', 'division_id': '3', 'logo': 'https://assets.leaguestat.com/whl/logos/205.png'}, 'MH': {'id': '206', 'name': 'Medicine Hat Tigers', 'nickname': 'Tigers', 'division_id': '3', 'logo': 'https://assets.leaguestat.com/whl/logos/206.png'}, 'MJ': {'id': '207', 'name': 'Moose Jaw Warriors', 'nickname': 'Warriors', 'division_id': '1', 'logo': 'https://assets.leaguestat.com/whl/logos/207.png'}, 'PEN': {'id': '277', 'name': 'Penticton Vees', 'nickname': 'Vees', 'division_id': '2', 'logo': 'https://assets.leaguestat.com/whl/logos/50x50/277.png'}, 'POR': {'id': '208', 'name': 'Portland Winterhawks', 'nickname': 'Winterhawks', 'division_id': '6', 'logo': 'https://assets.leaguestat.com/whl/logos/50x50/208.png'}, 'PA': {'id': '209', 'name': 'Prince Albert Raiders', 'nickname': 'Raiders', 'division_id': '1', 'logo': 'https://assets.leaguestat.com/whl/logos/209.png'}, 'PG': {'id': '210', 'name': 'Prince George Cougars', 'nickname': 'Cougars', 'division_id': '2', 'logo': 'https://assets.leaguestat.com/whl/logos/210.png'}, 'RD': {'id': '211', 'name': 'Red Deer Rebels', 'nickname': 'Rebels', 'division_id': '3', 'logo': 'https://assets.leaguestat.com/whl/logos/211.png'}, 'REG': {'id': '212', 'name': 'Regina Pats', 'nickname': 'Pats', 'division_id': '1', 'logo': 'https://assets.leaguestat.com/whl/logos/212.png'}, 'SAS': {'id': '213', 'name': 'Saskatoon Blades', 'nickname': 'Blades', 'division_id': '1', 'logo': 'https://assets.leaguestat.com/whl/logos/50x50/213.png'}, 'SEA': {'id': '214', 'name': 'Seattle Thunderbirds', 'nickname': 'Thunderbirds', 'division_id': '6', 'logo': 'https://assets.leaguestat.com/whl/logos/214.png'}, 'SPO': {'id': '215', 'name': 'Spokane Chiefs', 'nickname': 'Chiefs', 'division_id': '6', 'logo': 'https://assets.leaguestat.com/whl/logos/215.png'}, 'SC': {'id': '216', 'name': 'Swift Current Broncos', 'nickname': 'Broncos', 'division_id': '1', 'logo': 'https://assets.leaguestat.com/whl/logos/216.png'}, 'TC': {'id': '217', 'name': 'Tri-City Americans', 'nickname': 'Americans', 'division_id': '6', 'logo': 'https://assets.leaguestat.com/whl/logos/217.png'}, 'VAN': {'id': '223', 'name': 'Vancouver Giants', 'nickname': 'Giants', 'division_id': '2', 'logo': 'https://assets.leaguestat.com/whl/logos/223.png'}, 'VIC': {'id': '227', 'name': 'Victoria Royals', 'nickname': 'Royals', 'division_id': '2', 'logo': 'https://assets.leaguestat.com/whl/logos/227.png'}, 'WEN': {'id': '222', 'name': 'Wenatchee Wild', 'nickname': 'Wild', 'division_id': '6', 'logo': 'https://assets.leaguestat.com/whl/logos/50x50/222.png'}}
{'289': {'name': '2025 - 26 Regular Season'}, '285': {'name': '2024 - 25 Regular Season'}, '281': {'name': '2023 - 24 Regular Season'}, '279': {'name': '2022 - 23 Regular Season'}, '275': {'name': '2021 - 22 Regular Season'}, '273': {'name': '2020 - 21 Regular Season'}, '270': {'name': '2019 - 20 Regular Season'}, '268': {'name': '19 Tie Break'}, '266': {'name': '2018 - 19 Regular Season'}, '262': {'name': '2017 - 18 Regular Season'}, '257': {'name': '2016 - 17 Regular Season'}, '255': {'name': '16 Tie Break'}, '251': {'name': '2015-16 Regular Season'}, '249': {'name': '2014-15 Regular Season'}, '245': {'name': '2013-14 Regular Season'}, '242': {'name': '2012-13 Regular Season'}, '238': {'name': '2011-12 Regular Season'}, '236': {'name': '2010-11 Regular Season'}, '234': {'name': '2009-10 Regular Season'}, '231': {'name': '2008-09 Regular Season'}, '229': {'name': '2007-08 Regular Season'}, '227': {'name': '2006-07 WHL Season'}, '225': {'name': '2005-06 WHL Season'}, '223': {'name': '2004-05 WHL Season'}, '220': {'name': '2003-2004 WHL Season'}, '217': {'name': '2002-03 WHL Season'}, '215': {'name': '2001-2002 WHL Season'}, '213': {'name': '2000-2001 WHL Season'}, '211': {'name': '1999-2000 WHL Season'}, '209': {'name': '1998-99 WHL Season'}, '206': {'name': '1997-98 WHL Season'}, '204': {'name': '1996-97 WHL Season'}}
WHL Standings:

  team_code wins losses points
0        PA   41      8     87
1       BDN   31     22     63
2       SAS   27     22     60
3       REG   19     26     45
4        MJ   19     28     45

In [123]:
standings

,team_code,wins,losses,ties,ot_losses,ot_wins,shootout_wins,shootout_losses,regulation_wins,row,points,penalty_minutes,streak,goals_for,goals_against,goals_diff,percentage,games_played,rank,past_10,name,prefixTeam,season,league,seasonName,seasonStartYear,seasonEndYear,teamId,teamName,teamLogo
0,PA,41,8,0,5,3,2,0,36,39,87,623,1-0-0-0,248,139,109,0.806,54,1,7-2-1-0,x - Prince Albert Raiders,x,289,whl,2025 - 26 Regular Season,2025,2026,209,Prince Albert Raiders,https://assets.leaguestat.com/whl/logos/209.png
1,BDN,31,22,0,1,4,2,0,25,29,63,691,3-0-0-0,215,197,18,0.583,54,2,6-4-0-0,Brandon Wheat Kings,None,289,whl,2025 - 26 Regular Season,2025,2026,201,Brandon Wheat Kings,https://assets.leaguestat.com/whl/logos/50x50/...
2,SAS,27,22,0,4,3,2,2,22,25,60,592,1-0-1-1,181,184,-3,0.545,55,3,3-5-1-1,Saskatoon Blades,None,289,whl,2025 - 26 Regular Season,2025,2026,213,Saskatoon Blades,https://assets.leaguestat.com/whl/logos/50x50/...
3,REG,19,26,0,6,4,0,1,15,19,45,605,3-0-0-0,181,213,-32,0.433,52,4,4-5-1-0,Regina Pats,None,289,whl,2025 - 26 Regular Season,2025,2026,212,Regina Pats,https://assets.leaguestat.com/whl/logos/212.png
4,MJ,19,28,0,5,4,1,2,14,18,45,560,0-4-1-0,190,238,-48,0.417,54,5,2-6-2-0,Moose Jaw Warriors,None,289,whl,2025 - 26 Regular Season,2025,2026,207,Moose Jaw Warriors,https://assets.leaguestat.com/whl/logos/207.png
5,SC,13,35,0,3,2,2,2,9,11,31,751,1-0-0-2,143,265,-122,0.292,53,6,3-5-0-2,Swift Current Broncos,None,289,whl,2025 - 26 Regular Season,2025,2026,216,Swift Current Broncos,https://assets.leaguestat.com/whl/logos/216.png
6,MH,36,9,0,5,5,2,3,29,34,80,739,2-0-2-0,249,164,85,0.755,53,1,5-2-2-1,x - Medicine Hat Tigers,x,289,whl,2025 - 26 Regular Season,2025,2026,206,Medicine Hat Tigers,https://assets.leaguestat.com/whl/logos/206.png
7,EDM,35,13,0,3,3,1,2,31,34,75,667,1-0-0-0,228,165,63,0.708,53,2,5-5-0-0,x - Edmonton Oil Kings,x,289,whl,2025 - 26 Regular Season,2025,2026,228,Edmonton Oil Kings,https://assets.leaguestat.com/whl/logos/228.png
8,CGY,30,15,0,6,2,2,1,26,28,67,473,0-1-0-0,198,160,38,0.644,52,3,7-3-0-0,Calgary Hitmen,None,289,whl,2025 - 26 Regular Season,2025,2026,202,Calgary Hitmen,https://assets.leaguestat.com/whl/logos/202.png
9,RD,20,28,0,2,4,1,2,15,19,44,702,1-0-0-0,151,194,-43,0.423,52,4,4-6-0-0,Red Deer Rebels,None,289,whl,2025 - 26 Regular Season,2025,2026,211,Red Deer Rebels,https://assets.leaguestat.com/whl/logos/211.png
10,LET,16,36,0,0,5,0,1,11,16,33,609,0-1-0-0,156,249,-93,0.311,53,5,4-6-0-0,Lethbridge Hurricanes,None,289,whl,2025 - 26 Regular Season,2025,2026,205,Lethbridge Hurricanes,https://assets.leaguestat.com/whl/logos/205.png
11,PEN,34,11,0,4,3,2,4,29,32,76,532,3-0-0-1,214,152,62,0.717,53,1,7-2-0-1,Penticton Vees,None,289,whl,2025 - 26 Regular Season,2025,2026,277,Penticton Vees,https://assets.leaguestat.com/whl/logos/50x50/...
12,PG,32,19,0,2,7,3,0,22,29,66,694,3-0-0-0,194,158,36,0.623,53,2,7-3-0-0,Prince George Cougars,None,289,whl,2025 - 26 Regular Season,2025,2026,210,Prince George Cougars,https://assets.leaguestat.com/whl/logos/210.png
13,KEL,28,18,0,5,0,3,2,25,25,63,812,1-0-0-0,203,185,18,0.594,53,3,6-3-1-0,Kelowna Rockets,None,289,whl,2025 - 26 Regular Season,2025,2026,204,Kelowna Rockets,https://assets.leaguestat.com/whl/logos/50x50/...
14,KAM,25,18,0,6,4,1,5,20,24,61,488,0-1-0-1,215,201,14,0.565,54,4,4-4-1-1,Kamloops Blazers,None,289,whl,2025 - 26 Regular Season,2025,2026,203,Kamloops Blazers,https://assets.leaguestat.com/whl/logos/203.png
15,VIC,22,22,0,5,3,3,3,16,19,52,541,0-1-0-0,164,195,-31,0.500,52,5,4-6-0-0,Victoria Royals,None,289,whl,2025 - 26 Regular Season,2025,2026,227,Victoria Royals,https://assets.leaguestat.com/whl/logos/227.png
16,VAN,20,31,0,1,3,3,2,14,17,43,638,0-1-0-0,162,228,-66,0.398,54,6,2-8-0-0,Vancouver Giants,None,289,whl,2025 - 26 Regular Season,2025,2026,223,Vancouver Giants,https://assets.leaguestat.com/whl/logos/223.png
17,EVT,45,6,0,2,5,2,1,38,43,93,659,13-0-0-0,235,132,103,0.861,54,1,10-0-0-0,xy - Everett Silvertips,xy,289,whl,2025 - 26 Regular Season,2025,2026,226,Everett Silvertips,https://assets.leaguestat.com/whl/logos/226.png
18,POR,25,24,0,4,3,2,1,20,23,55,752,0-1-0-1,195,213,-18,0.509,54,2,4-3-2-1,Portland Winterhawks,None,289,whl,2025 - 26 Regular Season,2025,2026,208,Portland Winterhawks,https://assets.leaguestat.com/whl/logos/50x50/...
19,TC,25,23,0,3,6,1,1,18,24,54,551,0-5-0-0,152,175,-23,0.519,52,3,3-7-0-0,Tri-City Americans,None,289,whl,2025 - 26 Regular Season,2025,2026,217,Tri-City Americans,https://assets.leaguestat.com/whl/logos/217.png
20,SPO,26,26,0,1,3,2,0,21,24,53,647,0-1-0-0,165,173,-8,0.500,53,4,4-6-0-0,Spokane Chiefs,None,289,whl,2025 - 26 Regular Season,2025,2026,215,Spokane Chiefs,https://assets.leaguestat.com/whl/logos/215.png
21,SEA,21,23,0,4,0,2,3,19,19,49,837,3-0-1-0,174,194,-20,0.480,51,5,4-4-1-1,Seattle Thunderbirds,None,289,whl,2025 - 26 Regular Season,2025,2026,214,Seattle Thunderbirds,https://assets.leaguestat.com/whl/logos/214.png
22,WEN,21,28,0,3,4,1,2,16,20,47,748,2-0-0-0,150,189,-39,0.435,54,6,4-4-2-0,Wenatchee Wild,None,289,whl,2025 - 26 Regular Season,2025,2026,222,Wenatchee Wild,https://assets.leaguestat.com/whl/logos/50x50/...

In [125]:
scrape('whl', 'standings', season=285)

,team_code,wins,losses,ties,ot_losses,ot_wins,shootout_wins,shootout_losses,regulation_wins,row,points,penalty_minutes,streak,goals_for,goals_against,goals_diff,percentage,games_played,rank,past_10,name,prefixTeam,season,league,seasonName,seasonStartYear,seasonEndYear,teamId,teamName,teamLogo
0,PA,39,23,0,5,5,3,1,31,36,84,776,5-0-0-0,253,228,25,0.618,68,1,6-3-1-0,xy - Prince Albert Raiders,xy,285,whl,2024 - 25 Regular Season,2024,2025,209,Prince Albert Raiders,https://assets.leaguestat.com/whl/logos/209.png
1,BDN,38,23,0,4,3,1,3,34,37,83,750,2-0-0-0,255,213,42,0.610,68,2,6-4-0-0,x - Brandon Wheat Kings,x,285,whl,2024 - 25 Regular Season,2024,2025,201,Brandon Wheat Kings,https://assets.leaguestat.com/whl/logos/50x50/...
2,SAS,37,23,0,4,8,1,4,28,36,82,550,0-1-1-0,235,218,17,0.603,68,3,6-3-1-0,x - Saskatoon Blades,x,285,whl,2024 - 25 Regular Season,2024,2025,213,Saskatoon Blades,https://assets.leaguestat.com/whl/logos/50x50/...
3,SC,35,30,0,1,6,4,2,25,31,73,756,0-1-0-0,240,256,-16,0.537,68,4,4-5-0-1,x - Swift Current Broncos,x,285,whl,2024 - 25 Regular Season,2024,2025,216,Swift Current Broncos,https://assets.leaguestat.com/whl/logos/216.png
4,REG,16,44,0,5,5,2,3,9,14,40,765,0-2-0-0,170,285,-115,0.294,68,5,1-8-0-1,Regina Pats,None,285,whl,2024 - 25 Regular Season,2024,2025,212,Regina Pats,https://assets.leaguestat.com/whl/logos/212.png
5,MJ,15,45,0,6,1,2,2,12,13,38,685,1-0-0-0,189,308,-119,0.279,68,6,4-4-2-0,Moose Jaw Warriors,None,285,whl,2024 - 25 Regular Season,2024,2025,207,Moose Jaw Warriors,https://assets.leaguestat.com/whl/logos/207.png
6,MH,47,17,0,3,2,2,1,43,45,98,860,10-0-0-0,300,193,107,0.721,68,1,10-0-0-0,xy - Medicine Hat Tigers,xy,285,whl,2024 - 25 Regular Season,2024,2025,206,Medicine Hat Tigers,https://assets.leaguestat.com/whl/logos/206.png
7,CGY,45,17,0,3,8,0,3,37,45,96,665,0-1-0-0,266,183,83,0.706,68,2,7-2-0-1,x - Calgary Hitmen,x,285,whl,2024 - 25 Regular Season,2024,2025,202,Calgary Hitmen,https://assets.leaguestat.com/whl/logos/202.png
8,LET,42,21,0,3,5,2,2,35,40,89,749,0-1-0-0,226,199,27,0.654,68,3,6-2-1-1,x - Lethbridge Hurricanes,x,285,whl,2024 - 25 Regular Season,2024,2025,205,Lethbridge Hurricanes,https://assets.leaguestat.com/whl/logos/205.png
9,EDM,37,27,0,2,1,2,2,34,35,78,891,1-0-0-0,248,211,37,0.574,68,4,5-5-0-0,x - Edmonton Oil Kings,x,285,whl,2024 - 25 Regular Season,2024,2025,228,Edmonton Oil Kings,https://assets.leaguestat.com/whl/logos/228.png
10,RD,26,34,0,6,1,2,2,23,24,60,980,0-4-1-0,174,244,-70,0.441,68,5,3-6-1-0,Red Deer Rebels,None,285,whl,2024 - 25 Regular Season,2024,2025,211,Red Deer Rebels,https://assets.leaguestat.com/whl/logos/211.png
11,VIC,40,17,0,4,5,4,7,31,36,91,668,4-0-1-0,272,218,54,0.669,68,1,6-2-1-1,xy - Victoria Royals,xy,285,whl,2024 - 25 Regular Season,2024,2025,227,Victoria Royals,https://assets.leaguestat.com/whl/logos/227.png
12,PG,41,21,0,4,2,2,2,37,39,88,897,1-0-0-0,251,222,29,0.647,68,2,8-2-0-0,x - Prince George Cougars,x,285,whl,2024 - 25 Regular Season,2024,2025,210,Prince George Cougars,https://assets.leaguestat.com/whl/logos/210.png
13,VAN,34,26,0,8,4,2,0,28,32,76,732,2-0-0-0,252,246,6,0.559,68,3,6-3-1-0,x - Vancouver Giants,x,285,whl,2024 - 25 Regular Season,2024,2025,223,Vancouver Giants,https://assets.leaguestat.com/whl/logos/223.png
14,KAM,24,39,0,4,5,0,1,19,24,53,674,0-3-0-0,206,271,-65,0.390,68,4,3-7-0-0,Kamloops Blazers,None,285,whl,2024 - 25 Regular Season,2024,2025,203,Kamloops Blazers,https://assets.leaguestat.com/whl/logos/203.png
15,KEL,18,44,0,4,1,0,2,17,18,42,898,0-1-0-0,213,311,-98,0.309,68,5,1-9-0-0,Kelowna Rockets,None,285,whl,2024 - 25 Regular Season,2024,2025,204,Kelowna Rockets,https://assets.leaguestat.com/whl/logos/50x50/...
16,EVT,48,12,0,4,6,0,4,42,48,104,725,5-0-0-1,277,178,99,0.765,68,1,8-1-0-1,xyz - Everett Silvertips,xyz,285,whl,2024 - 25 Regular Season,2024,2025,226,Everett Silvertips,https://assets.leaguestat.com/whl/logos/226.png
17,SPO,45,20,0,1,4,2,2,39,43,93,880,1-0-0-1,292,202,90,0.684,68,2,6-3-0-1,x - Spokane Chiefs,x,285,whl,2024 - 25 Regular Season,2024,2025,215,Spokane Chiefs,https://assets.leaguestat.com/whl/logos/215.png
18,POR,36,28,0,3,4,4,1,28,32,76,848,0-2-0-0,261,269,-8,0.559,68,3,5-5-0-0,x - Portland Winterhawks,x,285,whl,2024 - 25 Regular Season,2024,2025,208,Portland Winterhawks,https://assets.leaguestat.com/whl/logos/50x50/...
19,TC,32,29,0,6,9,4,1,19,28,71,823,0-2-0-0,234,268,-34,0.522,68,4,2-6-2-0,x - Tri-City Americans,x,285,whl,2024 - 25 Regular Season,2024,2025,217,Tri-City Americans,https://assets.leaguestat.com/whl/logos/217.png
20,SEA,30,33,0,4,2,7,1,21,23,65,1005,4-0-0-0,212,257,-45,0.478,68,5,6-3-1-0,x - Seattle Thunderbirds,x,285,whl,2024 - 25 Regular Season,2024,2025,214,Seattle Thunderbirds,https://assets.leaguestat.com/whl/logos/214.png
21,WEN,23,36,0,8,5,1,1,17,22,55,781,0-3-1-0,207,253,-46,0.404,68,6,3-6-1-0,Wenatchee Wild,None,285,whl,2024 - 25 Regular Season,2024,2025,222,Wenatchee Wild,https://assets.leaguestat.com/whl/logos/50x50/...

In [126]:
scrape('qmjhl', 'standings', season=211)

,team_code,wins,losses,ot_losses,ot_wins,shootout_wins,shootout_losses,row,points,penalty_minutes,streak,goals_for,goals_against,goals_diff,percentage,overall_rank,games_played,rank,past_10,name,prefixTeam,season,league,seasonName,seasonStartYear,seasonEndYear,teamId,teamName,teamLogo
0,Mon,38,8,2,3,5,1,33,79,599,10-0-0-0,234,127,107,0.806,1,49,1,10-0-0-0,"x - Moncton, Wildcats",x,211,qmjhl,2025-26 | Regular Season,2025,2026,1,"Moncton, Wildcats",https://assets.leaguestat.com/lhjmq/logos/1.png
1,Chi,36,8,3,1,1,2,35,77,440,4-0-0-0,223,124,99,0.786,2,49,2,8-2-0-0,"x - Chicoutimi, Saguenéens",x,211,qmjhl,2025-26 | Regular Season,2025,2026,10,"Chicoutimi, Saguenéens",https://assets.leaguestat.com/lhjmq/logos/10.png
2,NFL,31,19,1,5,2,1,29,64,663,5-0-0-0,198,176,22,0.615,7,52,3,7-3-0-0,"x - Newfoundland, Regiment",x,211,qmjhl,2025-26 | Regular Season,2025,2026,2,"Newfoundland, Regiment",https://assets.leaguestat.com/lhjmq/logos/2_21...
3,Cap,26,16,2,1,3,8,23,62,491,2-0-0-1,151,154,-3,0.596,8,52,4,5-1-1-3,"Cape Breton, Eagles",None,211,qmjhl,2025-26 | Regular Season,2025,2026,3,"Cape Breton, Eagles",https://assets.leaguestat.com/lhjmq/logos/3.png
4,Que,26,19,3,3,1,1,25,56,604,3-0-0-0,163,154,9,0.571,9,49,5,6-4-0-0,"Québec, Remparts",None,211,qmjhl,2025-26 | Regular Season,2025,2026,9,"Québec, Remparts",https://assets.leaguestat.com/lhjmq/logos/9.png
5,Cha,23,20,2,5,2,6,21,54,569,1-0-0-0,164,195,-31,0.529,10,51,6,5-5-0-0,"Charlottetown, Islanders",None,211,qmjhl,2025-26 | Regular Season,2025,2026,7,"Charlottetown, Islanders",https://assets.leaguestat.com/lhjmq/logos/7.png
6,Hal,23,23,3,3,3,2,20,51,498,0-1-0-0,163,200,-37,0.500,13,51,7,4-5-1-0,"Halifax, Mooseheads",None,211,qmjhl,2025-26 | Regular Season,2025,2026,5,"Halifax, Mooseheads",https://assets.leaguestat.com/lhjmq/logos/5_21...
7,SNB,18,28,5,4,0,0,18,41,516,1-0-0-0,173,212,-39,0.402,15,51,8,2-7-1-0,"Saint John, Sea Dogs",None,211,qmjhl,2025-26 | Regular Season,2025,2026,8,"Saint John, Sea Dogs",https://assets.leaguestat.com/lhjmq/logos/50x5...
8,Rim,18,31,0,6,2,1,16,37,509,0-12-0-0,128,203,-75,0.370,16,50,9,0-10-0-0,"Rimouski, Océanic",None,211,qmjhl,2025-26 | Regular Season,2025,2026,18,"Rimouski, Océanic",https://assets.leaguestat.com/lhjmq/logos/18_2...
9,BaC,12,34,4,2,0,2,12,30,557,0-4-0-0,111,201,-90,0.288,18,52,10,1-9-0-0,"Baie-Comeau, Drakkar",None,211,qmjhl,2025-26 | Regular Season,2025,2026,16,"Baie-Comeau, Drakkar",https://assets.leaguestat.com/lhjmq/logos/16.png
10,BLB,31,14,5,1,0,1,31,68,653,0-1-0-0,213,139,74,0.667,3,51,1,8-2-0-0,"x - Blainville-Boisbriand, Armada",x,211,qmjhl,2025-26 | Regular Season,2025,2026,19,"Blainville-Boisbriand, Armada",https://assets.leaguestat.com/lhjmq/logos/19.png
11,Dru,30,15,3,4,0,3,30,66,412,2-0-1-0,187,150,37,0.647,4,51,2,6-3-1-0,"x - Drummondville, Voltigeurs",x,211,qmjhl,2025-26 | Regular Season,2025,2026,14,"Drummondville, Voltigeurs",https://assets.leaguestat.com/lhjmq/logos/50x5...
12,Sha,30,16,2,4,1,4,29,66,576,0-1-1-1,205,173,32,0.635,5,52,3,6-2-1-1,"x - Shawinigan, Cataractes",x,211,qmjhl,2025-26 | Regular Season,2025,2026,13,"Shawinigan, Cataractes",https://assets.leaguestat.com/lhjmq/logos/13.png
13,Rou,29,14,5,3,2,2,27,65,468,2-0-0-0,158,145,13,0.650,6,50,4,6-3-1-0,"x - Rouyn-Noranda, Huskies",x,211,qmjhl,2025-26 | Regular Season,2025,2026,11,"Rouyn-Noranda, Huskies",https://assets.leaguestat.com/lhjmq/logos/50x5...
14,VdO,24,22,2,1,1,3,23,53,569,0-3-0-0,185,190,-5,0.520,11,51,5,5-5-0-0,"Val-d'Or, Foreurs",None,211,qmjhl,2025-26 | Regular Season,2025,2026,15,"Val-d'Or, Foreurs",https://assets.leaguestat.com/lhjmq/logos/15.png
15,She,24,22,4,6,5,0,19,52,633,4-0-0-0,152,178,-26,0.520,12,50,6,6-4-0-0,"Sherbrooke, Phœnix",None,211,qmjhl,2025-26 | Regular Season,2025,2026,60,"Sherbrooke, Phœnix",https://assets.leaguestat.com/lhjmq/logos/50x5...
16,Vic,19,26,5,1,6,0,13,43,573,1-0-0-0,154,195,-41,0.430,14,50,7,4-6-0-0,"Victoriaville, Tigres",None,211,qmjhl,2025-26 | Regular Season,2025,2026,17,"Victoriaville, Tigres",https://assets.leaguestat.com/lhjmq/logos/17.png
17,Gat,16,30,4,1,4,1,12,37,604,0-4-0-1,114,166,-52,0.363,17,51,8,1-8-0-1,"Gatineau, Olympiques",None,211,qmjhl,2025-26 | Regular Season,2025,2026,12,"Gatineau, Olympiques",https://assets.leaguestat.com/lhjmq/logos/50x5...

In [147]:
scrape('qmjhl', 'roster', team=1,season=211)

,shoots,birthplace,player_id,birthdate,tp_jersey_number,rookie,position,h,w,name,catches,lastName,firstName,teamId,teamName,teamCode,teamLogo,season,league,seasonName,seasonStartYear,seasonEndYear,n_birthplace,birthCity,birthCountry,birthState,height_cm,shootsCatches
0,L,"St.Andrews, NB, Canada",19539,2006-08-03,9,0,C,"6'04""",225,"Smith, Gabe",NaN,Smith,Gabe,1,"Moncton, Wildcats",Mon,https://assets.leaguestat.com/lhjmq/logos/1.png,211,qmjhl,2025-26 | Regular Season,2025,2026,3,St.Andrews,Canada,NB,193.04,L
1,R,"Ste-Foy, QC, Canada",19090,2005-09-22,10,0,RW,"5'10""",183,"Mercier, Alex",NaN,Mercier,Alex,1,"Moncton, Wildcats",Mon,https://assets.leaguestat.com/lhjmq/logos/1.png,211,qmjhl,2025-26 | Regular Season,2025,2026,3,Ste-Foy,Canada,QC,177.80,R
2,L,"Fairbanks, AK, United States",22466,2006-02-14,12,0,LW,"6'00""",191,"Binkley, Simon",NaN,Binkley,Simon,1,"Moncton, Wildcats",Mon,https://assets.leaguestat.com/lhjmq/logos/1.png,211,qmjhl,2025-26 | Regular Season,2025,2026,3,Fairbanks,United States,AK,182.88,L
3,R,"Norwell, MA, United States",20414,2007-02-16,14,1,C,"6'01""",209,"Mutryn, Teddy",NaN,Mutryn,Teddy,1,"Moncton, Wildcats",Mon,https://assets.leaguestat.com/lhjmq/logos/1.png,211,qmjhl,2025-26 | Regular Season,2025,2026,3,Norwell,United States,MA,185.42,R
4,R,"Danbury, CT, United States",24195,2006-01-07,17,0,RW,"6'00""",215,"Wingfield, Jacob",NaN,Wingfield,Jacob,1,"Moncton, Wildcats",Mon,https://assets.leaguestat.com/lhjmq/logos/1.png,211,qmjhl,2025-26 | Regular Season,2025,2026,3,Danbury,United States,CT,182.88,R
5,L,"St-Hyacinthe, QC, Canada",20164,2007-04-11,18,0,C,"6'02""",173,"Desnoyers, Caleb",NaN,Desnoyers,Caleb,1,"Moncton, Wildcats",Mon,https://assets.leaguestat.com/lhjmq/logos/1.png,211,qmjhl,2025-26 | Regular Season,2025,2026,3,St-Hyacinthe,Canada,QC,187.96,L
6,L,"Salisbury, NB, Canada",19127,2005-04-12,20,0,LW,"6'01""",181,"Lounsbury, Preston",NaN,Lounsbury,Preston,1,"Moncton, Wildcats",Mon,https://assets.leaguestat.com/lhjmq/logos/1.png,211,qmjhl,2025-26 | Regular Season,2025,2026,3,Salisbury,Canada,NB,185.42,L
7,R,"Needham, MA, United States",22262,2007-12-30,22,1,RW,"6'01""",190,"Chudzinski, Rian",NaN,Chudzinski,Rian,1,"Moncton, Wildcats",Mon,https://assets.leaguestat.com/lhjmq/logos/1.png,211,qmjhl,2025-26 | Regular Season,2025,2026,3,Needham,United States,MA,185.42,R
8,L,"Havre Boucher, NS, Canada",19625,2006-05-23,23,0,C,"6'03""",196,"Sampson, Riley",NaN,Sampson,Riley,1,"Moncton, Wildcats",Mon,https://assets.leaguestat.com/lhjmq/logos/1.png,211,qmjhl,2025-26 | Regular Season,2025,2026,3,Havre Boucher,Canada,NS,190.50,L
9,L,"Boxford, MA, United States",21450,2008-06-22,26,1,LW,"6'00""",180,"Thornborough, Spencer",NaN,Thornborough,Spencer,1,"Moncton, Wildcats",Mon,https://assets.leaguestat.com/lhjmq/logos/1.png,211,qmjhl,2025-26 | Regular Season,2025,2026,3,Boxford,United States,MA,182.88,L
10,L,"Yaroslav, Russia",23749,2006-07-27,27,0,LW,"5'11""",172,"Voronin, Kuzma",NaN,Voronin,Kuzma,1,"Moncton, Wildcats",Mon,https://assets.leaguestat.com/lhjmq/logos/1.png,211,qmjhl,2025-26 | Regular Season,2025,2026,2,Yaroslav,Russia,NaN,180.34,L
11,R,"Warman, SK, Canada",24105,2007-01-16,36,1,C,"6'00""",175,"Bursaw, Liam",NaN,Bursaw,Liam,1,"Moncton, Wildcats",Mon,https://assets.leaguestat.com/lhjmq/logos/1.png,211,qmjhl,2025-26 | Regular Season,2025,2026,3,Warman,Canada,SK,182.88,R
12,L,"St.Andrews, NB, Canada",23424,2007-08-29,71,1,C,"5'11""",192,"Robertson-Palmer, Grayden",NaN,Robertson-Palmer,Grayden,1,"Moncton, Wildcats",Mon,https://assets.leaguestat.com/lhjmq/logos/1.png,211,qmjhl,2025-26 | Regular Season,2025,2026,3,St.Andrews,Canada,NB,180.34,L
13,R,"Redding, CT, Canada",20447,2006-02-17,86,0,RW,"6'02""",198,"Tournas, Niko",NaN,Tournas,Niko,1,"Moncton, Wildcats",Mon,https://assets.leaguestat.com/lhjmq/logos/1.png,211,qmjhl,2025-26 | Regular Season,2025,2026,3,Redding,Canada,CT,187.96,R
14,R,"Boston, MA, United States",19619,2006-12-15,92,0,RW,"5'09""",170,"Cornforth, Gavin",NaN,Cornforth,Gavin,1,"Moncton, Wildcats",Mon,https://assets.leaguestat.com/lhjmq/logos/1.png,211,qmjhl,2025-26 | Regular Season,2025,2026,3,Boston,United States,MA,175.26,R
15,L,"Hammarlöv, Sweden",23761,2006-06-29,2,0,D,"6'03""",198,"Vilen, Max",NaN,Vilen,Max,1,"Moncton, Wildcats",Mon,https://assets.leaguestat.com/lhjmq/logos/1.png,211,qmjhl,2025-26 | Regular Season,2025,2026,2,Hammarlöv,Sweden,NaN,190.50,L
16,R,"Stratford, PE, Canada",21315,2008-02-17,7,1,D,"6'01""",155,"Batchilder, Jackson",NaN,Batchilder,Jackson,1,"Moncton, Wildcats",Mon,https://assets.leaguestat.com/lhjmq/logos/1.png,211,qmjhl,2025-26 | Regular Season,2025,2026,3,Stratford,Canada,PE,185.42,R
17,R,"Richmond Hill, ON, Canada",23995,2006-03-24,15,0,D,"6'00""",200,"Virgilio, Matthew",NaN,Virgilio,Matthew,1,"Moncton, Wildcats",Mon,https://assets.leaguestat.com/lhjmq/logos/1.png,211,qmjhl,2025-26 | Regular Season,2025,2026,3,Richmond Hill,Canada,ON,182.88,R
18,R,"Glenville, NY, United States",23895,2007-12-01,16,1,D,"6'00""",160,"Bleyl, Tommy",NaN,Bleyl,Tommy,1,"Moncton, Wildcats",Mon,https://assets.leaguestat.com/lhjmq/logos/1.png,211,qmjhl,2025-26 | Regular Season,2025,2026,3,Glenville,United States,NY,182.88,R
19,L,"Stratford, PE, Canada",19716,2006-04-02,21,0,D,"6'00""",188,"Diamond, Aiden",NaN,Diamond,Aiden,1,"Moncton, Wildcats",Mon,https://assets.leaguestat.com/lhjmq/logos/1.png,211,qmjhl,2025-26 | Regular Season,2025,2026,3,Stratford,Canada,PE,182.88,L
20,L,"Repentigny, QC, Canada",19528,2006-01-21,24,0,D,"5'10""",196,"Fortier-Gendron, Adam",NaN,Fortier-Gendron,Adam,1,"Moncton, Wildcats",Mon,https://assets.leaguestat.com/lhjmq/logos/1.png,211,qmjhl,2025-26 | Regular Season,2025,2026,3,Repentigny,Canada,QC,177.80,L
21,L,"Salo, Finland",23747,2006-01-16,38,0,D,"6'04""",235,"Wallenius, Eerik",NaN,Wallenius,Eerik,1,"Moncton, Wildcats",Mon,https://assets.leaguestat.com/lhjmq/logos/1.png,211,qmjhl,2025-26 | Regular Season,2025,2026,2,Salo,Finland,NaN,193.04,L
22,R,"Granby, QC, Canada",19555,2006-08-19,44,0,D,"5'09""",175,"Dépatie, Evan",NaN,Dépatie,Evan,1,"Moncton, Wildcats",Mon,https://assets.leaguestat.com/lhjmq/logos/1.png,211,qmjhl,2025-26 | Regular Season,2025,2026,3,Granby,Canada,QC,175.26,R
23,NaN,"Montréal, QC, Canada",22092,2005-05-19,25,0,G,"6'04""",187,"Guimond, Rudy",L,Guimond,Rudy,1,"Moncton, Wildcats",Mon,https://assets.leaguestat.com/lhjmq/logos/1.png,211,qmjhl,2025-26 | Regular Season,2025,2026,3,Montréal,Canada,QC,193.04,L
24,NaN,"Riverside City, CT, United States",21388,2008-06-19,35,1,G,"6'04""",228,"Weiner, Jacoby",L,Weiner,Jacoby,1,"Moncton, Wildcats",Mon,https://assets.leaguestat.com/lhjmq/logos/1.png,211,qmjhl,2025-26 | Regular Season,2025,2026,3,Riverside City,United States,CT,193.04,L

## Method 2: Object-Oriented API (Advanced Usage)

For more control, you can create a `HockeyScraper` object:

### ✨ NEW: Automatic Bootstrap Fetching

When you create a scraper for non-NHL leagues, bootstrap data (teams, seasons, divisions) is **automatically fetched**!

In [40]:
from scrapernhl import HockeyScraper


for league in ['ohl', 'whl', 'qmjhl', 'ahl', 'pwhl']:
    # Create a scraper for the OHL
    scraper = HockeyScraper(league)

    # Bootstrap data is automatically fetched!
    print(f"Bootstrap auto-fetched on initialization:")
    print(f"  League ID: {scraper.current_league_id}")
    print(f"  Season ID: {scraper.current_season_id}")
    print(f"  Teams: {len(scraper.teams)}")

    # Access team data easily
    print(f"\nFirst 5 teams:")
    for team in scraper.teams[:5]:
        print(f"  - {team['name']} (ID: {team['id']})")

    # Use methods to get data
    stats = scraper.player_stats(season=83, position='skaters', limit=15)
    schedule = scraper.schedule(season=83, team='all')  # 'all' or team_id
    standings = scraper.standings(season=83)

    print(f"\nData retrieved:")
    print(f"  Stats: {len(stats)} rows")
    print(f"  Schedule: {len(schedule)} games")
    print(f"  Standings: {len(standings)} teams")

    bootstrap_keys = scraper.bootstrap_data.keys()
    print(f"\nBootstrap data keys: {bootstrap_keys}")

Bootstrap auto-fetched on initialization:
  League ID: 1
  Season ID: 83
  Teams: 20

First 5 teams:
  - Barrie Colts (ID: 7)
  - Brampton Steelheads (ID: 18)
  - Brantford Bulldogs (ID: 1)
  - Erie Otters (ID: 8)
  - Flint Firebirds (ID: 13)

Data retrieved:
  Stats: 15 rows
  Schedule: 683 games
  Standings: 20 teams

Bootstrap data keys: dict_keys(['firebaseUrl', 'firebaseToken', 'firebaseApiKey', 'current_league_id', 'current_season_id', 'leagues', 'seasons', 'conferences', 'conferencesAll', 'divisions', 'divisionsAll', 'first_season_year', 'regularSeasons', 'playoffSeasons', 'teams', 'teamsNoAll', 'months', 'monthsAll', 'positions', 'goalies', 'rosterstatus', 'standingsFooter', 'rosterFooter', 'playerStatsFooter', 'showExpandedGoaliesOption', 'showRosterStatus', 'quickViews', 'dailySchedRefreshToggle', 'playerNoPicLogoOverride', 'svfConfig', 'svfLanguages', 'svfLang', 'player_shot_heat_map'])
Bootstrap auto-fetched on initialization:
  League ID: 26
  Season ID: 289
  Teams: 23

First 5 teams:
  - Brandon Wheat Kings (ID: 201)
  - Calgary Hitmen (ID: 202)
  - Edmonton Oil Kings (ID: 228)
  - Everett Silvertips (ID: 226)
  - Kamloops Blazers (ID: 203)

KeyError: 'homeId'

In [17]:
bs_data = {}
for league in ['ohl', 'whl', 'qmjhl', 'ahl', 'pwhl']:
    scraper = HockeyScraper(league)
    bs_data[league] = scraper.bootstrap_data
    
bs_data

{'ohl': {'firebaseUrl': 'leaguestat-b9523.firebaseio.com',
  'firebaseToken': 'uwM69pPkdUhb0UuVAxM8IcA6pBAzATAxOc8979oJ',
  'firebaseApiKey': 'AIzaSyBVn0Gr6zIFtba-hQy3StkifD8bb7Hi68A',
  'current_league_id': '1',
  'current_season_id': '83',
  'leagues': [{'id': '2',
    'name': 'Canadian Hockey League',
    'short_name': 'CHL',
    'code': 'chl',
    'logo_image': ''},
   {'id': '3',
    'name': 'OHL All Star Game',
    'short_name': 'All Star',
    'code': 'allstar',
    'logo_image': ''},
   {'id': '1',
    'name': 'Ontario Hockey League',
    'short_name': 'OHL',
    'code': 'ohl',
    'logo_image': 'https://lscluster.hockeytech.com/download.php?client_code=ohl&file_path=img/logos/league-logo-1.jpg'},
   {'id': '4',
    'name': 'Tournaments',
    'short_name': 'tourney',
    'code': 'tourney',
    'logo_image': ''}],
  'seasons': [{'id': '84',
    'name': '2025-26 OHL Top Prospects',
    'default_sort': '',
    'start_date': '2026-01-10',
    'hide_in_standings': False},
   {'id': '83',
    'name': '2025-26 Regular Season',
    'default_sort': '',
    'start_date': '2025-09-16',
    'hide_in_standings': False},
   {'id': '82',
    'name': '2025 Pre-Season',
    'default_sort': '',
    'start_date': '2025-08-13',
    'hide_in_standings': False},
   {'id': '81',
    'name': '2025 Playoffs',
    'default_sort': '',
    'start_date': '2025-03-26',
    'hide_in_standings': False},
   {'id': '79',
    'name': '2024-25 Regular Season',
    'default_sort': '',
    'start_date': '2024-09-23',
    'hide_in_standings': False},
   {'id': '78',
    'name': '2024 Pre-season',
    'default_sort': '',
    'start_date': '2024-08-15',
    'hide_in_standings': False},
   {'id': '77',
    'name': '2024 Playoffs',
    'default_sort': '',
    'start_date': '2024-03-26',
    'hide_in_standings': False},
   {'id': '76',
    'name': '2023-24 Regular Season',
    'default_sort': '',
    'start_date': '2023-09-26',
    'hide_in_standings': False},
   {'id': '75',
    'name': '2023 Pre-season',
    'default_sort': '',
    'start_date': '2023-08-15',
    'hide_in_standings': False},
   {'id': '74',
    'name': '2023 Playoffs',
    'default_sort': '',
    'start_date': '2023-03-29',
    'hide_in_standings': False},
   {'id': '73',
    'name': '2022-23 Regular Season',
    'default_sort': '',
    'start_date': '2022-09-27',
    'hide_in_standings': True},
   {'id': '72',
    'name': '2022 Pre-season',
    'default_sort': '',
    'start_date': '2022-08-15',
    'hide_in_standings': False},
   {'id': '71',
    'name': '2022 Playoffs',
    'default_sort': '',
    'start_date': '2022-04-19',
    'hide_in_standings': False},
   {'id': '70',
    'name': '2021-22 Regular Season',
    'default_sort': '',
    'start_date': '2021-10-04',
    'hide_in_standings': False},
   {'id': '69',
    'name': '2021 Pre-season',
    'default_sort': '',
    'start_date': '2021-08-18',
    'hide_in_standings': False},
   {'id': '68',
    'name': '2019-20 Regular Season',
    'default_sort': '',
    'start_date': '2019-09-17',
    'hide_in_standings': False},
   {'id': '67',
    'name': '2019 Pre-season',
    'default_sort': '',
    'start_date': '2019-08-01',
    'hide_in_standings': False},
   {'id': '66',
    'name': '2019 Playoffs',
    'default_sort': '',
    'start_date': '2019-03-19',
    'hide_in_standings': False},
   {'id': '63',
    'name': '2018-19 Regular Season',
    'default_sort': '',
    'start_date': '2018-09-17',
    'hide_in_standings': False},
   {'id': '62',
    'name': '2018 Pre-season',
    'default_sort': '',
    'start_date': '2018-08-01',
    'hide_in_standings': False},
   {'id': '61',
    'name': '2018 Playoffs',
    'default_sort': '',
    'start_date': '2018-03-21',
    'hide_in_standings': False},
   {'id': '60',
    'name': '2017-18 Regular Season',
    'default_sort': '',
    'start_date': '2017-09-18',
    'hide_in_standings': False},
   {'id': '59',
    'name': '2017 Pre-season',
    'default_sort': '',
    'start_date': '2017-08-16',
    'hide_in_standings': False},
   {'id': '58',
    'name': '2017 Playoffs',
    'default_sort': '',
    'start_date': '2017-03-21',
    'hide_in_standings': False},
   {'id': '56',
    'name': '2016-17 Regular Season',
    'default_sort': '',
    'start_date': '2016-09-19',
    'hide_in_standings': False},
   {'id': '57',
    'name': '2016 Pre-season',
    'default_sort': '',
    'start_date': '2016-08-15',
    'hide_in_standings': False},
   {'id': '55',
    'name': '2016 Playoffs',
    'default_sort': '',
    'start_date': '2016-03-21',
    'hide_in_standings': False},
   {'id': '54',
    'name': '2015-16 Regular Season',
    'default_sort': '',
    'start_date': '2015-09-21',
    'hide_in_standings': False},
   {'id': '53',
    'name': '2015 Pre-season',
    'default_sort': '',
    'start_date': '2015-07-15',
    'hide_in_standings': False},
   {'id': '52',
    'name': '2015 Playoffs',
    'default_sort': '',
    'start_date': '2015-03-23',
    'hide_in_standings': False},
   {'id': '51',
    'name': '2014-15 Regular Season',
    'default_sort': '',
    'start_date': '2014-08-17',
    'hide_in_standings': False},
   {'id': '50',
    'name': '2014 Playoffs',
    'default_sort': '',
    'start_date': '2014-03-19',
    'hide_in_standings': False},
   {'id': '49',
    'name': '2013-14 Regular Season',
    'default_sort': '',
    'start_date': '2013-08-15',
    'hide_in_standings': False},
   {'id': '48',
    'name': '2013 Playoffs',
    'default_sort': '',
    'start_date': '2013-03-19',
    'hide_in_standings': False},
   {'id': '46',
    'name': '2012-13 Regular Season',
    'default_sort': '',
    'start_date': '2012-09-19',
    'hide_in_standings': False},
   {'id': '45',
    'name': '2012 Playoffs',
    'default_sort': '',
    'start_date': '2012-03-20',
    'hide_in_standings': False},
   {'id': '44',
    'name': '2011-12 Regular Season',
    'default_sort': '',
    'start_date': '2011-08-01',
    'hide_in_standings': False},
   {'id': '43',
    'name': '2011 Playoffs',
    'default_sort': '',
    'start_date': '2011-03-21',
    'hide_in_standings': False},
   {'id': '42',
    'name': '2010-11 Regular Season',
    'default_sort': '',
    'start_date': '2010-09-01',
    'hide_in_standings': False},
   {'id': '41',
    'name': '2010 Playoffs',
    'default_sort': '',
    'start_date': '2010-03-16',
    'hide_in_standings': False},
   {'id': '40',
    'name': '2009-10 All-Star Classic',
    'default_sort': '',
    'start_date': '2010-01-29',
    'hide_in_standings': False},
   {'id': '38',
    'name': '2009-10 Regular Season',
    'default_sort': '',
    'start_date': '2009-09-06',
    'hide_in_standings': False},
   {'id': '37',
    'name': '2009 Playoffs',
    'default_sort': '',
    'start_date': '2009-03-17',
    'hide_in_standings': False},
   {'id': '36',
    'name': '2008-09 All-Star Classic',
    'default_sort': '',
    'start_date': '2009-02-03',
    'hide_in_standings': False},
   {'id': '35',
    'name': '2008-09 Regular Season',
    'default_sort': '',
    'start_date': '2008-09-17',
    'hide_in_standings': False},
   {'id': '34',
    'name': '2008 Playoffs',
    'default_sort': '',
    'start_date': '2008-03-19',
    'hide_in_standings': False},
   {'id': '33',
    'name': '2007-08 All-Star Classic',
    'default_sort': '',
    'start_date': '2008-02-04',
    'hide_in_standings': False},
   {'id': '32',
    'name': '2007-08 Regular Season',
    'default_sort': '',
    'start_date': '2007-09-07',
    'hide_in_standings': False},
   {'id': '31',
    'name': '2007 Playoffs',
    'default_sort': '',
    'start_date': '2007-03-22',
    'hide_in_standings': False},
   {'id': '30',
    'name': '2006-07 All-Star Classic',
    'default_sort': '',
    'start_date': '2007-01-28',
    'hide_in_standings': False},
   {'id': '29',
    'name': '2006-07 Regular Season',
    'default_sort': '',
    'start_date': '2006-09-20',
    'hide_in_standings': False},
   {'id': '28',
    'name': '2006 Playoffs',
    'default_sort': '',
    'start_date': '2006-03-23',
    'hide_in_standings': False},
   {'id': '27',
    'name': '2005-06 All Star Classic',
    'default_sort': '',
    'start_date': '2006-02-01',
    'hide_in_standings': False},
   {'id': '26',
    'name': '2005-06 Regular Season',
    'default_sort': '',
    'start_date': '2005-09-05',
    'hide_in_standings': False},
   {'id': '25',
    'name': '2005 Playoffs',
    'default_sort': '',
    'start_date': '2005-03-24',
    'hide_in_standings': False},
   {'id': '24',
    'name': '2004-05 Regular Season',
    'default_sort': '',
    'start_date': '2004-09-06',
    'hide_in_standings': False},
   {'id': '23',
    'name': '2004 Playoffs',
    'default_sort': '',
    'start_date': '2004-03-17',
    'hide_in_standings': False},
   {'id': '21',
    'name': '2003-04 Regular Season',
    'default_sort': '',
    'start_date': '2003-09-17',
    'hide_in_standings': False},
   {'id': '20',
    'name': '2003 Playoffs',
    'default_sort': '',
    'start_date': '2003-03-20',
    'hide_in_standings': False},
   {'id': '17',
    'name': '2002-03 Regular Season',
    'default_sort': '',
    'start_date': '2002-09-18',
    'hide_in_standings': False},
   {'id': '15',
    'name': '2002 Playoffs',
    'default_sort': '',
    'start_date': '2002-03-19',
    'hide_in_standings': False},
   {'id': '14',
    'name': '2001-02 Regular Season',
    'default_sort': '',
    'start_date': '2001-09-13',
    'hide_in_standings': False},
   {'id': '12',
    'name': '2001 Playoffs',
    'default_sort': '',
    'start_date': '2001-03-24',
    'hide_in_standings': False},
   {'id': '11',
    'name': '2000-01 Regular Season',
    'default_sort': '',
    'start_date': '2000-09-21',
    'hide_in_standings': False},
   {'id': '10',
    'name': '2000 Playoffs',
    'default_sort': '',
    'start_date': '2000-03-25',
    'hide_in_standings': False},
   {'id': '9',
    'name': '1999-2000 Regular Season',
    'default_sort': '',
    'start_date': '1999-09-22',
    'hide_in_standings': False},
   {'id': '7',
    'name': '1999 Playoffs',
    'default_sort': '',
    'start_date': '1999-03-20',
    'hide_in_standings': False},
   {'id': '6',
    'name': '1998-99 Regular Season',
    'default_sort': '',
    'start_date': '1998-09-24',
    'hide_in_standings': False},
   {'id': '5',
    'name': '1998 Playoffs',
    'default_sort': '',
    'start_date': '1998-03-14',
    'hide_in_standings': False},
   {'id': '4',
    'name': '1997-98 Regular Season',
    'default_sort': '',
    'start_date': '1997-09-17',
    'hide_in_standings': False}],
  'conferences': [{'conference_id': '1',
    'conference_name': 'Eastern Conference'},
   {'conference_id': '2', 'conference_name': 'Western Conference'}],
  'conferencesAll': [{'conference_id': -1,
    'conference_name': 'All Conferences'},
   {'conference_id': '1', 'conference_name': 'Eastern Conference'},
   {'conference_id': '2', 'conference_name': 'Western Conference'}],
  'divisions': [{'id': '1', 'name': 'East Division', 'conference_id': '1'},
   {'id': '2', 'name': 'Central Division', 'conference_id': '1'},
   {'id': '4', 'name': 'Midwest Division', 'conference_id': '2'},
   {'id': '3', 'name': 'West Division', 'conference_id': '2'}],
  'divisionsAll': [{'id': -1, 'name': 'All Divisions', 'conference_id': None},
   {'id': '1', 'name': 'East Division', 'conference_id': '1'},
   {'id': '2', 'name': 'Central Division', 'conference_id': '1'},
   {'id': '4', 'name': 'Midwest Division', 'conference_id': '2'},
   {'id': '3', 'name': 'West Division', 'conference_id': '2'}],
  'first_season_year': '1997',
  'regularSeasons': [{'id': '83', 'name': '2025-26 Regular Season'},
   {'id': '79', 'name': '2024-25 Regular Season'},
   {'id': '76', 'name': '2023-24 Regular Season'},
   {'id': '73', 'name': '2022-23 Regular Season'},
   {'id': '70', 'name': '2021-22 Regular Season'},
   {'id': '68', 'name': '2019-20 Regular Season'},
   {'id': '63', 'name': '2018-19 Regular Season'},
   {'id': '60', 'name': '2017-18 Regular Season'},
   {'id': '56', 'name': '2016-17 Regular Season'},
   {'id': '54', 'name': '2015-16 Regular Season'},
   {'id': '51', 'name': '2014-15 Regular Season'},
   {'id': '49', 'name': '2013-14 Regular Season'},
   {'id': '46', 'name': '2012-13 Regular Season'},
   {'id': '44', 'name': '2011-12 Regular Season'},
   {'id': '42', 'name': '2010-11 Regular Season'},
   {'id': '38', 'name': '2009-10 Regular Season'},
   {'id': '35', 'name': '2008-09 Regular Season'},
   {'id': '32', 'name': '2007-08 Regular Season'},
   {'id': '29', 'name': '2006-07 Regular Season'},
   {'id': '26', 'name': '2005-06 Regular Season'},
   {'id': '24', 'name': '2004-05 Regular Season'},
   {'id': '21', 'name': '2003-04 Regular Season'},
   {'id': '17', 'name': '2002-03 Regular Season'},
   {'id': '14', 'name': '2001-02 Regular Season'},
   {'id': '11', 'name': '2000-01 Regular Season'},
   {'id': '9', 'name': '1999-2000 Regular Season'},
   {'id': '6', 'name': '1998-99 Regular Season'},
   {'id': '4', 'name': '1997-98 Regular Season'}],
  'playoffSeasons': [{'id': '81', 'name': '2025 Playoffs'},
   {'id': '77', 'name': '2024 Playoffs'},
   {'id': '74', 'name': '2023 Playoffs'},
   {'id': '71', 'name': '2022 Playoffs'},
   {'id': '66', 'name': '2019 Playoffs'},
   {'id': '61', 'name': '2018 Playoffs'},
   {'id': '58', 'name': '2017 Playoffs'},
   {'id': '55', 'name': '2016 Playoffs'},
   {'id': '52', 'name': '2015 Playoffs'},
   {'id': '50', 'name': '2014 Playoffs'},
   {'id': '48', 'name': '2013 Playoffs'},
   {'id': '45', 'name': '2012 Playoffs'},
   {'id': '43', 'name': '2011 Playoffs'},
   {'id': '41', 'name': '2010 Playoffs'},
   {'id': '37', 'name': '2009 Playoffs'},
   {'id': '34', 'name': '2008 Playoffs'},
   {'id': '31', 'name': '2007 Playoffs'},
   {'id': '28', 'name': '2006 Playoffs'},
   {'id': '25', 'name': '2005 Playoffs'},
   {'id': '23', 'name': '2004 Playoffs'},
   {'id': '20', 'name': '2003 Playoffs'},
   {'id': '15', 'name': '2002 Playoffs'},
   {'id': '12', 'name': '2001 Playoffs'},
   {'id': '10', 'name': '2000 Playoffs'},
   {'id': '7', 'name': '1999 Playoffs'},
   {'id': '5', 'name': '1998 Playoffs'}],
  'teams': [{'id': -1, 'name': 'All Teams'},
   {'id': '7',
    'name': 'Barrie Colts',
    'nickname': 'Colts',
    'team_code': 'BAR',
    'division_id': '2',
    'logo': 'https://assets.leaguestat.com/ohl/logos/50x50/7.png'},
   {'id': '18',
    'name': 'Brampton Steelheads',
    'nickname': 'Steelheads',
    'team_code': 'BRAM',
    'division_id': '2',
    'logo': 'https://assets.leaguestat.com/ohl/logos/50x50/18.png'},
   {'id': '1',
    'name': 'Brantford Bulldogs',
    'nickname': 'Bulldogs',
    'team_code': 'BFD',
    'division_id': '1',
    'logo': 'https://assets.leaguestat.com/ohl/logos/1.png'},
   {'id': '8',
    'name': 'Erie Otters',
    'nickname': 'Otters',
    'team_code': 'ER',
    'division_id': '4',
    'logo': 'https://assets.leaguestat.com/ohl/logos/8.png'},
   {'id': '13',
    'name': 'Flint Firebirds',
    'nickname': 'Firebirds',
    'team_code': 'FLNT',
    'division_id': '3',
    'logo': 'https://assets.leaguestat.com/ohl/logos/13.png'},
   {'id': '9',
    'name': 'Guelph Storm',
    'nickname': 'Storm',
    'team_code': 'GUE',
    'division_id': '4',
    'logo': 'https://assets.leaguestat.com/ohl/logos/9.png'},
   {'id': '2',
    'name': 'Kingston Frontenacs',
    'nickname': 'Frontenacs',
    'team_code': 'KGN',
    'division_id': '1',
    'logo': 'https://assets.leaguestat.com/ohl/logos/50x50/2.png'},
   {'id': '10',
    'name': 'Kitchener Rangers',
    'nickname': 'Rangers',
    'team_code': 'KIT',
    'division_id': '4',
    'logo': 'https://assets.leaguestat.com/ohl/logos/10.png'},
   {'id': '14',
    'name': 'London Knights',
    'nickname': 'Knights',
    'team_code': 'LDN',
    'division_id': '4',
    'logo': 'https://assets.leaguestat.com/ohl/logos/14.png'},
   {'id': '20',
    'name': 'Niagara IceDogs',
    'nickname': 'IceDogs',
    'team_code': 'NIAG',
    'division_id': '2',
    'logo': 'https://assets.leaguestat.com/ohl/logos/20.png'},
   {'id': '19',
    'name': 'North Bay Battalion',
    'nickname': 'Battalion',
    'team_code': 'NB',
    'division_id': '2',
    'logo': 'https://assets.leaguestat.com/ohl/logos/19.png'},
   {'id': '4',
    'name': 'Oshawa Generals',
    'nickname': 'Generals',
    'team_code': 'OSH',
    'division_id': '1',
    'logo': 'https://assets.leaguestat.com/ohl/logos/4.png'},
   {'id': '5',
    'name': "Ottawa 67's",
    'nickname': "67's",
    'team_code': 'OTT',
    'division_id': '1',
    'logo': 'https://assets.leaguestat.com/ohl/logos/5.png'},
   {'id': '11',
    'name': 'Owen Sound Attack',
    'nickname': 'Attack',
    'team_code': 'OS',
    'division_id': '4',
    'logo': 'https://assets.leaguestat.com/ohl/logos/11.png'},
   {'id': '6',
    'name': 'Peterborough Petes',
    'nickname': 'Petes',
    'team_code': 'PBO',
    'division_id': '1',
    'logo': 'https://assets.leaguestat.com/ohl/logos/6.png'},
   {'id': '34',
    'name': 'Saginaw Spirit',
    'nickname': 'Spirit',
    'team_code': 'SAG',
    'division_id': '3',
    'logo': 'https://assets.leaguestat.com/ohl/logos/34.png'},
   {'id': '15',
    'name': 'Sarnia Sting',
    'nickname': 'Sting',
    'team_code': 'SAR',
    'division_id': '3',
    'logo': 'https://assets.leaguestat.com/ohl/logos/15.png'},
   {'id': '16',
    'name': 'Soo Greyhounds',
    'nickname': 'Greyhounds',
    'team_code': 'SOO',
    'division_id': '3',
    'logo': 'https://assets.leaguestat.com/ohl/logos/16.png'},
   {'id': '12',
    'name': 'Sudbury Wolves',
    'nickname': 'Wolves',
    'team_code': 'SBY',
    'division_id': '2',
    'logo': 'https://assets.leaguestat.com/ohl/logos/50x50/12.png'},
   {'id': '17',
    'name': 'Windsor Spitfires',
    'nickname': 'Spitfires',
    'team_code': 'WSR',
    'division_id': '3',
    'logo': 'https://assets.leaguestat.com/ohl/logos/17.png'}],
  'teamsNoAll': [{'id': '7',
    'name': 'Barrie Colts',
    'nickname': 'Colts',
    'team_code': 'BAR',
    'division_id': '2',
    'logo': 'https://assets.leaguestat.com/ohl/logos/50x50/7.png'},
   {'id': '18',
    'name': 'Brampton Steelheads',
    'nickname': 'Steelheads',
    'team_code': 'BRAM',
    'division_id': '2',
    'logo': 'https://assets.leaguestat.com/ohl/logos/50x50/18.png'},
   {'id': '1',
    'name': 'Brantford Bulldogs',
    'nickname': 'Bulldogs',
    'team_code': 'BFD',
    'division_id': '1',
    'logo': 'https://assets.leaguestat.com/ohl/logos/1.png'},
   {'id': '8',
    'name': 'Erie Otters',
    'nickname': 'Otters',
    'team_code': 'ER',
    'division_id': '4',
    'logo': 'https://assets.leaguestat.com/ohl/logos/8.png'},
   {'id': '13',
    'name': 'Flint Firebirds',
    'nickname': 'Firebirds',
    'team_code': 'FLNT',
    'division_id': '3',
    'logo': 'https://assets.leaguestat.com/ohl/logos/13.png'},
   {'id': '9',
    'name': 'Guelph Storm',
    'nickname': 'Storm',
    'team_code': 'GUE',
    'division_id': '4',
    'logo': 'https://assets.leaguestat.com/ohl/logos/9.png'},
   {'id': '2',
    'name': 'Kingston Frontenacs',
    'nickname': 'Frontenacs',
    'team_code': 'KGN',
    'division_id': '1',
    'logo': 'https://assets.leaguestat.com/ohl/logos/50x50/2.png'},
   {'id': '10',
    'name': 'Kitchener Rangers',
    'nickname': 'Rangers',
    'team_code': 'KIT',
    'division_id': '4',
    'logo': 'https://assets.leaguestat.com/ohl/logos/10.png'},
   {'id': '14',
    'name': 'London Knights',
    'nickname': 'Knights',
    'team_code': 'LDN',
    'division_id': '4',
    'logo': 'https://assets.leaguestat.com/ohl/logos/14.png'},
   {'id': '20',
    'name': 'Niagara IceDogs',
    'nickname': 'IceDogs',
    'team_code': 'NIAG',
    'division_id': '2',
    'logo': 'https://assets.leaguestat.com/ohl/logos/20.png'},
   {'id': '19',
    'name': 'North Bay Battalion',
    'nickname': 'Battalion',
    'team_code': 'NB',
    'division_id': '2',
    'logo': 'https://assets.leaguestat.com/ohl/logos/19.png'},
   {'id': '4',

In [19]:
import json

# save to a file
bs_data_json = json.dumps(bs_data, indent=4)
with open('bootstrap_data.json', 'w') as f:
    f.write(bs_data_json)

In [15]:
pd.json_normalize(scraper.bootstrap_data["seasons"])

    id                       name default_sort  start_date  hide_in_standings
0   84  2025-26 OHL Top Prospects               2026-01-10              False
1   83     2025-26 Regular Season               2025-09-16              False
2   82            2025 Pre-Season               2025-08-13              False
3   81              2025 Playoffs               2025-03-26              False
4   79     2024-25 Regular Season               2024-09-23              False
..  ..                        ...          ...         ...                ...
65   9   1999-2000 Regular Season               1999-09-22              False
66   7              1999 Playoffs               1999-03-20              False
67   6     1998-99 Regular Season               1998-09-24              False
68   5              1998 Playoffs               1998-03-14              False
69   4     1997-98 Regular Season               1997-09-17              False

[70 rows x 5 columns]

In [9]:
# Manually fetch bootstrap with specific parameters
ahl = HockeyScraper('ahl')

# Get bootstrap for a specific season
bootstrap = ahl.bootstrap(season='90', page_name='scorebar')

print(f"Manual bootstrap fetch:")
print(f"  Season ID: {bootstrap['current_season_id']}")
print(f"  Teams: {len(bootstrap['teams'])}")

# Note: NHL doesn't support bootstrap
try:
    nhl = HockeyScraper('nhl')
    nhl_bootstrap = nhl.bootstrap()
except NotImplementedError as e:
    print(f"\nNHL doesn't support bootstrap: {e}")

Manual bootstrap fetch:
  Season ID: 90
  Teams: 33

NHL doesn't support bootstrap: Bootstrap endpoint not available for NHL. Use the NHL API directly.

### Manual Bootstrap Method

You can also manually fetch bootstrap with custom parameters:

In [ ]:
# Bootstrap properties provide quick access to common data
pwhl = HockeyScraper('pwhl')

print("Convenience properties:")
print(f"  League ID: {pwhl.current_league_id}")
print(f"  Season ID: {pwhl.current_season_id}")
print(f"  Number of teams: {len(pwhl.teams)}")

# Full bootstrap data is also available
print(f"\nFull bootstrap has {len(pwhl.bootstrap_data)} keys:")
print(f"  Available keys: {list(pwhl.bootstrap_data.keys())[:10]}...")

# Access specific data from bootstrap
divisions = pwhl.bootstrap_data.get('divisions', [])
seasons = pwhl.bootstrap_data.get('regularSeasons', [])
print(f"\n  Divisions: {len(divisions)}")
print(f"  Regular seasons: {len(seasons)}")

### Bootstrap Properties

The scraper provides convenient properties for accessing bootstrap data:

## Understanding the Output

All methods return **pandas DataFrames** - this makes it easy to:
- Filter and sort data
- Export to CSV, Excel, or JSON
- Perform analysis
- Create visualizations

In [181]:
# Example: Filter and sort
stats = scrape('qmjhl', 'stats', season=90, position='skaters', limit=50)

# Get players with more than 20 goals
goal_scorers = stats[stats['G'] > 20].sort_values('G', ascending=False)

print(f"Found {len(goal_scorers)} players with 20+ goals")
display(goal_scorers[['playerName', 'teamCode', 'G', 'A', 'PTS']].head(10))

Found 46 players with 20+ goals

                  playerName teamCode   G   A  PTS
2          Boisclair, Maxime      Chi  70  60  130
0         Radulov, Alexander      Que  61  91  152
13  Picard-Hooper, Alexandre      BaC  57  43  100
5               Aubin, Brent      Que  57  60  117
20          Goulet, Stéphane      Mon  51  42   93
9               Roy, Mathieu      Bat  50  54  104
14          Labelle, Olivier      Bat  50  50  100
1          Lascek, Stanislav      Chi  47  88  135
10            Aubin, Mathieu      Lew  47  56  103
22        Beauregard, Thomas      Bat  46  42   88

In [182]:
stats

,player_id,name,position,rookie,jerseyNumber,teamCode,GP,GWG,G,S,Sh%,A,PTS,PTS/GP,+/-,PIM,PIM/GP,PPG,PPA,SHG,SHA,SG,rank,playerName,lastName,firstName,teamId,teamLogo,season,league,seasonName,seasonStartYear,seasonEndYear
0,9261,"Radulov, Alexander",RW,0,22,Que,62,9,61,332,18.4,91,152,2.45,53,101,1.63,22,44,10,6,4,1,"Radulov, Alexander",Radulov,Alexander,9,https://assets.leaguestat.com/lhjmq/logos/9_90...,90,qmjhl,2005-06 | Regular Season,2005,2006
1,9734,"Lascek, Stanislav",RW,0,17,Chi,64,9,47,344,13.7,88,135,2.11,42,96,1.50,20,55,3,2,3,2,"Lascek, Stanislav",Lascek,Stanislav,10,https://assets.leaguestat.com/lhjmq/logos/10.png,90,qmjhl,2005-06 | Regular Season,2005,2006
2,10615,"Boisclair, Maxime",LW,0,97,Chi,70,12,70,321,21.8,60,130,1.86,39,97,1.39,43,24,3,1,0,3,"Boisclair, Maxime",Boisclair,Maxime,10,https://assets.leaguestat.com/lhjmq/logos/10.png,90,qmjhl,2005-06 | Regular Season,2005,2006
3,9732,"Latendresse, Olivier",C,0,44,VdO,70,6,41,359,11.4,84,125,1.79,5,83,1.19,16,47,4,2,2,4,"Latendresse, Olivier",Latendresse,Olivier,15,https://assets.leaguestat.com/lhjmq/logos/15.png,90,qmjhl,2005-06 | Regular Season,2005,2006
4,10288,"Desharnais, David",C,0,15,Chi,63,6,33,161,20.5,85,118,1.87,45,44,0.70,20,52,2,3,2,5,"Desharnais, David",Desharnais,David,10,https://assets.leaguestat.com/lhjmq/logos/10.png,90,qmjhl,2005-06 | Regular Season,2005,2006
5,10779,"Aubin, Brent",C,0,18,Que,72,10,57,323,17.6,60,117,1.63,17,92,1.28,26,41,1,0,1,6,"Aubin, Brent",Aubin,Brent,9,https://assets.leaguestat.com/lhjmq/logos/9_90...,90,qmjhl,2005-06 | Regular Season,2005,2006
6,10550,"Brassard, Derick",C,0,61,Dru,58,6,44,283,15.5,72,116,2.00,19,92,1.59,23,39,2,4,0,7,"Brassard, Derick",Brassard,Derick,14,https://assets.leaguestat.com/lhjmq/logos/50x5...,90,qmjhl,2005-06 | Regular Season,2005,2006
7,10562,"Bourret, Alex",LW,0,23,Sha,67,10,44,289,15.2,70,114,1.70,11,133,1.99,23,40,5,4,1,8,"Bourret, Alex",Bourret,Alex,13,https://assets.leaguestat.com/lhjmq/logos/13.png,90,qmjhl,2005-06 | Regular Season,2005,2006
8,10199,"Dupuis, Philippe",C,0,9,Mon,56,5,32,277,11.6,76,108,1.93,42,52,0.93,13,53,2,1,1,9,"Dupuis, Philippe",Dupuis,Philippe,1,https://assets.leaguestat.com/lhjmq/logos/1.png,90,qmjhl,2005-06 | Regular Season,2005,2006
9,9180,"Roy, Mathieu",LW,0,15,Bat,65,4,50,348,14.4,54,104,1.60,22,101,1.55,28,35,3,0,2,10,"Roy, Mathieu",Roy,Mathieu,2,https://assets.leaguestat.com/lhjmq/logos/2.png,90,qmjhl,2005-06 | Regular Season,2005,2006
10,10777,"Aubin, Mathieu",C,0,24,Lew,70,6,47,326,14.4,56,103,1.47,10,63,0.90,22,39,4,2,6,11,"Aubin, Mathieu",Aubin,Mathieu,4,https://assets.leaguestat.com/lhjmq/logos/4_90...,90,qmjhl,2005-06 | Regular Season,2005,2006
11,8149,"Giroux, Claude",RW,1,28,Gat,69,4,39,199,19.6,64,103,1.49,30,64,0.93,14,35,4,3,1,12,"Giroux, Claude",Giroux,Claude,12,https://assets.leaguestat.com/lhjmq/logos/50x5...,90,qmjhl,2005-06 | Regular Season,2005,2006
12,10588,"Bouchard, François",LW,0,16,BaC,69,4,33,234,14.1,69,102,1.48,-6,66,0.96,17,42,0,1,0,13,"Bouchard, François",Bouchard,François,16,https://assets.leaguestat.com/lhjmq/logos/16_9...,90,qmjhl,2005-06 | Regular Season,2005,2006
13,9323,"Picard-Hooper, Alexandre",C,0,14,BaC,70,4,57,285,20.0,43,100,1.43,-2,111,1.59,33,18,4,1,1,14,"Picard-Hooper, Alexandre",Picard-Hooper,Alexandre,16,https://assets.leaguestat.com/lhjmq/logos/16_9...,90,qmjhl,2005-06 | Regular Season,2005,2006
14,9828,"Labelle, Olivier",RW,0,91,Bat,67,9,50,290,17.2,50,100,1.49,18,185,2.76,32,23,5,4,0,15,"Labelle, Olivier",Labelle,Olivier,2,https://assets.leaguestat.com/lhjmq/logos/2.png,90,qmjhl,2005-06 | Regular Season,2005,2006
15,10534,"Brine, David",C,0,49,Hal,70,6,34,325,10.5,66,100,1.43,22,80,1.14,13,30,2,2,4,16,"Brine, David",Brine,David,5,https://assets.leaguestat.com/lhjmq/logos/5_90...,90,qmjhl,2005-06 | Regular Season,2005,2006
16,9479,"Mondou, Benoit",C,0,61,Sha,59,3,46,198,23.2,52,98,1.66,18,57,0.97,21,32,6,3,0,17,"Mondou, Benoit",Mondou,Benoit,13,https://assets.leaguestat.com/lhjmq/logos/13.png,90,qmjhl,2005-06 | Regular Season,2005,2006
17,8757,"Esposito, Angelo",C,1,7,Que,57,7,39,200,19.5,59,98,1.72,42,45,0.79,10,25,5,6,0,18,"Esposito, Angelo",Esposito,Angelo,9,https://assets.leaguestat.com/lhjmq/logos/9_90...,90,qmjhl,2005-06 | Regular Season,2005,2006
18,10494,"Carnegie, Rane",RW,0,7,Hal,63,5,44,315,14.0,52,96,1.52,22,65,1.03,12,26,7,3,4,19,"Carnegie, Rane",Carnegie,Rane,5,https://assets.leaguestat.com/lhjmq/logos/5_90...,90,qmjhl,2005-06 | Regular Season,2005,2006
19,8976,"Trukhno, Viatcheslav",LW,0,10,PEI,60,1,28,213,13.1,68,96,1.60,-1,81,1.35,9,44,0,1,3,20,"Trukhno, Viatcheslav",Trukhno,Viatcheslav,7,https://assets.leaguestat.com/lhjmq/logos/7_90...,90,qmjhl,2005-06 | Regular Season,2005,2006
20,10006,"Goulet, Stéphane",LW,0,16,Mon,67,5,51,225,22.7,42,93,1.39,39,80,1.19,30,23,1,1,0,21,"Goulet, Stéphane",Goulet,Stéphane,1,https://assets.leaguestat.com/lhjmq/logos/1.png,90,qmjhl,2005-06 | Regular Season,2005,2006
21,9514,"Mathieu-Girard, Ian",C,0,81,VdO,69,7,31,169,18.3,58,89,1.29,32,40,0.58,10,25,0,3,2,22,"Mathieu-Girard, Ian",Mathieu-Girard,Ian,15,https://assets.leaguestat.com/lhjmq/logos/15.png,90,qmjhl,2005-06 | Regular Season,2005,2006
22,10714,"Beauregard, Thomas",RW,0,28,Bat,69,4,46,273,16.8,42,88,1.28,30,38,0.55,21,19,0,1,4,23,"Beauregard, Thomas",Beauregard,Thomas,2,https://assets.leaguestat.com/lhjmq/logos/2.png,90,qmjhl,2005-06 | Regular Season,2005,2006
23,10782,"Asselin, Kevin",RW,0,22,Cap,67,9,44,296,14.9,44,88,1.31,12,92,1.37,21,22,2,1,3,24,"Asselin, Kevin",Asselin,Kevin,3,https://assets.leaguestat.com/lhjmq/logos/3.png,90,qmjhl,2005-06 | Regular Season,2005,2006
24,8881,"Zagrapan, Marek",C,0,8,Chi,59,3,35,199,17.6,52,87,1.47,16,63,1.07,17,34,0,0,0,25,"Zagrapan, Marek",Zagrapan,Marek,10,https://assets.leaguestat.com/lhjmq/logos/10.png,90,qmjhl,2005-06 | Regular Season,2005,2006
25,10931,"Melanson, Mathieu",RW,0,91,Que,59,6,42,268,15.7,44,86,1.46,26,65,1.10,18,22,4,2,0,26,"Melanson, Mathieu",Melanson,Mathieu,9,https://assets.leaguestat.com/lhjmq/logos/9_90...,90,qmjhl,2005-06 | Regular Season,2005,2006
26,9114,"Sheppard, James",LW,0,15,Cap,66,5,30,205,14.6,54,84,1.27,3,78,1.18,14,31,1,1,1,27,"Sheppard, James",Sheppard,James,3,https://assets.leaguestat.com/lhjmq/logos/3.png,90,qmjhl,2005-06 | Regular Season,2005,2006
27,8890,"Yandle, Keith",D,0,3,Mon,66,3,25,282,8.9,59,84,1.27,50,109,1.65,15,33,0,1,0,28,"Yandle, Keith",Yandle,Keith,1,https://assets.leaguestat.com/lhjmq/logos/1.png,90,qmjhl,2005-06 | Regular Season,2005,2006
28,9733,"Latendresse, Guillaume",RW,0,22,Dru,51,8,43,280,15.4,40,83,1.63,20,105,2.06,16,16,3,3,0,29,"Latendresse, Guillaume",Latendresse,Guillaume,14,https://assets.leaguestat.com/lhjmq/logos/50x5...,90,qmjhl,2005-06 | Regular Season,2005,2006
29,10424,"Cliche, Marc-André",C,0,10,Lew,66,8,37,195,19.0,45,82,1.24,4,60,0.91,22,31,3,2,0,30,"Cliche, Marc-André",Cliche,Marc-André,4,https://assets.leaguestat.com/lhjmq/logos/4_90...,90,qmjhl,2005-06 | Regular Season,2005,2006
30,10299,"Demers, Alexandre",C,0,25,Dru,56,4,32,207,15.5,50,82,1.46,18,109,1.95,17,29,3,0,0,31,"Demers, Alexandre",Demers,Alexandre,14,https://assets.leaguestat.com/lhjmq/logos/50x5...,90,qmjhl,2005-06 | Regular Season,2005,2006
31,9843,"Krejci, David",C,0,44,Gat,55,6,27,241,11.2,54,81,1.47,3,54,0.98,15,35,1,1,2,32,"Krejci, David",Krejci,David,12,https://assets.leaguestat.com/lhjmq/logos/50x5...,90,qmjhl,2005-06 | Regular Season,2005,2006
32,9454,"Munden, Justin",LW,0,20,Rou,69,3,32,223,14.3,48,80,1.16,19,70,1.01,17,20,0,3,1,33,"Munden, Justin",Munden,Justin,11,https://assets.leaguestat.com/lhjmq/logos/50x5...,90,qmjhl,2005-06 | Regular Season,2005,2006
33,9922,"Imbeault, Alexandre",C,0,89,Vic,69,2,29,268,10.8,51,80,1.16,-14,70,1.01,9,30,2,1,2,34,"Imbeault, Alexandre",Imbeault,Alexandre,17,https://assets.leaguestat.com/lhjmq/logos/17.png,90,qmjhl,2005-06 | Regular Season,2005,2006
34,9126,"Sersen, Michal",D,0,8,Que,63,5,22,286,7.7,57,79,1.25,56,76,1.21,15,29,1,3,1,35,"Sersen, Michal",Sersen,Michal,9,https://assets.leaguestat.com/lhjmq/logos/9_90...,90,qmjhl,2005-06 | Regular Season,2005,2006
35,10373,"Coulombe, Patrick",D,0,5,Chi,62,3,23,258,8.9,54,77,1.24,2,40,0.65,11,41,0,0,0,36,"Coulombe, Patrick",Coulombe,Patrick,10,https://assets.leaguestat.com/lhjmq/logos/10.png,90,qmjhl,2005-06 | Regular Season,2005,2006
36,9381,"Paré, Francis",C,0,48,Sha,55,2,26,196,13.3,48,74,1.35,16,66,1.20,12,31,6,3,0,37,"Paré, Francis",Paré,Francis,13,https://assets.leaguestat.com/lhjmq/logos/13.png,90,qmjhl,2005-06 | Regular Season,2005,2006
37,10247,"Doucet, Kyle",RW,0,21,Rou,70,1,19,157,12.1,55,74,1.06,16,78,1.11,4,33,5,2,0,38,"Doucet, Kyle",Doucet,Kyle,11,https://assets.leaguestat.com/lhjmq/logos/50x5...,90,qmjhl,2005-06 | Regular Season,2005,2006
38,9824,"Labrecque, Guillaume",RW,0,81,Sha,66,3,28,212,13.2,45,73,1.11,12,75,1.14,11,23,2,2,1,39,"Labrecque, Guillaume",Labrecque,Guillaume,13,https://assets.leaguestat.com/lhjmq/logos/13.png,90,qmjhl,2005-06 | Regular Season,2005,2006
39,8930,"Vlasic, Marc-Edouard",D,0,44,Que,66,2,16,191,8.4,57,73,1.11,41,57,0.86,8,39,1,1,0,40,"Vlasic, Marc-Edouard",Vlasic,Marc-Edouard,9,https://assets.leaguestat.com/lhjmq/logos/9_90...,90,qmjhl,2005-06 | Regular Season,2005,2006
40,9461,"Morrison, Brett",C,0,10,Gat,64,4,33,154,21.4,39,72,1.13,7,53,0.83,14,20,3,2,1,41,"Morrison, Brett",Morrison,Brett,12,https://assets.leaguestat.com/lhjmq/logos/50x5...,90,qmjhl,2005-06 | Regular Season,2005,2006
41,10640,"Bisaillon, Sébastien",D,0,21,VdO,63,1,35,241,14.5,36,71,1.13,-27,56,0.89,33,22,0,2,1,42,"Bisaillon, Sébastien",Bisaillon,Sébastien,15,https://assets.leaguestat.com/lhjmq/logos/15.png,90,qmjhl,2005-06 | Regular Season,2005,2006
42,10003,"Gragnani, Marc-André",D,0,52,PEI,62,1,16,149,10.7,55,71,1.15,-23,75,1.21,10,43,0,1,2,43,"Gragnani, Marc-André",Gragnani,Marc-André,7,https://assets.leaguestat.com/lhjmq/logos/7_90...,90,qmjhl,2005-06 | Regular Season,2005,2006
43,10489,"Carpentier, Hugo",C,0,28,Rou,70,4,31,138,22.5,39,70,1.00,7,64,0.91,15,16,1,0,1,44,"Carpentier, Hugo",Carpentier,Hugo,11,https://assets.leaguestat.com/lhjmq/logos/50x5...,90,qmjhl,2005-06 | Regular Season,2005,2006
44,9306,"Pohl, Petr",RW,0,55,Bat,62,4,27,208,13.0,43,70,1.13,12,44,0.71,11,27,1,1,1,45,"Pohl, Petr",Pohl,Petr,2,https://assets.leaguestat.com/lhjmq/logos/2.png,90,qmjhl,2005-06 | Regular Season,2005,2006
45,10496,"Carle, Mathieu",D,0,77,Bat,67,2,18,206,8.7,51,69,1.03,20,122,1.82,8,35,3,2,0,46,"Carle, Mathieu",Carle,Mathieu,2,https://assets.leaguestat.com/lhjmq/logos/2.png,90,qmjhl,2005-06 | Regular Season,2005,2006
46,10249,"Doucet, Benoît",C,0,43,Vic,66,2,37,201,18.4,31,68,1.03,-23,68,1.03,17,18,2,1,0,47,"Doucet, Benoît",Doucet,Benoît,17,https://assets.leaguestat.com/lhjmq/logos/17.png,90,qmjhl,2005-06 | Regular Season,2005,2006
47,10546,"Breault, Benjamin",C,0,36,BaC,68,7,30,259,11.6,38,68,1.00,-20,60,0.88,13,16,4,2,0,48,"Breault, Benjamin",Breault,Benjamin,16,https://assets.leaguestat.com/lhjmq/logos/16_9...,90,qmjhl,2005-06 | Regular Season,2005,2006
48,9650,"Letang, Kristopher",D,0,58,VdO,60,2,25,289,8.7,43,68,1.13,4,156,2.60,13,32,1,2,1,49,"Letang, Kristopher",Letang,Kristopher,15,https://assets.leaguestat.com/lhjmq/logos/15.png,90,qmjhl,2005-06 | Regular Season,2005,2006
49,9049,"Stewart, Danny",C,0,74,PEI,58,3,29,196,14.8,38,67,1.16,-10,74,1.28,16,21,0,0,0,50,"Stewart, Danny",Stewart,Danny,7,https://assets.leaguestat.com/lhjmq/logos/7_90...,90,qmjhl,2005-06 | Regular Season,2005,2006

In [ ]:
## Next Steps

Now that you understand the basics, check out:

1. **02_nhl_data.ipynb** - Working with NHL data
2. **03_other_leagues.ipynb** - QMJHL, OHL, WHL, AHL examples
3. **04_advanced_features.ipynb** - Caching, rate limiting, transformations

## Summary

- Use `scrape(league, data_type, **kwargs)` for simple queries
- Use `HockeyScraper(league)` for object-oriented approach
- **NEW:** Bootstrap data (teams, seasons, divisions) auto-fetched for non-NHL leagues
- Access bootstrap via `scraper.teams`, `scraper.current_season_id`, etc.
- All methods return pandas DataFrames
- Supported leagues: NHL, PWHL, QMJHL, OHL, WHL, AHL
- Data types: pbp, stats, schedule, roster, standings

## League-Specific Parameters

Each league and data type accepts specific parameters. Here are the most common ones:

### Player Stats
- `season`: Season ID (e.g., 90 for QMJHL 2024-25)
- `position`: 'skaters' or 'goalies'
- `team`: Team ID or 'all'
- `limit`: Number of results to return

### Schedule
- `season`: Season ID
- `team_id`: Team ID (-1 for all teams)
- `month`: Month filter (-1 for all months)

### Play-by-Play
- `game_id`: The game ID to scrape
- `nhlify`: Apply NHL-style transformations (default: True)

### Roster
- `team_id`: Team ID
- `season`: Season ID

### Standings
- `season`: Season ID

## Error Handling

ScraperNHL provides helpful error messages:

In [ ]:
try:
    # This will fail - invalid data type
    data = scrape('qmjhl', 'invalid_type', season=90)
except ValueError as e:
    print(f"Error: {e}")

## Next Steps

Now that you understand the basics, check out:

1. **02_nhl_data.ipynb** - Working with NHL data
2. **03_other_leagues.ipynb** - QMJHL, OHL, WHL, AHL examples
3. **04_advanced_features.ipynb** - Caching, rate limiting, transformations

## Summary

- Use `scrape(league, data_type, **kwargs)` for simple queries
- Use `HockeyScraper(league)` for object-oriented approach
- All methods return pandas DataFrames
- Supported leagues: NHL, QMJHL, OHL, WHL, AHL
- Data types: pbp, stats, schedule, roster, standings