# Working with Other Hockey Leagues

This notebook demonstrates how to scrape data from QMJHL, OHL, WHL, and AHL.

All of these leagues use the HockeyTech platform, so they share a consistent API.

## Supported Leagues

- **QMJHL** - Quebec Major Junior Hockey League
- **OHL** - Ontario Hockey League
- **WHL** - Western Hockey League
- **AHL** - American Hockey League

In [ ]:
# %load_ext autoreload
# %autoreload 2

In [2]:
from scrapernhl import scrape, HockeyScraper
import pandas as pd

pd.set_option('display.max_columns', None)

## QMJHL Examples

The Quebec Major Junior Hockey League features teams from Quebec, New Brunswick, and Prince Edward Island.

In [5]:
# Create a QMJHL scraper
qmjhl = HockeyScraper('qmjhl')

# Get top skaters for current season (season 90 = 2024-25)
stats = qmjhl.player_stats(season=90, position='skaters', limit=20)

print(f"Top 20 QMJHL skaters:")
display(stats[['name', "position",'teamCode' ,'GP', 'G', 'A', 'PTS']].head(20))

Top 20 QMJHL skaters:

                        name position teamCode  GP   G   A  PTS
0         Radulov, Alexander       RW      Que  62  61  91  152
1          Lascek, Stanislav       RW      Chi  64  47  88  135
2          Boisclair, Maxime       LW      Chi  70  70  60  130
3       Latendresse, Olivier        C      VdO  70  41  84  125
4          Desharnais, David        C      Chi  63  33  85  118
5               Aubin, Brent        C      Que  72  57  60  117
6           Brassard, Derick        C      Dru  58  44  72  116
7              Bourret, Alex       LW      Sha  67  44  70  114
8           Dupuis, Philippe        C      Mon  56  32  76  108
9               Roy, Mathieu       LW      Bat  65  50  54  104
10            Aubin, Mathieu        C      Lew  70  47  56  103
11            Giroux, Claude       RW      Gat  69  39  64  103
12        Bouchard, François       LW      BaC  69  33  69  102
13  Picard-Hooper, Alexandre        C      BaC  70  57  43  100
14          Labelle, Olivier       RW      Bat  67  50  50  100
15              Brine, David        C      Hal  70  34  66  100
16            Mondou, Benoit        C      Sha  59  46  52   98
17          Esposito, Angelo        C      Que  57  39  59   98
18            Carnegie, Rane       RW      Hal  63  44  52   96
19      Trukhno, Viatcheslav       LW      PEI  60  28  68   96

In [4]:
stats

,player_id,name,position,rookie,jerseyNumber,teamCode,GP,GWG,G,S,Sh%,A,PTS,PTS/GP,+/-,PIM,PIM/GP,PPG,PPA,SHG,SHA,SG,rank,lastName,firstName,playerName,teamId,teamLogo,season,league,seasonName,seasonStartYear,seasonEndYear,scraped_at
0,9261,"Radulov, Alexander",RW,0,22,Que,62,9,61,332,18.4,91,152,2.45,53,101,1.63,22,44,10,6,4,1,Radulov,Alexander,"Radulov, Alexander",9,https://assets.leaguestat.com/lhjmq/logos/9_90...,90,qmjhl,2005-06 | Regular Season,2005,2006,2026-03-06T23:30:29.586209+00:00
1,9734,"Lascek, Stanislav",RW,0,17,Chi,64,9,47,344,13.7,88,135,2.11,42,96,1.50,20,55,3,2,3,2,Lascek,Stanislav,"Lascek, Stanislav",10,https://assets.leaguestat.com/lhjmq/logos/10.png,90,qmjhl,2005-06 | Regular Season,2005,2006,2026-03-06T23:30:29.586209+00:00
2,10615,"Boisclair, Maxime",LW,0,97,Chi,70,12,70,321,21.8,60,130,1.86,39,97,1.39,43,24,3,1,0,3,Boisclair,Maxime,"Boisclair, Maxime",10,https://assets.leaguestat.com/lhjmq/logos/10.png,90,qmjhl,2005-06 | Regular Season,2005,2006,2026-03-06T23:30:29.586209+00:00
3,9732,"Latendresse, Olivier",C,0,44,VdO,70,6,41,359,11.4,84,125,1.79,5,83,1.19,16,47,4,2,2,4,Latendresse,Olivier,"Latendresse, Olivier",15,https://assets.leaguestat.com/lhjmq/logos/15.png,90,qmjhl,2005-06 | Regular Season,2005,2006,2026-03-06T23:30:29.586209+00:00
4,10288,"Desharnais, David",C,0,15,Chi,63,6,33,161,20.5,85,118,1.87,45,44,0.70,20,52,2,3,2,5,Desharnais,David,"Desharnais, David",10,https://assets.leaguestat.com/lhjmq/logos/10.png,90,qmjhl,2005-06 | Regular Season,2005,2006,2026-03-06T23:30:29.586209+00:00
5,10779,"Aubin, Brent",C,0,18,Que,72,10,57,323,17.6,60,117,1.63,17,92,1.28,26,41,1,0,1,6,Aubin,Brent,"Aubin, Brent",9,https://assets.leaguestat.com/lhjmq/logos/9_90...,90,qmjhl,2005-06 | Regular Season,2005,2006,2026-03-06T23:30:29.586209+00:00
6,10550,"Brassard, Derick",C,0,61,Dru,58,6,44,283,15.5,72,116,2.00,19,92,1.59,23,39,2,4,0,7,Brassard,Derick,"Brassard, Derick",14,https://assets.leaguestat.com/lhjmq/logos/50x5...,90,qmjhl,2005-06 | Regular Season,2005,2006,2026-03-06T23:30:29.586209+00:00
7,10562,"Bourret, Alex",LW,0,23,Sha,67,10,44,289,15.2,70,114,1.70,11,133,1.99,23,40,5,4,1,8,Bourret,Alex,"Bourret, Alex",13,https://assets.leaguestat.com/lhjmq/logos/13.png,90,qmjhl,2005-06 | Regular Season,2005,2006,2026-03-06T23:30:29.586209+00:00
8,10199,"Dupuis, Philippe",C,0,9,Mon,56,5,32,277,11.6,76,108,1.93,42,52,0.93,13,53,2,1,1,9,Dupuis,Philippe,"Dupuis, Philippe",1,https://assets.leaguestat.com/lhjmq/logos/1.png,90,qmjhl,2005-06 | Regular Season,2005,2006,2026-03-06T23:30:29.586209+00:00
9,9180,"Roy, Mathieu",LW,0,15,Bat,65,4,50,348,14.4,54,104,1.60,22,101,1.55,28,35,3,0,2,10,Roy,Mathieu,"Roy, Mathieu",2,https://assets.leaguestat.com/lhjmq/logos/2.png,90,qmjhl,2005-06 | Regular Season,2005,2006,2026-03-06T23:30:29.586209+00:00
10,10777,"Aubin, Mathieu",C,0,24,Lew,70,6,47,326,14.4,56,103,1.47,10,63,0.90,22,39,4,2,6,11,Aubin,Mathieu,"Aubin, Mathieu",4,https://assets.leaguestat.com/lhjmq/logos/4_90...,90,qmjhl,2005-06 | Regular Season,2005,2006,2026-03-06T23:30:29.586209+00:00
11,8149,"Giroux, Claude",RW,1,28,Gat,69,4,39,199,19.6,64,103,1.49,30,64,0.93,14,35,4,3,1,12,Giroux,Claude,"Giroux, Claude",12,https://assets.leaguestat.com/lhjmq/logos/50x5...,90,qmjhl,2005-06 | Regular Season,2005,2006,2026-03-06T23:30:29.586209+00:00
12,10588,"Bouchard, François",LW,0,16,BaC,69,4,33,234,14.1,69,102,1.48,-6,66,0.96,17,42,0,1,0,13,Bouchard,François,"Bouchard, François",16,https://assets.leaguestat.com/lhjmq/logos/16_9...,90,qmjhl,2005-06 | Regular Season,2005,2006,2026-03-06T23:30:29.586209+00:00
13,9323,"Picard-Hooper, Alexandre",C,0,14,BaC,70,4,57,285,20.0,43,100,1.43,-2,111,1.59,33,18,4,1,1,14,Picard-Hooper,Alexandre,"Picard-Hooper, Alexandre",16,https://assets.leaguestat.com/lhjmq/logos/16_9...,90,qmjhl,2005-06 | Regular Season,2005,2006,2026-03-06T23:30:29.586209+00:00
14,9828,"Labelle, Olivier",RW,0,91,Bat,67,9,50,290,17.2,50,100,1.49,18,185,2.76,32,23,5,4,0,15,Labelle,Olivier,"Labelle, Olivier",2,https://assets.leaguestat.com/lhjmq/logos/2.png,90,qmjhl,2005-06 | Regular Season,2005,2006,2026-03-06T23:30:29.586209+00:00
15,10534,"Brine, David",C,0,49,Hal,70,6,34,325,10.5,66,100,1.43,22,80,1.14,13,30,2,2,4,16,Brine,David,"Brine, David",5,https://assets.leaguestat.com/lhjmq/logos/5_90...,90,qmjhl,2005-06 | Regular Season,2005,2006,2026-03-06T23:30:29.586209+00:00
16,9479,"Mondou, Benoit",C,0,61,Sha,59,3,46,198,23.2,52,98,1.66,18,57,0.97,21,32,6,3,0,17,Mondou,Benoit,"Mondou, Benoit",13,https://assets.leaguestat.com/lhjmq/logos/13.png,90,qmjhl,2005-06 | Regular Season,2005,2006,2026-03-06T23:30:29.586209+00:00
17,8757,"Esposito, Angelo",C,1,7,Que,57,7,39,200,19.5,59,98,1.72,42,45,0.79,10,25,5,6,0,18,Esposito,Angelo,"Esposito, Angelo",9,https://assets.leaguestat.com/lhjmq/logos/9_90...,90,qmjhl,2005-06 | Regular Season,2005,2006,2026-03-06T23:30:29.586209+00:00
18,10494,"Carnegie, Rane",RW,0,7,Hal,63,5,44,315,14.0,52,96,1.52,22,65,1.03,12,26,7,3,4,19,Carnegie,Rane,"Carnegie, Rane",5,https://assets.leaguestat.com/lhjmq/logos/5_90...,90,qmjhl,2005-06 | Regular Season,2005,2006,2026-03-06T23:30:29.586209+00:00
19,8976,"Trukhno, Viatcheslav",LW,0,10,PEI,60,1,28,213,13.1,68,96,1.60,-1,81,1.35,9,44,0,1,3,20,Trukhno,Viatcheslav,"Trukhno, Viatcheslav",7,https://assets.leaguestat.com/lhjmq/logos/7_90...,90,qmjhl,2005-06 | Regular Season,2005,2006,2026-03-06T23:30:29.586209+00:00

In [9]:
# Get goalie stats
goalies = qmjhl.player_stats(season=90, position='goalies', limit=15)

print("Top 15 QMJHL goalies:")
display(goalies[['name', 'teamCode' ,
                 'save_percentage','goals_against','shutouts','wins','losses','ot_losses','shootout_games_played','shootout_losses','shootout_wins','shootout_goals_against','shootout_attempts','shootout_percentage','ties','goals_against_average']].head(15))

Top 15 QMJHL goalies:

,name,teamCode,save_percentage,goals_against,shutouts,wins,losses,ot_losses,shootout_games_played,shootout_losses,shootout_wins,shootout_goals_against,shootout_attempts,shootout_percentage,ties,goals_against_average
0,J. Sniderman,Mon,0.909,27,1,12,1,0,0,0,0,0,0,0.000,0,1.97
1,O. Pavelec,Cap,0.929,108,3,27,14,2,3,2,1,4,11,0.636,0,2.51
2,S. Michaud,Chi,0.906,107,4,30,9,1,4,2,2,5,15,0.667,0,2.53
3,A. Vincent,Chi,0.913,76,2,21,6,1,1,0,1,0,3,1.000,0,2.69
4,J. Bernier,Lew,0.908,146,2,27,19,2,6,5,1,11,27,0.593,0,2.70
5,G. Bouthillette,Bat,0.905,150,2,34,14,1,10,5,5,12,34,0.647,0,2.81
6,O. Laliberté,Gat,0.900,63,0,13,4,0,2,2,0,3,8,0.625,0,2.83
7,K. Desfossés,Que,0.897,66,1,18,6,0,0,0,0,0,0,0.000,0,2.87
8,T. Fullerton,Lew,0.899,49,1,9,4,1,3,3,0,5,9,0.444,0,2.94
9,C. Desjardins,Que,0.906,111,5,28,8,1,4,1,3,3,11,0.727,0,2.95
10,J. Tordjman,Mon,0.908,161,4,31,21,1,3,1,2,3,16,0.813,0,3.00
11,V. Vanasse,BaC,0.882,2,0,0,0,0,0,0,0,0,0,0.000,0,3.00
12,D. Tremblay,Gat,0.901,148,4,27,19,4,6,1,5,3,19,0.842,0,3.05
13,M. Côté,Dru,0.914,3,0,0,1,0,0,0,0,0,0,0.000,0,3.06
14,G. Blouin,Mon,0.876,43,1,9,6,0,0,0,0,0,0,0.000,0,3.08

In [7]:
goalies

,player_id,shortname,rookie,jerseyNumber,teamCode,GP,minutes_played,S,save_percentage,goals_against,shutouts,wins,losses,ot_losses,shootout_games_played,shootout_losses,shootout_wins,shootout_goals_against,shootout_attempts,shootout_percentage,ties,goals_against_average,rank,name,firstName,lastName,playerName,teamId,teamLogo,season,league,seasonName,seasonStartYear,seasonEndYear,scraped_at
0,6943,J. Sniderman,1,35,Mon,17,823:34,297,0.909,27,1,12,1,0,0,0,0,0,0,0.000,0,1.97,1,J. Sniderman,J.,Sniderman,J. Sniderman,1,https://assets.leaguestat.com/lhjmq/logos/1.png,90,qmjhl,2005-06 | Regular Season,2005,2006,2026-03-06T23:36:32.756229+00:00
1,8076,O. Pavelec,1,1,Cap,47,2578:25,1515,0.929,108,3,27,14,2,3,2,1,4,11,0.636,0,2.51,2,O. Pavelec,O.,Pavelec,O. Pavelec,3,https://assets.leaguestat.com/lhjmq/logos/3.png,90,qmjhl,2005-06 | Regular Season,2005,2006,2026-03-06T23:36:32.756229+00:00
2,10947,S. Michaud,0,33,Chi,46,2532:47,1135,0.906,107,4,30,9,1,4,2,2,5,15,0.667,0,2.53,3,S. Michaud,S.,Michaud,S. Michaud,10,https://assets.leaguestat.com/lhjmq/logos/10.png,90,qmjhl,2005-06 | Regular Season,2005,2006,2026-03-06T23:36:32.756229+00:00
3,8933,A. Vincent,0,35,Chi,31,1694:34,877,0.913,76,2,21,6,1,1,0,1,0,3,1.000,0,2.69,4,A. Vincent,A.,Vincent,A. Vincent,10,https://assets.leaguestat.com/lhjmq/logos/10.png,90,qmjhl,2005-06 | Regular Season,2005,2006,2026-03-06T23:36:32.756229+00:00
4,10668,J. Bernier,0,1,Lew,54,3240:39,1586,0.908,146,2,27,19,2,6,5,1,11,27,0.593,0,2.70,5,J. Bernier,J.,Bernier,J. Bernier,4,https://assets.leaguestat.com/lhjmq/logos/4_90...,90,qmjhl,2005-06 | Regular Season,2005,2006,2026-03-06T23:36:32.756229+00:00
5,10560,G. Bouthillette,0,35,Bat,57,3207:26,1576,0.905,150,2,34,14,1,10,5,5,12,34,0.647,0,2.81,6,G. Bouthillette,G.,Bouthillette,G. Bouthillette,2,https://assets.leaguestat.com/lhjmq/logos/2.png,90,qmjhl,2005-06 | Regular Season,2005,2006,2026-03-06T23:36:32.756229+00:00
6,9780,O. Laliberté,0,30,Gat,28,1334:25,630,0.900,63,0,13,4,0,2,2,0,3,8,0.625,0,2.83,7,O. Laliberté,O.,Laliberté,O. Laliberté,12,https://assets.leaguestat.com/lhjmq/logos/50x5...,90,qmjhl,2005-06 | Regular Season,2005,2006,2026-03-06T23:36:32.756229+00:00
7,10289,K. Desfossés,1,35,Que,27,1379:35,640,0.897,66,1,18,6,0,0,0,0,0,0,0.000,0,2.87,8,K. Desfossés,K.,Desfossés,K. Desfossés,9,https://assets.leaguestat.com/lhjmq/logos/9_90...,90,qmjhl,2005-06 | Regular Season,2005,2006,2026-03-06T23:36:32.756229+00:00
8,10108,T. Fullerton,1,37,Lew,17,1000:12,484,0.899,49,1,9,4,1,3,3,0,5,9,0.444,0,2.94,9,T. Fullerton,T.,Fullerton,T. Fullerton,4,https://assets.leaguestat.com/lhjmq/logos/4_90...,90,qmjhl,2005-06 | Regular Season,2005,2006,2026-03-06T23:36:32.756229+00:00
9,10286,C. Desjardins,0,30,Que,41,2254:26,1180,0.906,111,5,28,8,1,4,1,3,3,11,0.727,0,2.95,10,C. Desjardins,C.,Desjardins,C. Desjardins,9,https://assets.leaguestat.com/lhjmq/logos/9_90...,90,qmjhl,2005-06 | Regular Season,2005,2006,2026-03-06T23:36:32.756229+00:00
10,9003,J. Tordjman,0,39,Mon,56,3219:03,1746,0.908,161,4,31,21,1,3,1,2,3,16,0.813,0,3.00,11,J. Tordjman,J.,Tordjman,J. Tordjman,1,https://assets.leaguestat.com/lhjmq/logos/1.png,90,qmjhl,2005-06 | Regular Season,2005,2006,2026-03-06T23:36:32.756229+00:00
11,8481,V. Vanasse,1,35,BaC,2,40:00,17,0.882,2,0,0,0,0,0,0,0,0,0,0.000,0,3.00,12,V. Vanasse,V.,Vanasse,V. Vanasse,16,https://assets.leaguestat.com/lhjmq/logos/16_9...,90,qmjhl,2005-06 | Regular Season,2005,2006,2026-03-06T23:36:32.756229+00:00
12,8999,D. Tremblay,0,31,Gat,53,2916:12,1493,0.901,148,4,27,19,4,6,1,5,3,19,0.842,0,3.05,13,D. Tremblay,D.,Tremblay,D. Tremblay,12,https://assets.leaguestat.com/lhjmq/logos/50x5...,90,qmjhl,2005-06 | Regular Season,2005,2006,2026-03-06T23:36:32.756229+00:00
13,8819,M. Côté,1,31,Dru,2,58:50,35,0.914,3,0,0,1,0,0,0,0,0,0,0.000,0,3.06,14,M. Côté,M.,Côté,M. Côté,14,https://assets.leaguestat.com/lhjmq/logos/50x5...,90,qmjhl,2005-06 | Regular Season,2005,2006,2026-03-06T23:36:32.756229+00:00
14,10626,G. Blouin,0,30,Mon,15,837:11,347,0.876,43,1,9,6,0,0,0,0,0,0,0.000,0,3.08,15,G. Blouin,G.,Blouin,G. Blouin,1,https://assets.leaguestat.com/lhjmq/logos/1.png,90,qmjhl,2005-06 | Regular Season,2005,2006,2026-03-06T23:36:32.756229+00:00

In [10]:
# Get play-by-play for a game
# Note: Replace with an actual game ID from the current season
game_id = 31171  # Example game ID

try:
    pbp = qmjhl.play_by_play(game_id=game_id, nhlify=True)
    print(f"Total events: {len(pbp)}")
    display(pbp.head(15))
except Exception as e:
    print(f"Error getting play-by-play: {e}")
    print("Try a different game_id from the current season")

Error getting play-by-play: nhlify_goals failed: 1 goal(s) could not be merged with their preceding shot (shot+goal pairs still present at the same time). The data format for this game may be incompatible with automatic merging. Re-scrape with nhlify=False to get the raw event rows.
Try a different game_id from the current season

## OHL Examples

The Ontario Hockey League is one of the three major junior hockey leagues in Canada.

In [12]:
# Create an OHL scraper
ohl = HockeyScraper('ohl')

# Get player stats (season 83 = 2024-25)
stats = ohl.player_stats(season=83, position='skaters', limit=25)

print("Top 25 OHL skaters:")
display(stats[['name', "position",'teamCode' ,'GP', 'G', 'A', 'PTS']].head(25))

Top 25 OHL skaters:

                   name position teamCode  GP   G   A  PTS
0         Nikita Klepov       RW      SAG  60  35  52   87
1       Nathan Aspinall       LW     FLNT  58  29  54   83
2         Cole Beaudoin        C      BAR  48  29  53   82
3          Jack Pridham       RW      KIT  59  39  42   81
4         Dylan Edwards       LW      KIT  61  37  44   81
5   Christian Humphreys       LW      KIT  58  26  55   81
6        Egor Barabanov        C      SAG  61  26  55   81
7         Kieron Walton       LW      PBO  55  37  43   80
8         Marco Mignosa       RW      SOO  58  31  49   80
9          Jake O'Brien        C      BFD  46  24  55   79
10      Riley Patterson        C     NIAG  53  36  40   76
11       Caleb Malhotra        C      BFD  59  26  50   76
12       Marek Vanacker       LW      BFD  53  42  30   72
13             Kevin He       LW     FLNT  53  34  33   67
14        Cooper Dennis       RW      BFD  60  32  35   67
15       Dimian Zhilkin       LW      SAG  52  33  33   66
16           Adam Benak        C      BFD  40  24  42   66
17       Jimmy Lombardi        C     FLNT  58  31  33   64
18    Kashawn Aitcheson        D      BAR  50  27  37   64
19         Pierce Mbuyi       LW       OS  60  29  34   63
20          Michael Dec       RW       ER  59  26  37   63
21    Nathan Villeneuve        C      WSR  49  21  42   63
22       Liam Greentree       LW      WSR  44  33  28   61
23         Adam Novotný       LW      PBO  52  31  30   61
24       Carson Woodall        D      WSR  60  11  49   60

In [16]:
# Get standings
standings = ohl.standings(season=83)

print("OHL Standings:")
display(standings[['team_code', 'wins', 'losses', 'points']].head())

OHL Standings:

  team_code wins losses points
0       BFD   42      9     93
1       OTT   41     14     87
2       PBO   35     22     74
3       KGN   27     28     59
4       OSH   17     40     37

In [15]:
standings

,team_code,wins,losses,ot_losses,ot_wins,shootout_wins,shootout_losses,regulation_wins,row,points,penalty_minutes,streak,goals_for,goals_against,goals_diff,percentage,overall_rank,games_played,rank,past_10,name,prefixTeam,season,league,seasonName,seasonStartYear,seasonEndYear,teamId,teamName,teamLogo,scraped_at
0,BFD,42,9,7,1,2,2,39,40,93,647,3-0-1-0,264,169,95,0.775,1,60,1,8-1-1-0,x - Brantford Bulldogs,x,83,ohl,2025-26 Regular Season,2025,2026,1,Brantford Bulldogs,https://assets.leaguestat.com/ohl/logos/1.png,2026-03-06T23:40:14.146533+00:00
1,OTT,41,14,2,3,3,3,35,38,87,597,2-0-1-1,229,146,83,0.725,4,60,2,4-4-1-1,x - Ottawa 67's,x,83,ohl,2025-26 Regular Season,2025,2026,5,Ottawa 67's,https://assets.leaguestat.com/ohl/logos/5.png,2026-03-06T23:40:14.146533+00:00
2,PBO,35,22,1,6,2,3,27,33,74,775,2-0-0-0,206,209,-3,0.607,9,61,3,6-3-0-1,x - Peterborough Petes,x,83,ohl,2025-26 Regular Season,2025,2026,6,Peterborough Petes,https://assets.leaguestat.com/ohl/logos/6.png,2026-03-06T23:40:14.146533+00:00
3,KGN,27,28,3,1,2,2,24,25,59,480,0-1-0-0,190,189,1,0.492,12,60,4,3-6-1-0,x - Kingston Frontenacs,x,83,ohl,2025-26 Regular Season,2025,2026,2,Kingston Frontenacs,https://assets.leaguestat.com/ohl/logos/50x50/...,2026-03-06T23:40:14.146533+00:00
4,OSH,17,40,2,5,0,1,12,17,37,606,2-0-0-0,153,236,-83,0.308,20,60,5,5-5-0-0,Oshawa Generals,None,83,ohl,2025-26 Regular Season,2025,2026,4,Oshawa Generals,https://assets.leaguestat.com/ohl/logos/4.png,2026-03-06T23:40:14.146533+00:00
5,BAR,42,13,2,5,6,4,31,36,90,813,0-1-0-0,220,170,50,0.738,3,61,1,8-2-0-0,xy - Barrie Colts,xy,83,ohl,2025-26 Regular Season,2025,2026,7,Barrie Colts,https://assets.leaguestat.com/ohl/logos/50x50/...,2026-03-06T23:40:14.146533+00:00
6,NB,34,24,2,4,5,1,25,29,71,656,0-1-0-0,210,195,15,0.582,10,61,2,8-2-0-0,x - North Bay Battalion,x,83,ohl,2025-26 Regular Season,2025,2026,19,North Bay Battalion,https://assets.leaguestat.com/ohl/logos/19.png,2026-03-06T23:40:14.146533+00:00
7,NIAG,29,25,4,8,3,2,18,26,64,708,0-1-0-1,187,222,-35,0.533,11,60,3,4-5-0-1,x - Niagara IceDogs,x,83,ohl,2025-26 Regular Season,2025,2026,20,Niagara IceDogs,https://assets.leaguestat.com/ohl/logos/20.png,2026-03-06T23:40:14.146533+00:00
8,SBY,24,34,2,4,1,0,19,23,50,607,1-0-0-0,190,232,-42,0.417,16,60,4,5-5-0-0,Sudbury Wolves,None,83,ohl,2025-26 Regular Season,2025,2026,12,Sudbury Wolves,https://assets.leaguestat.com/ohl/logos/50x50/...,2026-03-06T23:40:14.146533+00:00
9,BRAM,15,35,6,0,1,3,14,14,39,758,0-9-2-1,143,219,-76,0.331,19,59,5,0-8-1-1,Brampton Steelheads,None,83,ohl,2025-26 Regular Season,2025,2026,18,Brampton Steelheads,https://assets.leaguestat.com/ohl/logos/50x50/...,2026-03-06T23:40:14.146533+00:00
10,KIT,43,12,4,5,1,2,37,42,92,739,9-0-0-1,233,157,76,0.754,2,61,1,9-0-0-1,xy - Kitchener Rangers,xy,83,ohl,2025-26 Regular Season,2025,2026,10,Kitchener Rangers,https://assets.leaguestat.com/ohl/logos/10.png,2026-03-06T23:40:14.146533+00:00
11,LDN,35,21,4,8,3,1,24,32,75,686,1-0-0-0,210,184,26,0.615,8,61,2,5-5-0-0,x - London Knights,x,83,ohl,2025-26 Regular Season,2025,2026,14,London Knights,https://assets.leaguestat.com/ohl/logos/14.png,2026-03-06T23:40:14.146533+00:00
12,GUE,26,29,2,2,2,3,22,24,57,570,0-3-0-1,201,235,-34,0.475,13,60,3,4-5-0-1,Guelph Storm,None,83,ohl,2025-26 Regular Season,2025,2026,9,Guelph Storm,https://assets.leaguestat.com/ohl/logos/9.png,2026-03-06T23:40:14.146533+00:00
13,OS,23,29,3,2,2,5,19,21,54,832,3-0-1-1,215,245,-30,0.450,14,60,4,3-4-1-2,Owen Sound Attack,None,83,ohl,2025-26 Regular Season,2025,2026,11,Owen Sound Attack,https://assets.leaguestat.com/ohl/logos/11.png,2026-03-06T23:40:14.146533+00:00
14,ER,17,35,3,1,2,4,14,15,41,754,0-3-1-2,154,238,-84,0.347,18,59,5,2-5-1-2,Erie Otters,None,83,ohl,2025-26 Regular Season,2025,2026,8,Erie Otters,https://assets.leaguestat.com/ohl/logos/8.png,2026-03-06T23:40:14.146533+00:00
15,WSR,39,14,5,3,3,2,33,36,85,752,3-0-0-0,228,151,77,0.708,5,60,1,7-3-0-0,x - Windsor Spitfires,x,83,ohl,2025-26 Regular Season,2025,2026,17,Windsor Spitfires,https://assets.leaguestat.com/ohl/logos/17.png,2026-03-06T23:40:14.146533+00:00
16,FLNT,39,15,4,2,3,3,34,36,85,603,0-1-0-1,234,179,55,0.697,6,61,2,5-3-1-1,x - Flint Firebirds,x,83,ohl,2025-26 Regular Season,2025,2026,13,Flint Firebirds,https://assets.leaguestat.com/ohl/logos/13.png,2026-03-06T23:40:14.146533+00:00
17,SOO,36,18,1,3,5,5,28,31,78,632,1-0-0-0,232,180,52,0.650,7,60,3,6-2-0-2,x - Soo Greyhounds,x,83,ohl,2025-26 Regular Season,2025,2026,16,Soo Greyhounds,https://assets.leaguestat.com/ohl/logos/16.png,2026-03-06T23:40:14.146533+00:00
18,SAG,23,31,3,2,2,4,19,21,53,773,2-0-0-0,204,262,-58,0.434,15,61,4,5-5-0-0,Saginaw Spirit,None,83,ohl,2025-26 Regular Season,2025,2026,34,Saginaw Spirit,https://assets.leaguestat.com/ohl/logos/34.png,2026-03-06T23:40:14.146533+00:00
19,SAR,18,35,7,3,3,1,12,15,44,759,0-2-1-0,180,259,-79,0.361,17,61,5,3-5-2-0,Sarnia Sting,None,83,ohl,2025-26 Regular Season,2025,2026,15,Sarnia Sting,https://assets.leaguestat.com/ohl/logos/15.png,2026-03-06T23:40:14.146533+00:00

In [20]:
# Get schedule for all teams
schedule = ohl.schedule(season=83, team_id=-1)  # -1 = all teams

print(f"Total games in schedule: {len(schedule)}")
display(schedule[['date', 'homeTeam', 'awayTeam', 'gameStatus']].head(10))

Total games in schedule: 683

        date             homeTeam             awayTeam gameStatus
0 2025-09-18  North Bay Battalion      Oshawa Generals      Final
1 2025-09-18   Peterborough Petes  Brampton Steelheads      Final
2 2025-09-19  Brampton Steelheads      Niagara IceDogs      Final
3 2025-09-19    Kitchener Rangers   Brantford Bulldogs   Final OT
4 2025-09-19       London Knights    Owen Sound Attack   Final OT
5 2025-09-19  Kingston Frontenacs          Ottawa 67's      Final
6 2025-09-19       Sudbury Wolves  North Bay Battalion   Final OT
7 2025-09-19         Sarnia Sting    Windsor Spitfires      Final
8 2025-09-19       Soo Greyhounds       Saginaw Spirit      Final
9 2025-09-19         Guelph Storm          Erie Otters      Final

In [18]:
schedule

,homeId,awayId,gameId,dateString,homeScore,awayScore,gameStatus,homeCity,awayCity,venue,homeTeam,homeCode,homeDivision,homeLogo,awayTeam,awayCode,awayDivision,awayLogo,season,league,seasonName,seasonStartDate,seasonStartYear,seasonEndYear,dayOfWeek,monthText,monthNum,day,year,date,scraped_at
0,19,4,28150,"Thu, Sep 18",4,2,Final,North Bay,Oshawa,Boart Longyear Memorial Gardens,North Bay Battalion,NB,2,https://assets.leaguestat.com/ohl/logos/19.png,Oshawa Generals,OSH,1,https://assets.leaguestat.com/ohl/logos/4.png,83,ohl,2025-26 Regular Season,2025-09-16,2025,2026,Thu,Sep,09,18,2025,2025-09-18,2026-03-06T23:41:36.542639+00:00
1,6,18,28151,"Thu, Sep 18",6,3,Final,Peterborough,Brampton,Peterborough Memorial Centre,Peterborough Petes,PBO,1,https://assets.leaguestat.com/ohl/logos/6.png,Brampton Steelheads,BRAM,2,https://assets.leaguestat.com/ohl/logos/50x50/...,83,ohl,2025-26 Regular Season,2025-09-16,2025,2026,Thu,Sep,09,18,2025,2025-09-18,2026-03-06T23:41:36.542639+00:00
2,18,20,28152,"Fri, Sep 19",4,1,Final,Brampton,Niagara,CAA Centre,Brampton Steelheads,BRAM,2,https://assets.leaguestat.com/ohl/logos/50x50/...,Niagara IceDogs,NIAG,2,https://assets.leaguestat.com/ohl/logos/20.png,83,ohl,2025-26 Regular Season,2025-09-16,2025,2026,Fri,Sep,09,19,2025,2025-09-19,2026-03-06T23:41:36.542639+00:00
3,10,1,28155,"Fri, Sep 19",4,3,Final OT,Kitchener,Brantford,Kitchener Memorial Auditorium,Kitchener Rangers,KIT,4,https://assets.leaguestat.com/ohl/logos/10.png,Brantford Bulldogs,BFD,1,https://assets.leaguestat.com/ohl/logos/1.png,83,ohl,2025-26 Regular Season,2025-09-16,2025,2026,Fri,Sep,09,19,2025,2025-09-19,2026-03-06T23:41:36.542639+00:00
4,14,11,28156,"Fri, Sep 19",2,3,Final OT,London,Owen Sound,Canada Life Place,London Knights,LDN,4,https://assets.leaguestat.com/ohl/logos/14.png,Owen Sound Attack,OS,4,https://assets.leaguestat.com/ohl/logos/11.png,83,ohl,2025-26 Regular Season,2025-09-16,2025,2026,Fri,Sep,09,19,2025,2025-09-19,2026-03-06T23:41:36.542639+00:00
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
678,18,1,28827,"Sun, Mar 22",-,-,2:00 pm,Brampton,Brantford,CAA Centre,Brampton Steelheads,BRAM,2,https://assets.leaguestat.com/ohl/logos/50x50/...,Brantford Bulldogs,BFD,1,https://assets.leaguestat.com/ohl/logos/1.png,83,ohl,2025-26 Regular Season,2025-09-16,2025,2026,Sun,Mar,03,22,2026,2026-03-22,2026-03-06T23:41:36.542639+00:00
679,19,12,28829,"Sun, Mar 22",-,-,2:00 pm,North Bay,Sudbury,Boart Longyear Memorial Gardens,North Bay Battalion,NB,2,https://assets.leaguestat.com/ohl/logos/19.png,Sudbury Wolves,SBY,2,https://assets.leaguestat.com/ohl/logos/50x50/...,83,ohl,2025-26 Regular Season,2025-09-16,2025,2026,Sun,Mar,03,22,2026,2026-03-22,2026-03-06T23:41:36.542639+00:00
680,20,8,28828,"Sun, Mar 22",-,-,2:00 pm,Niagara,Erie,Meridian Centre,Niagara IceDogs,NIAG,2,https://assets.leaguestat.com/ohl/logos/20.png,Erie Otters,ER,4,https://assets.leaguestat.com/ohl/logos/8.png,83,ohl,2025-26 Regular Season,2025-09-16,2025,2026,Sun,Mar,03,22,2026,2026-03-22,2026-03-06T23:41:36.542639+00:00
681,16,17,28831,"Sun, Mar 22",-,-,2:07 pm,Sault Ste. Marie,Windsor,GFL Memorial Gardens,Soo Greyhounds,SOO,3,https://assets.leaguestat.com/ohl/logos/16.png,Windsor Spitfires,WSR,3,https://assets.leaguestat.com/ohl/logos/17.png,83,ohl,2025-26 Regular Season,2025-09-16,2025,2026,Sun,Mar,03,22,2026,2026-03-22,2026-03-06T23:41:36.542639+00:00
682,4,6,28830,"Sun, Mar 22",-,-,6:05 pm,Oshawa,Peterborough,Tribute Communities Centre,Oshawa Generals,OSH,1,https://assets.leaguestat.com/ohl/logos/4.png,Peterborough Petes,PBO,1,https://assets.leaguestat.com/ohl/logos/6.png,83,ohl,2025-26 Regular Season,2025-09-16,2025,2026,Sun,Mar,03,22,2026,2026-03-22,2026-03-06T23:41:36.542639+00:00

## WHL Examples

The Western Hockey League covers teams in Western Canada and the Northwestern United States.

In [24]:
# Functional API example for WHL (season 289 = 2025-26)
stats = scrape('whl', 'stats', season=289, position='skaters', limit=20)

print("Top 20 WHL skaters:")
display(stats[['name', 'position', 'teamCode', 'GP', 'G', 'A', 'PTS']].head(20))

Top 20 WHL skaters:

                 name position teamCode  GP   G   A  PTS
0           Liam Ruck       RW       MH  61  39  54   93
1         Markus Ruck        C       MH  61  18  74   92
2     Cameron Schmidt       RW      SEA  63  43  46   89
3         JP Hurlbert       RW      KAM  60  36  50   86
4     Matias Vanhanen       LW      EVT  54  19  61   80
5         Nathan Behm       LW      KAM  59  34  45   79
6     Jacob Kvasnicka       RW      PEN  58  34  44   78
7           Jonas Woo       LD       MH  50  26  52   78
8       Lukas Sawchyn       RW      EDM  60  22  56   78
9      Bryce Pickford       RD       MH  49  41  35   76
10  Luke Mistelbacher       RW      BDN  59  39  37   76
11   Miroslav Holinka        C      EDM  53  35  41   76
12     Jaxon Jacobson        C      BDN  55  21  55   76
13         Tij Iginla        C      KEL  40  37  38   75
14     Alex Weiermair       RW      POR  57  32  43   75
15        Julien Maze       LW      CGY  61  34  36   70
16   Julius Miettinen        C      EVT  45  30  40   70
17     Terik Parascak       RW       PG  54  28  42   70
18          Kale Dach        C      CGY  56  33  36   69
19        Ryden Evers        C      PEN  60  31  38   69

In [25]:
stats

,player_id,name,position,rookie,jerseyNumber,teamCode,GP,GWG,G,Sh%,A,PTS,PTS/GP,+/-,PIM,PIM/GP,PPG,PPA,SHG,SHA,SG,shootout_attempts,shootout_winning_goals,shootout_percentage,rank,firstName,lastName,playerName,teamId,teamLogo,season,league,seasonName,seasonStartYear,seasonEndYear,scraped_at
0,29383,Liam Ruck,RW,0,12,MH,61,8,39,19.0,54,93,1.52,37,32,0.52,16,22,3,0,1,3,1,33.3,1,Liam,Ruck,Liam Ruck,206,https://assets.leaguestat.com/whl/logos/206.png,289,whl,2025 - 26 Regular Season,2025,2026,2026-03-06T23:50:45.121637+00:00
1,29384,Markus Ruck,C,0,26,MH,61,1,18,15.7,74,92,1.51,36,26,0.43,2,37,0,3,0,2,0,0.0,2,Markus,Ruck,Markus Ruck,206,https://assets.leaguestat.com/whl/logos/206.png,289,whl,2025 - 26 Regular Season,2025,2026,2026-03-06T23:50:45.121637+00:00
2,29235,Cameron Schmidt,RW,0,91,SEA,63,9,43,17.3,46,89,1.41,-8,54,0.86,12,20,2,0,2,4,1,50.0,3,Cameron,Schmidt,Cameron Schmidt,214,https://assets.leaguestat.com/whl/logos/214.png,289,whl,2025 - 26 Regular Season,2025,2026,2026-03-06T23:50:45.121637+00:00
3,30098,JP Hurlbert,RW,1,2,KAM,60,3,36,13.8,50,86,1.43,8,41,0.68,8,19,1,0,1,6,0,16.7,4,JP,Hurlbert,JP Hurlbert,203,https://assets.leaguestat.com/whl/logos/203.png,289,whl,2025 - 26 Regular Season,2025,2026,2026-03-06T23:50:45.121637+00:00
4,30307,Matias Vanhanen,LW,1,37,EVT,54,6,19,14.5,61,80,1.48,56,6,0.11,3,20,0,1,1,2,0,50.0,5,Matias,Vanhanen,Matias Vanhanen,226,https://assets.leaguestat.com/whl/logos/226.png,289,whl,2025 - 26 Regular Season,2025,2026,2026-03-06T23:50:45.121637+00:00
5,29169,Nathan Behm,LW,0,29,KAM,59,4,34,16.0,45,79,1.34,7,31,0.53,5,12,0,0,1,4,0,25.0,6,Nathan,Behm,Nathan Behm,203,https://assets.leaguestat.com/whl/logos/203.png,289,whl,2025 - 26 Regular Season,2025,2026,2026-03-06T23:50:45.121637+00:00
6,30127,Jacob Kvasnicka,RW,1,83,PEN,58,5,34,18.7,44,78,1.34,36,16,0.28,10,8,4,0,0,2,0,0.0,7,Jacob,Kvasnicka,Jacob Kvasnicka,277,https://assets.leaguestat.com/whl/logos/50x50/...,289,whl,2025 - 26 Regular Season,2025,2026,2026-03-06T23:50:45.121637+00:00
7,29025,Jonas Woo,LD,0,18,MH,50,2,26,16.4,52,78,1.56,56,44,0.88,8,18,4,0,0,2,0,0.0,8,Jonas,Woo,Jonas Woo,206,https://assets.leaguestat.com/whl/logos/206.png,289,whl,2025 - 26 Regular Season,2025,2026,2026-03-06T23:50:45.121637+00:00
8,29781,Lukas Sawchyn,RW,0,95,EDM,60,5,22,20.2,56,78,1.30,25,34,0.57,5,14,0,1,1,3,0,33.3,9,Lukas,Sawchyn,Lukas Sawchyn,228,https://assets.leaguestat.com/whl/logos/228.png,289,whl,2025 - 26 Regular Season,2025,2026,2026-03-06T23:50:45.121637+00:00
9,29125,Bryce Pickford,RD,0,27,MH,49,11,41,17.4,35,76,1.55,47,56,1.14,18,11,1,2,0,2,0,0.0,10,Bryce,Pickford,Bryce Pickford,206,https://assets.leaguestat.com/whl/logos/206.png,289,whl,2025 - 26 Regular Season,2025,2026,2026-03-06T23:50:45.121637+00:00
10,28939,Luke Mistelbacher,RW,0,26,BDN,59,3,39,14.3,37,76,1.29,10,27,0.46,7,13,0,0,1,1,1,100.0,11,Luke,Mistelbacher,Luke Mistelbacher,201,https://assets.leaguestat.com/whl/logos/50x50/...,289,whl,2025 - 26 Regular Season,2025,2026,2026-03-06T23:50:45.121637+00:00
11,29709,Miroslav Holinka,C,0,92,EDM,53,10,35,21.6,41,76,1.43,26,24,0.45,5,19,4,0,0,3,0,0.0,12,Miroslav,Holinka,Miroslav Holinka,228,https://assets.leaguestat.com/whl/logos/228.png,289,whl,2025 - 26 Regular Season,2025,2026,2026-03-06T23:50:45.121637+00:00
12,29444,Jaxon Jacobson,C,0,9,BDN,55,4,21,15.1,55,76,1.38,6,30,0.55,7,18,0,0,0,1,0,0.0,13,Jaxon,Jacobson,Jaxon Jacobson,201,https://assets.leaguestat.com/whl/logos/50x50/...,289,whl,2025 - 26 Regular Season,2025,2026,2026-03-06T23:50:45.121637+00:00
13,29008,Tij Iginla,C,0,11,KEL,40,5,37,19.4,38,75,1.88,40,27,0.68,9,11,3,2,0,1,0,0.0,14,Tij,Iginla,Tij Iginla,204,https://assets.leaguestat.com/whl/logos/50x50/...,289,whl,2025 - 26 Regular Season,2025,2026,2026-03-06T23:50:45.121637+00:00
14,29906,Alex Weiermair,RW,0,88,POR,57,4,32,15.4,43,75,1.32,3,28,0.49,10,16,3,3,0,2,0,0.0,15,Alex,Weiermair,Alex Weiermair,208,https://assets.leaguestat.com/whl/logos/50x50/...,289,whl,2025 - 26 Regular Season,2025,2026,2026-03-06T23:50:45.121637+00:00
15,29194,Julien Maze,LW,0,27,CGY,61,4,34,20.0,36,70,1.15,4,58,0.95,9,17,0,0,0,2,0,0.0,16,Julien,Maze,Julien Maze,202,https://assets.leaguestat.com/whl/logos/202.png,289,whl,2025 - 26 Regular Season,2025,2026,2026-03-06T23:50:45.121637+00:00
16,29398,Julius Miettinen,C,0,17,EVT,45,2,30,20.1,40,70,1.56,54,21,0.47,9,8,1,0,0,0,0,0.0,17,Julius,Miettinen,Julius Miettinen,226,https://assets.leaguestat.com/whl/logos/226.png,289,whl,2025 - 26 Regular Season,2025,2026,2026-03-06T23:50:45.121637+00:00
17,29272,Terik Parascak,RW,0,32,PG,54,2,28,13.7,42,70,1.30,7,43,0.80,10,19,2,3,1,2,1,50.0,18,Terik,Parascak,Terik Parascak,210,https://assets.leaguestat.com/whl/logos/210.png,289,whl,2025 - 26 Regular Season,2025,2026,2026-03-06T23:50:45.121637+00:00
18,30196,Kale Dach,C,1,22,CGY,56,8,33,24.3,36,69,1.23,9,20,0.36,11,18,0,1,2,2,0,100.0,19,Kale,Dach,Kale Dach,202,https://assets.leaguestat.com/whl/logos/202.png,289,whl,2025 - 26 Regular Season,2025,2026,2026-03-06T23:50:45.121637+00:00
19,30124,Ryden Evers,C,0,21,PEN,60,7,31,15.2,38,69,1.15,28,12,0.20,10,7,0,1,1,4,1,25.0,20,Ryden,Evers,Ryden Evers,277,https://assets.leaguestat.com/whl/logos/50x50/...,289,whl,2025 - 26 Regular Season,2025,2026,2026-03-06T23:50:45.121637+00:00

In [26]:
# Get WHL standings (season 289 = 2025-26)
standings = scrape('whl', 'standings', season=289)

print("WHL Standings:")
display(standings[['team_code', 'wins', 'losses', 'points']].head())

WHL Standings:

  team_code wins losses points
0        PA   45      9     96
1       BDN   35     24     71
2       SAS   31     25     68
3       REG   23     29     53
4        MJ   21     33     49

## AHL Examples

The American Hockey League is the primary development league for the NHL.

In [27]:
# Create an AHL scraper
ahl = HockeyScraper('ahl')

# Get player stats (season 90 = 2024-25)
stats = ahl.player_stats(season=90, position='skaters', limit=30)

print("Top 30 AHL skaters:")
display(stats[['name', 'teamCode', 'GP', 'G', 'A', 'PTS']].head(30))

Top 30 AHL skaters:

                     name teamCode  GP   G   A  PTS
0         Jakob Pelletier      SYR  48  22  36   58
1         Laurent Dauphin      LAV  50  15  41   56
2       Alex Barré-Boulet      COL  52  17  37   54
3          Arthur Kaliyev      BEL  54  30  21   51
4            Alex Belzile      LAV  54  26  25   51
5           Seth Griffith      BAK  55  15  36   51
6            Conor Geekie      SYR  47  14  37   51
7          Cameron Hughes      TEX  52  13  38   51
8   Benoit-Olivier Groulx      TOR  53  27  23   50
9          Justin Robidas      CHI  48  22  28   50
10         Logan Morrison       CV  53  24  25   49
11          Jagger Firkus       CV  53  19  30   49
12       Tanner Laczynski      HSK  44  16  33   49
13          Bradly Nadeau      CHI  42  23  25   48
14          Patrick Brown      PRO  53  17  31   48
15           Quinn Hutson      BAK  50  25  22   47
16          Ben McCartney      TUC  49  21  26   47
17             Dylan Duke      SYR  54  27  19   46
18            Ilya Protas      HER  55  22  23   45
19            Rory Kerins      CGY  50  17  28   45
20      Felix Unger Sörum      CHI  51  11  34   45
21              Zac Jones      ROC  42   7  38   45
22             Martin Frk      CGY  55  20  24   44
23    Luca Del Bel Belluz      CLE  42  16  28   44
24        Viljami Marjala      BAK  55  13  31   44
25              Ryan Ufko      MIL  50  11  33   44
26             Isak Rosén      ROC  37  25  18   43
27       Mitchell Chaffee      SYR  42  18  25   43
28          Cameron Hebig      TUC  49  17  26   43
29       Xavier Bourgault      BEL  54  16  27   43

In [28]:
# Get AHL goalie stats
goalies = ahl.player_stats(season=90, position='goalies', limit=20)

print("Top 20 AHL goalies:")
display(goalies[['name', 'teamCode', 'GP', 'wins', 'save_percentage', 'goals_against_average']].head(20))

Top 20 AHL goalies:

,name,teamCode,GP,wins,save_percentage,goals_against_average
0,Nolan Lalonde,CLE,1,0,1.000,0.00
1,Ethan Haider,MIL,1,1,0.957,1.00
2,Pyotr Kochetkov,CHI,1,1,0.957,1.00
3,Kyle Keyser,COL,11,8,0.943,1.49
4,Kevin Mandolese,SYR,2,2,0.933,1.50
5,Carter Gylander,GR,7,6,0.943,1.57
6,Michael DiPietro,PRO,33,25,0.938,1.78
7,Jack LaFontaine,CV,5,4,0.933,1.84
8,Michal Postava,GR,17,11,0.934,1.88
9,Isaiah Saville,ONT,8,6,0.916,1.91
10,Dustin Tokarski,GR,2,1,0.929,1.92
11,Sebastian Cossa,GR,31,24,0.927,1.99
12,Jon Gillies,SYR,2,2,0.933,2.00
13,Ukko-Pekka Luukkonen,ROC,1,1,0.913,2.01
14,Carl Lindbom,HSK,20,12,0.928,2.10
15,Sergei Murashov,WBS,29,20,0.924,2.12
16,Maxim Pavlenko,WBS,4,3,0.912,2.16
17,Brandon Halverson,SYR,30,20,0.912,2.17
18,Simon Zajicek,PRO,15,11,0.923,2.19
19,Jeremy Smith,BRI,5,1,0.907,2.20

## Comparing Across Leagues

Since all leagues return pandas DataFrames with similar structures, it's easy to compare across leagues.

In [29]:
# Get top scorer from each league
leagues_seasons = {'qmjhl': 90, 'ohl': 83, 'whl': 289}

top_scorers = []

for league, season in leagues_seasons.items():
    stats = scrape(league, 'stats', season=season, position='skaters', limit=1)
    if len(stats) > 0:
        top_scorer = stats.iloc[0]
        top_scorers.append({
            'league': league.upper(),
            'player': top_scorer.get('name', 'N/A'),
            'team': top_scorer.get('teamCode', 'N/A'),
            'points': top_scorer.get('PTS', 0),
        })

comparison = pd.DataFrame(top_scorers)
print("Top scorer in each league:")
display(comparison)

Top scorer in each league:

  league              player team  points
0  QMJHL  Radulov, Alexander  Que     152
1    OHL       Nikita Klepov  SAG      87
2    WHL           Liam Ruck   MH      93

## Finding Season IDs

Each league uses different season IDs. Here are the current ones (2025-26 season):

- **QMJHL**: 211 (current), 90 (2005-06 used above as example)
- **OHL**: 83
- **WHL**: 289
- **AHL**: 90

To find the correct season ID, use `HockeyScraper(league).current_season_id` or browse available seasons with `HockeyScraper(league).get_seasons()`.

## Team IDs

Each team has a unique ID. To get all teams and their IDs:
- Use `team_id=-1` in schedule queries to see all teams
- Check the league's website
- Look at roster or stats data which includes team information

In [30]:
# Example: Get all teams from a schedule query
schedule = scrape('ohl', 'schedule', season=83, team_id=-1)

if 'homeTeam' in schedule.columns and 'awayTeam' in schedule.columns:
    teams = pd.concat([schedule['homeTeam'], schedule['awayTeam']]).dropna().unique()
    print(f"OHL Teams ({len(teams)}):")
    for team in sorted(teams):
        print(f"  - {team}")

OHL Teams (20):
  - Barrie Colts
  - Brampton Steelheads
  - Brantford Bulldogs
  - Erie Otters
  - Flint Firebirds
  - Guelph Storm
  - Kingston Frontenacs
  - Kitchener Rangers
  - London Knights
  - Niagara IceDogs
  - North Bay Battalion
  - Oshawa Generals
  - Ottawa 67's
  - Owen Sound Attack
  - Peterborough Petes
  - Saginaw Spirit
  - Sarnia Sting
  - Soo Greyhounds
  - Sudbury Wolves
  - Windsor Spitfires

## Data Transformation: nhlify

The `nhlify=True` parameter in play-by-play queries applies NHL-style transformations:
- Merges shot and goal events
- Standardizes event types
- Cleans up data inconsistencies

In [33]:
# Example: Compare with and without nhlify
game_id = 31171  # Replace with valid game ID

try:
    # Without nhlify
    pbp_raw = scrape('qmjhl', 'pbp', game_id=game_id, nhlify=False)
    
    # With nhlify
    pbp_clean = scrape('qmjhl', 'pbp', game_id=game_id, nhlify=True)
    
    print(f"Raw events: {len(pbp_raw)}")
    print(f"Cleaned events: {len(pbp_clean)}")
except Exception as e:
    print(f"Error: {e}")

Raw events: 192
Cleaned events: 186

## Summary

This notebook covered:
- QMJHL, OHL, WHL, and AHL data scraping
- Player stats (skaters and goalies)
- Standings and schedules
- Play-by-play data
- Comparing across leagues
- Data transformation with nhlify

## Next Steps

- **04_advanced_features.ipynb** - Learn about caching, rate limiting, and advanced transformations